// cheer_stars_i18n.dart
//
// 🆕 [부모 운동 응원별 2026-09-29] 부모 운동 응원별 기능 전체의 12개 언어 번역 사전.
// 화면(운동 응원별 화면·학부모방 카드·학생 황금색 카드)은 글자를 직접 쓰지 않고
// 모두 이 사전을 부른다. 문구를 고칠 때는 이 파일 하나만 고치면 된다.
//
// 규칙 (원장님 원칙)
// - 한국어(KO): 큰 제목·중간 제목만 영문+한글, 나머지는 한글
// - English(EN): 영어만
// - 10개 언어: 그 언어만
// - 없는 언어는 영어로, 영어도 없으면 한국어로 대체
// - {n} 같은 자리는 cs(..., args: {'n': 5})로 채움

import 'app_language_service.dart';

const Map<String, Map<String, String>> kCheerStarsText = {
  // ---------------- 제목 · 중간 제목 ----------------
  'appTitle': {'KO': '부모 가족 응원', 'EN': 'CHEER STARS', 'JA': '家族応援スター', 'ZH': '家人加油星', // 🆕 [2026-10-02] 부모 + 응원 가족이 함께 쓰는 화면이라 이름 변경
    'FR': "Étoiles d'encouragement", 'DE': 'Anfeuerungssterne', 'RU': 'Звёзды поддержки', 'AR': 'نجوم التشجيع', 'HI': 'प्रोत्साहन सितारे', 'VI': 'Sao cổ vũ', 'ES': 'Estrellas de ánimo', 'TH': 'ดาวให้กำลังใจ'},
  'secBank': {'KO': '나의 별 통장', 'EN': 'MY STAR BANK', 'JA': 'わたしの星の貯金', 'ZH': '我的星星存折', 'FR': "Ma banque d'étoiles", 'DE': 'Meine Sternenbank', 'RU': 'Мой банк звёзд', 'AR': 'بنك نجومي', 'HI': 'मेरा सितारा बैंक', 'VI': 'Ngân hàng sao của tôi', 'ES': 'Mi banco de estrellas', 'TH': 'ธนาคารดาวของฉัน'},
  'secChoose': {'KO': '운동 고르기', 'EN': 'CHOOSE EXERCISE', 'JA': '運動を選ぶ', 'ZH': '选择运动', 'FR': 'Choisir un sport', 'DE': 'Sportart wählen', 'RU': 'Выберите занятие', 'AR': 'اختر التمرين', 'HI': 'व्यायाम चुनें', 'VI': 'Chọn môn tập', 'ES': 'Elegir ejercicio', 'TH': 'เลือกการออกกำลังกาย'},
  'secTimer': {'KO': '운동 타이머', 'EN': 'EXERCISE TIMER', 'JA': '運動タイマー', 'ZH': '运动计时器', 'FR': 'Minuteur de sport', 'DE': 'Trainings-Timer', 'RU': 'Таймер тренировки', 'AR': 'مؤقت التمرين', 'HI': 'व्यायाम टाइमर', 'VI': 'Hẹn giờ tập luyện', 'ES': 'Temporizador de ejercicio', 'TH': 'ตัวจับเวลาออกกำลังกาย'},
  'secWorkouts': {'KO': '나의 운동 기록', 'EN': 'MY WORKOUTS', 'JA': 'わたしの運動記録', 'ZH': '我的运动记录', 'FR': 'Mes séances', 'DE': 'Meine Trainings', 'RU': 'Мои тренировки', 'AR': 'تماريني', 'HI': 'मेरे व्यायाम', 'VI': 'Buổi tập của tôi', 'ES': 'Mis entrenamientos', 'TH': 'บันทึกการออกกำลังกายของฉัน'},
  'secCollection': {'KO': '나의 별 수집 현황', 'EN': 'STAR COLLECTION', 'JA': '星の集まり具合', 'ZH': '我的星星收集', 'FR': "Ma collection d'étoiles", 'DE': 'Meine Sternensammlung', 'RU': 'Моя коллекция звёзд', 'AR': 'مجموعة نجومي', 'HI': 'मेरा सितारा संग्रह', 'VI': 'Bộ sưu tập sao', 'ES': 'Mi colección de estrellas', 'TH': 'สรุปดาวที่สะสม'},
  'secSend': {'KO': '자녀에게 보내기', 'EN': 'SEND TO CHILD', 'JA': '子どもに送る', 'ZH': '送给孩子', 'FR': "Envoyer à l'enfant", 'DE': 'An das Kind senden', 'RU': 'Отправить ребёнку', 'AR': 'إرسال إلى الطفل', 'HI': 'बच्चे को भेजें', 'VI': 'Gửi cho con', 'ES': 'Enviar al hijo/a', 'TH': 'ส่งให้ลูก'},
  'secHow': {'KO': '별 모으는 방법', 'EN': 'HOW TO EARN', 'JA': '星の集め方', 'ZH': '如何获得星星', 'FR': 'Comment gagner des étoiles', 'DE': 'So sammelst du Sterne', 'RU': 'Как заработать звёзды', 'AR': 'كيف تكسب النجوم', 'HI': 'सितारे कैसे कमाएं', 'VI': 'Cách nhận sao', 'ES': 'Cómo ganar estrellas', 'TH': 'วิธีสะสมดาว'},

  // ---------------- 공통 단위 ----------------
  'nStars': {'KO': '{n}개', 'EN': '{n} stars', 'JA': '{n}個', 'ZH': '{n}颗', 'FR': '{n} étoiles', 'DE': '{n} Sterne', 'RU': '{n} звёзд', 'AR': '{n} نجمة', 'HI': '{n} सितारे', 'VI': '{n} sao', 'ES': '{n} estrellas', 'TH': '{n} ดวง'},
  'nMin': {'KO': '{n}분', 'EN': '{n} min', 'JA': '{n}分', 'ZH': '{n}分钟', 'FR': '{n} min', 'DE': '{n} Min.', 'RU': '{n} мин', 'AR': '{n} دقيقة', 'HI': '{n} मिनट', 'VI': '{n} phút', 'ES': '{n} min', 'TH': '{n} นาที'},
  'unitMin': {'KO': '분', 'EN': 'min', 'JA': '分', 'ZH': '分钟', 'FR': 'min', 'DE': 'Min.', 'RU': 'мин', 'AR': 'دقيقة', 'HI': 'मिनट', 'VI': 'phút', 'ES': 'min', 'TH': 'นาที'},
  'unitStar': {'KO': '개', 'EN': 'stars', 'JA': '個', 'ZH': '颗', 'FR': 'étoiles', 'DE': 'Sterne', 'RU': 'звёзд', 'AR': 'نجمة', 'HI': 'सितारे', 'VI': 'sao', 'ES': 'estrellas', 'TH': 'ดวง'},
  'codeLabel': {'KO': '코드 {c}', 'EN': 'Code {c}', 'JA': 'コード {c}', 'ZH': '代码 {c}', 'FR': 'Code {c}', 'DE': 'Code {c}', 'RU': 'Код {c}', 'AR': 'الرمز {c}', 'HI': 'कोड {c}', 'VI': 'Mã {c}', 'ES': 'Código {c}', 'TH': 'รหัส {c}'},

  // ---------------- 운동 종목 ----------------
  'ex_walking': {'KO': '걷기', 'EN': 'Walking', 'JA': 'ウォーキング', 'ZH': '步行', 'FR': 'Marche', 'DE': 'Gehen', 'RU': 'Ходьба', 'AR': 'المشي', 'HI': 'पैदल चलना', 'VI': 'Đi bộ', 'ES': 'Caminar', 'TH': 'เดิน'},
  'ex_running': {'KO': '달리기', 'EN': 'Running', 'JA': 'ランニング', 'ZH': '跑步', 'FR': 'Course', 'DE': 'Laufen', 'RU': 'Бег', 'AR': 'الجري', 'HI': 'दौड़ना', 'VI': 'Chạy bộ', 'ES': 'Correr', 'TH': 'วิ่ง'},
  'ex_gym': {'KO': '헬스', 'EN': 'Gym', 'JA': 'ジム', 'ZH': '健身', 'FR': 'Musculation', 'DE': 'Fitnessstudio', 'RU': 'Тренажёрный зал', 'AR': 'الصالة الرياضية', 'HI': 'जिम', 'VI': 'Tập gym', 'ES': 'Gimnasio', 'TH': 'ฟิตเนส'},
  'ex_cycling': {'KO': '자전거', 'EN': 'Cycling', 'JA': 'サイクリング', 'ZH': '骑行', 'FR': 'Vélo', 'DE': 'Radfahren', 'RU': 'Велосипед', 'AR': 'ركوب الدراجة', 'HI': 'साइकिलिंग', 'VI': 'Đạp xe', 'ES': 'Ciclismo', 'TH': 'ปั่นจักรยาน'},
  'ex_swimming': {'KO': '수영', 'EN': 'Swimming', 'JA': '水泳', 'ZH': '游泳', 'FR': 'Natation', 'DE': 'Schwimmen', 'RU': 'Плавание', 'AR': 'السباحة', 'HI': 'तैराकी', 'VI': 'Bơi lội', 'ES': 'Natación', 'TH': 'ว่ายน้ำ'},
  'ex_yoga': {'KO': '요가', 'EN': 'Yoga', 'JA': 'ヨガ', 'ZH': '瑜伽', 'FR': 'Yoga', 'DE': 'Yoga', 'RU': 'Йога', 'AR': 'اليوغا', 'HI': 'योग', 'VI': 'Yoga', 'ES': 'Yoga', 'TH': 'โยคะ'},
  'ex_pilates': {'KO': '필라테스', 'EN': 'Pilates', 'JA': 'ピラティス', 'ZH': '普拉提', 'FR': 'Pilates', 'DE': 'Pilates', 'RU': 'Пилатес', 'AR': 'البيلاتس', 'HI': 'पिलेट्स', 'VI': 'Pilates', 'ES': 'Pilates', 'TH': 'พิลาทิส'},
  'ex_hiking': {'KO': '등산', 'EN': 'Hiking', 'JA': '登山', 'ZH': '登山', 'FR': 'Randonnée', 'DE': 'Wandern', 'RU': 'Поход', 'AR': 'المشي الجبلي', 'HI': 'पर्वतारोहण', 'VI': 'Leo núi', 'ES': 'Senderismo', 'TH': 'เดินป่า'},
  'ex_etc': {'KO': '기타', 'EN': 'Other', 'JA': 'その他', 'ZH': '其他', 'FR': 'Autre', 'DE': 'Sonstiges', 'RU': 'Другое', 'AR': 'أخرى', 'HI': 'अन्य', 'VI': 'Khác', 'ES': 'Otro', 'TH': 'อื่น ๆ'},

  // ---------------- 나의 별 통장 ----------------
  'bankSaved': {'KO': '모아 둔 별', 'EN': 'Saved stars', 'JA': '貯めた星', 'ZH': '攒下的星星', 'FR': 'Étoiles épargnées', 'DE': 'Gesparte Sterne', 'RU': 'Накоплено звёзд', 'AR': 'النجوم المدخرة', 'HI': 'जमा सितारे', 'VI': 'Sao đã tích lũy', 'ES': 'Estrellas ahorradas', 'TH': 'ดาวที่สะสมไว้'},
  'bankTotal': {'KO': '지금까지 모은 별 {n}개', 'EN': 'Total earned so far: {n}', 'JA': 'これまでに集めた星 {n}個', 'ZH': '至今共获得 {n} 颗星星', 'FR': 'Total gagné : {n} étoiles', 'DE': 'Bisher gesammelt: {n} Sterne', 'RU': 'Всего заработано: {n}', 'AR': 'إجمالي ما جمعته: {n} نجمة', 'HI': 'अब तक कमाए: {n} सितारे', 'VI': 'Tổng đã nhận: {n} sao', 'ES': 'Total ganado: {n} estrellas', 'TH': 'สะสมทั้งหมด {n} ดวง'},

  // ---------------- 운동 타이머 ----------------
  'statusUnder': {'KO': '{m}분 / 목표 60분 ({p}%)', 'EN': '{m} min / goal 60 min ({p}%)', 'JA': '{m}分 / 目標60分 ({p}%)', 'ZH': '{m}分钟 / 目标60分钟 ({p}%)', 'FR': '{m} min / objectif 60 min ({p} %)', 'DE': '{m} Min. / Ziel 60 Min. ({p} %)', 'RU': '{m} мин / цель 60 мин ({p}%)', 'AR': '{m} دقيقة / الهدف 60 دقيقة ({p}%)', 'HI': '{m} मिनट / लक्ष्य 60 मिनट ({p}%)', 'VI': '{m} phút / mục tiêu 60 phút ({p}%)', 'ES': '{m} min / meta 60 min ({p} %)', 'TH': '{m} นาที / เป้าหมาย 60 นาที ({p}%)'},
  'statusOver': {'KO': '총 {m}분 · 지금 칸 {s}/10분', 'EN': 'Total {m} min · current block {s}/10 min', 'JA': '合計{m}分 · 現在の区間 {s}/10分', 'ZH': '共{m}分钟 · 当前格 {s}/10分钟', 'FR': 'Total {m} min · bloc actuel {s}/10 min', 'DE': 'Gesamt {m} Min. · aktueller Block {s}/10 Min.', 'RU': 'Всего {m} мин · текущий блок {s}/10 мин', 'AR': 'المجموع {m} دقيقة · الخانة الحالية {s}/10', 'HI': 'कुल {m} मिनट · मौजूदा खंड {s}/10 मिनट', 'VI': 'Tổng {m} phút · ô hiện tại {s}/10 phút', 'ES': 'Total {m} min · bloque actual {s}/10 min', 'TH': 'รวม {m} นาที · ช่องปัจจุบัน {s}/10 นาที'},
  'barUnder': {'KO': '{m}분\n({p}%)', 'EN': '{m} min\n({p}%)', 'JA': '{m}分\n({p}%)', 'ZH': '{m}分钟\n({p}%)', 'FR': '{m} min\n({p} %)', 'DE': '{m} Min.\n({p} %)', 'RU': '{m} мин\n({p}%)', 'AR': '{m} د\n({p}%)', 'HI': '{m} मि.\n({p}%)', 'VI': '{m} phút\n({p}%)', 'ES': '{m} min\n({p} %)', 'TH': '{m} นาที\n({p}%)'},
  'barOver': {'KO': '{a}~{b}분', 'EN': '{a}–{b} min', 'JA': '{a}〜{b}分', 'ZH': '{a}~{b}分钟', 'FR': '{a}–{b} min', 'DE': '{a}–{b} Min.', 'RU': '{a}–{b} мин', 'AR': '{a}–{b} د', 'HI': '{a}–{b} मि.', 'VI': '{a}–{b} phút', 'ES': '{a}–{b} min', 'TH': '{a}–{b} นาที'},
  'sessionStars': {'KO': '이번 운동으로 모은 별 +{n}개', 'EN': 'Stars from this workout: +{n}', 'JA': '今回の運動で集めた星 +{n}個', 'ZH': '本次运动获得星星 +{n}颗', 'FR': 'Étoiles de cette séance : +{n}', 'DE': 'Sterne aus diesem Training: +{n}', 'RU': 'Звёзды за эту тренировку: +{n}', 'AR': 'نجوم هذا التمرين: +{n}', 'HI': 'इस व्यायाम के सितारे: +{n}', 'VI': 'Sao từ buổi tập này: +{n}', 'ES': 'Estrellas de este entrenamiento: +{n}', 'TH': 'ดาวจากการออกกำลังกายครั้งนี้ +{n} ดวง'},
  'btnSaving': {'KO': '저장 중...', 'EN': 'Saving...', 'JA': '保存中...', 'ZH': '保存中...', 'FR': 'Enregistrement...', 'DE': 'Wird gespeichert...', 'RU': 'Сохранение...', 'AR': 'جارٍ الحفظ...', 'HI': 'सहेजा जा रहा है...', 'VI': 'Đang lưu...', 'ES': 'Guardando...', 'TH': 'กำลังบันทึก...'},
  'btnPause': {'KO': '일시 정지', 'EN': 'Pause', 'JA': '一時停止', 'ZH': '暂停', 'FR': 'Pause', 'DE': 'Pause', 'RU': 'Пауза', 'AR': 'إيقاف مؤقت', 'HI': 'रोकें', 'VI': 'Tạm dừng', 'ES': 'Pausa', 'TH': 'หยุดชั่วคราว'},
  'btnStart': {'KO': '운동 시작', 'EN': 'Start workout', 'JA': '運動スタート', 'ZH': '开始运动', 'FR': 'Commencer', 'DE': 'Training starten', 'RU': 'Начать', 'AR': 'ابدأ التمرين', 'HI': 'व्यायाम शुरू करें', 'VI': 'Bắt đầu tập', 'ES': 'Empezar', 'TH': 'เริ่มออกกำลังกาย'},
  'btnResume': {'KO': '다시 시작', 'EN': 'Resume', 'JA': '再開', 'ZH': '继续', 'FR': 'Reprendre', 'DE': 'Fortsetzen', 'RU': 'Продолжить', 'AR': 'استئناف', 'HI': 'फिर से शुरू करें', 'VI': 'Tiếp tục', 'ES': 'Reanudar', 'TH': 'เริ่มต่อ'},
  'btnFinishToday': {'KO': '오늘 운동 끝내기', 'EN': "Finish today's workout", 'JA': '今日の運動を終える', 'ZH': '结束今天的运动', 'FR': 'Terminer la séance du jour', 'DE': 'Heutiges Training beenden', 'RU': 'Завершить тренировку', 'AR': 'إنهاء تمرين اليوم', 'HI': 'आज का व्यायाम खत्म करें', 'VI': 'Kết thúc buổi tập hôm nay', 'ES': 'Terminar el entrenamiento de hoy', 'TH': 'จบการออกกำลังกายวันนี้'},

  // ---------------- 안내창 ----------------
  'leaveTitle': {'KO': '운동을 끝내고 나갈까요?', 'EN': 'Finish and leave?', 'JA': '運動を終えて戻りますか？', 'ZH': '结束运动并离开吗？', 'FR': 'Terminer et quitter ?', 'DE': 'Beenden und verlassen?', 'RU': 'Завершить и выйти?', 'AR': 'هل تريد الإنهاء والخروج؟', 'HI': 'व्यायाम खत्म करके बाहर जाएं?', 'VI': 'Kết thúc và thoát?', 'ES': '¿Terminar y salir?', 'TH': 'จบการออกกำลังกายและออกไหม?'},
  'leaveMsg': {'KO': '지금까지 한 운동은 기록되고, 받을 보너스 별도 계산됩니다.', 'EN': 'Your workout so far will be saved and any bonus stars will be counted.', 'JA': 'ここまでの運動は記録され、ボーナスの星も計算されます。', 'ZH': '到目前为止的运动会被记录，奖励星星也会计算。', 'FR': 'Votre séance sera enregistrée et les étoiles bonus comptées.', 'DE': 'Dein bisheriges Training wird gespeichert und Bonussterne werden berechnet.', 'RU': 'Тренировка будет сохранена, бонусные звёзды начислены.', 'AR': 'سيتم حفظ تمرينك وحساب النجوم الإضافية.', 'HI': 'अब तक का व्यायाम सहेजा जाएगा और बोनस सितारे गिने जाएंगे।', 'VI': 'Buổi tập đến giờ sẽ được lưu và sao thưởng sẽ được tính.', 'ES': 'Tu entrenamiento se guardará y se contarán las estrellas extra.', 'TH': 'การออกกำลังกายจะถูกบันทึก และคำนวณดาวโบนัสให้'},
  'btnKeepGoing': {'KO': '계속 운동', 'EN': 'Keep going', 'JA': '運動を続ける', 'ZH': '继续运动', 'FR': 'Continuer', 'DE': 'Weitermachen', 'RU': 'Продолжить', 'AR': 'متابعة', 'HI': 'जारी रखें', 'VI': 'Tập tiếp', 'ES': 'Seguir', 'TH': 'ออกกำลังกายต่อ'},
  'btnFinishLeave': {'KO': '끝내고 나가기', 'EN': 'Finish & leave', 'JA': '終えて戻る', 'ZH': '结束并离开', 'FR': 'Terminer et quitter', 'DE': 'Beenden & verlassen', 'RU': 'Завершить и выйти', 'AR': 'إنهاء وخروج', 'HI': 'खत्म करके जाएं', 'VI': 'Kết thúc và thoát', 'ES': 'Terminar y salir', 'TH': 'จบแล้วออก'},
  'stayTitle': {'KO': '이 화면에 머물러 주세요', 'EN': 'Please stay on this screen', 'JA': 'この画面のままにしてください', 'ZH': '请停留在此画面', 'FR': 'Restez sur cet écran', 'DE': 'Bitte auf diesem Bildschirm bleiben', 'RU': 'Оставайтесь на этом экране', 'AR': 'يرجى البقاء في هذه الشاشة', 'HI': 'कृपया इसी स्क्रीन पर रहें', 'VI': 'Vui lòng ở lại màn hình này', 'ES': 'Permanece en esta pantalla', 'TH': 'กรุณาอยู่ที่หน้าจอนี้'},
  'stayMsg': {'KO': '운동 중에 다른 앱으로 나가면 타이머가 자동으로 멈춥니다.\n자녀의 공부 타이머와 같은 규칙이에요.', 'EN': "If you switch to another app, the timer pauses automatically.\nIt's the same rule as your child's study timer.", 'JA': '運動中に他のアプリへ移るとタイマーが自動で止まります。\nお子様の勉強タイマーと同じルールです。', 'ZH': '运动中切换到其他应用，计时器会自动暂停。\n和孩子的学习计时器是同样的规则。', 'FR': "Si vous passez à une autre application, le minuteur se met en pause.\nC'est la même règle que le minuteur d'étude de votre enfant.", 'DE': 'Wenn du zu einer anderen App wechselst, pausiert der Timer automatisch.\nDas ist dieselbe Regel wie beim Lern-Timer deines Kindes.', 'RU': 'При переходе в другое приложение таймер останавливается.\nТо же правило, что и у учебного таймера ребёнка.', 'AR': 'إذا انتقلت إلى تطبيق آخر يتوقف المؤقت تلقائيًا.\nإنها القاعدة نفسها في مؤقت دراسة طفلك.', 'HI': 'दूसरे ऐप पर जाने पर टाइमर अपने आप रुक जाता है।\nयही नियम बच्चे के पढ़ाई टाइमर में भी है।', 'VI': 'Nếu chuyển sang ứng dụng khác, bộ hẹn giờ sẽ tự dừng.\nĐây cũng là quy tắc của bộ hẹn giờ học của con.', 'ES': 'Si cambias a otra app, el temporizador se pausa solo.\nEs la misma regla que el temporizador de estudio de tu hijo/a.', 'TH': 'ถ้าออกไปแอปอื่น ตัวจับเวลาจะหยุดเอง\nเป็นกติกาเดียวกับตัวจับเวลาเรียนของลูก'},
  'btnGotIt': {'KO': '알겠습니다', 'EN': 'Got it', 'JA': 'わかりました', 'ZH': '知道了', 'FR': "J'ai compris", 'DE': 'Verstanden', 'RU': 'Понятно', 'AR': 'حسنًا', 'HI': 'समझ गया', 'VI': 'Đã hiểu', 'ES': 'Entendido', 'TH': 'เข้าใจแล้ว'},
  'pauseTitle': {'KO': '잠시 멈췄습니다', 'EN': 'Paused', 'JA': '一時停止しました', 'ZH': '已暂停', 'FR': 'En pause', 'DE': 'Pausiert', 'RU': 'Пауза', 'AR': 'متوقف مؤقتًا', 'HI': 'रुका हुआ', 'VI': 'Đã tạm dừng', 'ES': 'En pausa', 'TH': 'หยุดชั่วคราวแล้ว'},
  'pauseMsg': {'KO': '계속 운동할까요, 오늘 운동을 끝낼까요?', 'EN': "Keep going, or finish today's workout?", 'JA': '運動を続けますか、今日の運動を終えますか？', 'ZH': '继续运动，还是结束今天的运动？', 'FR': 'Continuer ou terminer la séance du jour ?', 'DE': 'Weitermachen oder das heutige Training beenden?', 'RU': 'Продолжить или завершить тренировку?', 'AR': 'هل تتابع أم تنهي تمرين اليوم؟', 'HI': 'जारी रखें या आज का व्यायाम खत्म करें?', 'VI': 'Tập tiếp hay kết thúc buổi tập hôm nay?', 'ES': '¿Seguir o terminar el entrenamiento de hoy?', 'TH': 'จะออกกำลังกายต่อ หรือจบของวันนี้?'},
  'btnContinue': {'KO': '계속하기', 'EN': 'Continue', 'JA': '続ける', 'ZH': '继续', 'FR': 'Continuer', 'DE': 'Weiter', 'RU': 'Продолжить', 'AR': 'متابعة', 'HI': 'जारी रखें', 'VI': 'Tiếp tục', 'ES': 'Continuar', 'TH': 'ทำต่อ'},
  'btnFinish': {'KO': '끝내기', 'EN': 'Finish', 'JA': '終える', 'ZH': '结束', 'FR': 'Terminer', 'DE': 'Beenden', 'RU': 'Завершить', 'AR': 'إنهاء', 'HI': 'खत्म करें', 'VI': 'Kết thúc', 'ES': 'Terminar', 'TH': 'จบ'},

  // ---------------- 운동 완료 팝업 ----------------
  'resultTitle': {'KO': '오늘 운동 완료', 'EN': 'WORKOUT COMPLETE', 'JA': '今日の運動完了', 'ZH': '今日运动完成', 'FR': 'Séance terminée', 'DE': 'Training abgeschlossen', 'RU': 'Тренировка завершена', 'AR': 'اكتمل التمرين', 'HI': 'व्यायाम पूरा', 'VI': 'Hoàn thành buổi tập', 'ES': 'Entrenamiento completo', 'TH': 'ออกกำลังกายเสร็จแล้ว'},
  'resultTimeStars': {'KO': '운동 시간 별', 'EN': 'Workout time stars', 'JA': '運動時間の星', 'ZH': '运动时间星星', 'FR': 'Étoiles de durée', 'DE': 'Zeit-Sterne', 'RU': 'Звёзды за время', 'AR': 'نجوم وقت التمرين', 'HI': 'समय के सितारे', 'VI': 'Sao theo thời gian', 'ES': 'Estrellas por tiempo', 'TH': 'ดาวจากเวลาออกกำลังกาย'},
  'resultTotal': {'KO': '⭐ 모두 받은 별', 'EN': '⭐ Total stars', 'JA': '⭐ もらった星の合計', 'ZH': '⭐ 共获得星星', 'FR': '⭐ Total des étoiles', 'DE': '⭐ Sterne gesamt', 'RU': '⭐ Всего звёзд', 'AR': '⭐ مجموع النجوم', 'HI': '⭐ कुल सितारे', 'VI': '⭐ Tổng số sao', 'ES': '⭐ Total de estrellas', 'TH': '⭐ ดาวที่ได้รวม'},
  'resultSaved': {'KO': '{ex} 운동 기록에 {m}분이 저장되었습니다.\n거리·걸음수 같은 세부 내용을 더하면 운동 분석이 더 정확해집니다.', 'EN': '{m} min was saved to your {ex} records.\nAdd details like distance or steps for a more accurate analysis.', 'JA': '{ex}の運動記録に{m}分を保存しました。\n距離や歩数などを加えると分析がより正確になります。', 'ZH': '已将{m}分钟保存到{ex}运动记录。\n补充距离、步数等细节，分析会更准确。', 'FR': '{m} min enregistrées dans vos séances de {ex}.\nAjoutez distance ou pas pour une analyse plus précise.', 'DE': '{m} Min. wurden in deinen {ex}-Einträgen gespeichert.\nMit Details wie Distanz oder Schritten wird die Analyse genauer.', 'RU': '{m} мин сохранено в записях «{ex}».\nДобавьте расстояние или шаги для точного анализа.', 'AR': 'تم حفظ {m} دقيقة في سجل {ex}.\nأضف تفاصيل مثل المسافة أو الخطوات لتحليل أدق.', 'HI': '{ex} रिकॉर्ड में {m} मिनट सहेजे गए।\nदूरी या कदम जैसी जानकारी जोड़ने से विश्लेषण सटीक होगा।', 'VI': 'Đã lưu {m} phút vào nhật ký {ex}.\nThêm quãng đường, số bước để phân tích chính xác hơn.', 'ES': 'Se guardaron {m} min en tus registros de {ex}.\nAñade distancia o pasos para un análisis más preciso.', 'TH': 'บันทึก {m} นาทีในบันทึก{ex}แล้ว\nใส่ระยะทาง จำนวนก้าว ฯลฯ เพิ่ม การวิเคราะห์จะแม่นยำขึ้น'},
  'btnLater': {'KO': '나중에', 'EN': 'Later', 'JA': 'あとで', 'ZH': '以后再说', 'FR': 'Plus tard', 'DE': 'Später', 'RU': 'Позже', 'AR': 'لاحقًا', 'HI': 'बाद में', 'VI': 'Để sau', 'ES': 'Más tarde', 'TH': 'ไว้ทีหลัง'},
  'btnOk': {'KO': '확인', 'EN': 'OK', 'JA': 'OK', 'ZH': '确定', 'FR': 'OK', 'DE': 'OK', 'RU': 'ОК', 'AR': 'موافق', 'HI': 'ठीक है', 'VI': 'OK', 'ES': 'Aceptar', 'TH': 'ตกลง'},
  'btnDetail': {'KO': '세부 기록하기', 'EN': 'Add details', 'JA': '詳しく記録する', 'ZH': '填写详细记录', 'FR': 'Ajouter des détails', 'DE': 'Details eintragen', 'RU': 'Добавить детали', 'AR': 'إضافة التفاصيل', 'HI': 'विवरण जोड़ें', 'VI': 'Ghi chi tiết', 'ES': 'Añadir detalles', 'TH': 'บันทึกรายละเอียด'},
  'recordMemo': {'KO': '부모 운동 응원별 타이머', 'EN': 'Cheer Stars timer', 'JA': '運動応援スタータイマー', 'ZH': '运动加油星计时器', 'FR': "Minuteur Étoiles d'encouragement", 'DE': 'Anfeuerungssterne-Timer', 'RU': 'Таймер «Звёзды поддержки»', 'AR': 'مؤقت نجوم التشجيع', 'HI': 'प्रोत्साहन सितारे टाइमर', 'VI': 'Hẹn giờ Sao cổ vũ', 'ES': 'Temporizador Estrellas de ánimo', 'TH': 'ตัวจับเวลาดาวให้กำลังใจ'},

  // ---------------- 나의 운동 기록 · 수정 팝업 ----------------
  'recordsEmpty': {'KO': '아직 타이머로 한 운동이 없습니다. 위에서 운동을 시작해 보세요.', 'EN': 'No timer workouts yet. Start one above.', 'JA': 'まだタイマーでの運動はありません。上から始めてみましょう。', 'ZH': '还没有用计时器的运动记录。请在上方开始运动。', 'FR': 'Aucune séance chronométrée pour le moment. Commencez-en une ci-dessus.', 'DE': 'Noch keine Timer-Trainings. Starte oben eines.', 'RU': 'Тренировок по таймеру пока нет. Начните выше.', 'AR': 'لا توجد تمارين بالمؤقت بعد. ابدأ من الأعلى.', 'HI': 'अभी टाइमर वाला कोई व्यायाम नहीं है। ऊपर से शुरू करें।', 'VI': 'Chưa có buổi tập bằng hẹn giờ. Hãy bắt đầu ở trên.', 'ES': 'Aún no hay entrenamientos con temporizador. Empieza arriba.', 'TH': 'ยังไม่มีการออกกำลังกายด้วยตัวจับเวลา ลองเริ่มด้านบนเลย'},
  'editTitle': {'KO': '운동 기록 수정', 'EN': 'Edit workout', 'JA': '運動記録の修正', 'ZH': '修改运动记录', 'FR': 'Modifier la séance', 'DE': 'Training bearbeiten', 'RU': 'Изменить тренировку', 'AR': 'تعديل التمرين', 'HI': 'व्यायाम संपादित करें', 'VI': 'Sửa buổi tập', 'ES': 'Editar entrenamiento', 'TH': 'แก้ไขบันทึกการออกกำลังกาย'},
  'fldExercise': {'KO': 'Exercise / 운동 종목', 'EN': 'Exercise', 'JA': '運動の種類', 'ZH': '运动项目', 'FR': 'Sport', 'DE': 'Sportart', 'RU': 'Вид занятия', 'AR': 'نوع التمرين', 'HI': 'व्यायाम', 'VI': 'Môn tập', 'ES': 'Ejercicio', 'TH': 'ประเภทการออกกำลังกาย'},
  'fldDuration': {'KO': 'Duration / 운동 시간', 'EN': 'Duration', 'JA': '運動時間', 'ZH': '运动时长', 'FR': 'Durée', 'DE': 'Dauer', 'RU': 'Длительность', 'AR': 'المدة', 'HI': 'अवधि', 'VI': 'Thời lượng', 'ES': 'Duración', 'TH': 'ระยะเวลา'},
  'fldDate': {'KO': 'Date / 운동 날짜', 'EN': 'Date', 'JA': '日付', 'ZH': '日期', 'FR': 'Date', 'DE': 'Datum', 'RU': 'Дата', 'AR': 'التاريخ', 'HI': 'तारीख', 'VI': 'Ngày', 'ES': 'Fecha', 'TH': 'วันที่'},
  'fldMemo': {'KO': 'Memo / 메모', 'EN': 'Memo', 'JA': 'メモ', 'ZH': '备注', 'FR': 'Note', 'DE': 'Notiz', 'RU': 'Заметка', 'AR': 'ملاحظة', 'HI': 'नोट', 'VI': 'Ghi chú', 'ES': 'Nota', 'TH': 'บันทึกย่อ'},
  'openDetail': {'KO': '거리·걸음수 등 세부 기록 열기', 'EN': 'Open detailed record (distance, steps…)', 'JA': '距離・歩数などの詳細記録を開く', 'ZH': '打开详细记录（距离、步数等）', 'FR': 'Ouvrir le détail (distance, pas…)', 'DE': 'Details öffnen (Distanz, Schritte …)', 'RU': 'Открыть подробности (расстояние, шаги…)', 'AR': 'فتح السجل المفصل (المسافة، الخطوات…)', 'HI': 'विस्तृत रिकॉर्ड खोलें (दूरी, कदम…)', 'VI': 'Mở ghi chép chi tiết (quãng đường, số bước…)', 'ES': 'Abrir registro detallado (distancia, pasos…)', 'TH': 'เปิดบันทึกละเอียด (ระยะทาง จำนวนก้าว…)'},
  'editNote': {'KO': '기록을 고치거나 지워도 이미 받은 별은 그대로입니다.', 'EN': 'Editing or deleting a record does not change stars already earned.', 'JA': '記録を修正・削除しても、もらった星はそのままです。', 'ZH': '修改或删除记录，已获得的星星不变。', 'FR': "Modifier ou supprimer une séance ne change pas les étoiles déjà gagnées.", 'DE': 'Bearbeiten oder Löschen ändert bereits verdiente Sterne nicht.', 'RU': 'Изменение или удаление записи не влияет на полученные звёзды.', 'AR': 'تعديل السجل أو حذفه لا يغيّر النجوم التي حصلت عليها.', 'HI': 'रिकॉर्ड बदलने या हटाने से मिले सितारे नहीं बदलते।', 'VI': 'Sửa hoặc xóa ghi chép không làm thay đổi số sao đã nhận.', 'ES': 'Editar o borrar un registro no cambia las estrellas ya ganadas.', 'TH': 'แก้ไขหรือลบบันทึก ดาวที่ได้แล้วก็ยังอยู่เหมือนเดิม'},
  'errDuration': {'KO': '운동 시간은 1분에서 600분 사이로 입력해 주세요.', 'EN': 'Enter a duration between 1 and 600 minutes.', 'JA': '運動時間は1〜600分で入力してください。', 'ZH': '请输入1到600分钟之间的时长。', 'FR': 'Saisissez une durée entre 1 et 600 minutes.', 'DE': 'Bitte eine Dauer zwischen 1 und 600 Minuten eingeben.', 'RU': 'Введите от 1 до 600 минут.', 'AR': 'أدخل مدة بين 1 و600 دقيقة.', 'HI': '1 से 600 मिनट के बीच अवधि दर्ज करें।', 'VI': 'Nhập thời lượng từ 1 đến 600 phút.', 'ES': 'Introduce una duración entre 1 y 600 minutos.', 'TH': 'กรุณาใส่เวลา 1–600 นาที'},
  'btnDelete': {'KO': 'Delete / 삭제', 'EN': 'Delete', 'JA': '削除', 'ZH': '删除', 'FR': 'Supprimer', 'DE': 'Löschen', 'RU': 'Удалить', 'AR': 'حذف', 'HI': 'हटाएं', 'VI': 'Xóa', 'ES': 'Eliminar', 'TH': 'ลบ'},
  'btnClose': {'KO': 'Close / 닫기', 'EN': 'Close', 'JA': '閉じる', 'ZH': '关闭', 'FR': 'Fermer', 'DE': 'Schließen', 'RU': 'Закрыть', 'AR': 'إغلاق', 'HI': 'बंद करें', 'VI': 'Đóng', 'ES': 'Cerrar', 'TH': 'ปิด'},
  'btnSave': {'KO': 'Save / 저장', 'EN': 'Save', 'JA': '保存', 'ZH': '保存', 'FR': 'Enregistrer', 'DE': 'Speichern', 'RU': 'Сохранить', 'AR': 'حفظ', 'HI': 'सहेजें', 'VI': 'Lưu', 'ES': 'Guardar', 'TH': 'บันทึก'},
  'delTitle': {'KO': '이 운동 기록을 지울까요?', 'EN': 'Delete this workout?', 'JA': 'この運動記録を削除しますか？', 'ZH': '删除这条运动记录吗？', 'FR': 'Supprimer cette séance ?', 'DE': 'Dieses Training löschen?', 'RU': 'Удалить эту тренировку?', 'AR': 'حذف هذا التمرين؟', 'HI': 'यह व्यायाम हटाएं?', 'VI': 'Xóa buổi tập này?', 'ES': '¿Eliminar este entrenamiento?', 'TH': 'ลบบันทึกนี้ไหม?'},
  'delMsg': {'KO': '지운 기록은 되돌릴 수 없습니다.\n이미 받은 별은 그대로 남습니다.', 'EN': 'This cannot be undone.\nStars already earned will stay.', 'JA': '削除した記録は元に戻せません。\nもらった星はそのまま残ります。', 'ZH': '删除后无法恢复。\n已获得的星星会保留。', 'FR': 'Action irréversible.\nLes étoiles déjà gagnées restent.', 'DE': 'Das kann nicht rückgängig gemacht werden.\nVerdiente Sterne bleiben erhalten.', 'RU': 'Это нельзя отменить.\nПолученные звёзды сохранятся.', 'AR': 'لا يمكن التراجع عن ذلك.\nستبقى النجوم التي حصلت عليها.', 'HI': 'इसे वापस नहीं लाया जा सकता।\nमिले सितारे बने रहेंगे।', 'VI': 'Không thể hoàn tác.\nSố sao đã nhận vẫn được giữ.', 'ES': 'No se puede deshacer.\nLas estrellas ganadas se conservan.', 'TH': 'ย้อนกลับไม่ได้\nดาวที่ได้แล้วยังอยู่'},
  'btnCancel': {'KO': '취소', 'EN': 'Cancel', 'JA': 'キャンセル', 'ZH': '取消', 'FR': 'Annuler', 'DE': 'Abbrechen', 'RU': 'Отмена', 'AR': 'إلغاء', 'HI': 'रद्द करें', 'VI': 'Hủy', 'ES': 'Cancelar', 'TH': 'ยกเลิก'},
  'btnDel': {'KO': '삭제', 'EN': 'Delete', 'JA': '削除', 'ZH': '删除', 'FR': 'Supprimer', 'DE': 'Löschen', 'RU': 'Удалить', 'AR': 'حذف', 'HI': 'हटाएं', 'VI': 'Xóa', 'ES': 'Eliminar', 'TH': 'ลบ'},

  // ---------------- 나의 별 수집 현황 ----------------
  'colMonth': {'KO': '이번 달 모은 별', 'EN': 'Stars this month', 'JA': '今月集めた星', 'ZH': '本月获得的星星', 'FR': 'Étoiles ce mois-ci', 'DE': 'Sterne diesen Monat', 'RU': 'Звёзды за месяц', 'AR': 'نجوم هذا الشهر', 'HI': 'इस महीने के सितारे', 'VI': 'Sao tháng này', 'ES': 'Estrellas este mes', 'TH': 'ดาวเดือนนี้'},
  'colTime': {'KO': '운동 시간 별', 'EN': 'Time stars', 'JA': '運動時間の星', 'ZH': '时间星星', 'FR': 'Étoiles de durée', 'DE': 'Zeit-Sterne', 'RU': 'За время', 'AR': 'نجوم الوقت', 'HI': 'समय सितारे', 'VI': 'Sao thời gian', 'ES': 'Estrellas por tiempo', 'TH': 'ดาวจากเวลา'},
  'colBonus': {'KO': '보너스 별', 'EN': 'Bonus stars', 'JA': 'ボーナスの星', 'ZH': '奖励星星', 'FR': 'Étoiles bonus', 'DE': 'Bonussterne', 'RU': 'Бонусные', 'AR': 'نجوم إضافية', 'HI': 'बोनस सितारे', 'VI': 'Sao thưởng', 'ES': 'Estrellas extra', 'TH': 'ดาวโบนัส'},
  'colDetail': {'KO': '보너스 별 상세 내역', 'EN': 'Bonus details', 'JA': 'ボーナスの内訳', 'ZH': '奖励明细', 'FR': 'Détail des bonus', 'DE': 'Bonus-Details', 'RU': 'Детали бонусов', 'AR': 'تفاصيل المكافآت', 'HI': 'बोनस विवरण', 'VI': 'Chi tiết thưởng', 'ES': 'Detalle de bonos', 'TH': 'รายละเอียดโบนัส'},
  'colEmpty': {'KO': '운동을 끝내면 받은 보너스가 여기에 쌓입니다.', 'EN': 'Bonuses appear here after you finish a workout.', 'JA': '運動を終えると、もらったボーナスがここに表示されます。', 'ZH': '结束运动后，获得的奖励会显示在这里。', 'FR': "Les bonus s'affichent ici après une séance.", 'DE': 'Boni erscheinen hier nach dem Training.', 'RU': 'Бонусы появятся здесь после тренировки.', 'AR': 'تظهر المكافآت هنا بعد إنهاء التمرين.', 'HI': 'व्यायाम खत्म करने पर बोनस यहां दिखेंगे।', 'VI': 'Phần thưởng sẽ hiện ở đây sau khi tập xong.', 'ES': 'Los bonos aparecen aquí al terminar un entrenamiento.', 'TH': 'จบการออกกำลังกายแล้ว โบนัสจะแสดงที่นี่'},
  'colBonusRow': {'KO': '{name} (+{per} × {n}회)', 'EN': '{name} (+{per} × {n})', 'JA': '{name} (+{per} × {n}回)', 'ZH': '{name} (+{per} × {n}次)', 'FR': '{name} (+{per} × {n})', 'DE': '{name} (+{per} × {n})', 'RU': '{name} (+{per} × {n})', 'AR': '{name} (+{per} × {n})', 'HI': '{name} (+{per} × {n})', 'VI': '{name} (+{per} × {n} lần)', 'ES': '{name} (+{per} × {n})', 'TH': '{name} (+{per} × {n} ครั้ง)'},
  'colMonthMin': {'KO': '이번 달 운동', 'EN': 'Exercise this month', 'JA': '今月の運動', 'ZH': '本月运动', 'FR': 'Sport ce mois-ci', 'DE': 'Training diesen Monat', 'RU': 'Спорт за месяц', 'AR': 'تمارين هذا الشهر', 'HI': 'इस महीने व्यायाम', 'VI': 'Tập luyện tháng này', 'ES': 'Ejercicio este mes', 'TH': 'ออกกำลังกายเดือนนี้'},
  'colSent': {'KO': '자녀에게 보낸 별', 'EN': 'Stars sent to child', 'JA': '子どもに送った星', 'ZH': '送给孩子的星星', 'FR': "Étoiles envoyées à l'enfant", 'DE': 'An das Kind gesendet', 'RU': 'Отправлено ребёнку', 'AR': 'نجوم أُرسلت للطفل', 'HI': 'बच्चे को भेजे सितारे', 'VI': 'Sao đã gửi cho con', 'ES': 'Estrellas enviadas', 'TH': 'ดาวที่ส่งให้ลูก'},

  // ---------------- 보너스 이름 ----------------
  'bonus_record': {'KO': '운동 기록', 'EN': 'Workout logged', 'JA': '運動の記録', 'ZH': '运动记录', 'FR': 'Séance enregistrée', 'DE': 'Training eingetragen', 'RU': 'Тренировка записана', 'AR': 'تسجيل التمرين', 'HI': 'व्यायाम दर्ज', 'VI': 'Ghi buổi tập', 'ES': 'Entrenamiento registrado', 'TH': 'บันทึกการออกกำลังกาย'},
  'bonus_d60': {'KO': '하루 60분 이상', 'EN': '60+ min in a day', 'JA': '1日60分以上', 'ZH': '单日60分钟以上', 'FR': '60 min+ dans la journée', 'DE': '60+ Min. an einem Tag', 'RU': '60+ мин за день', 'AR': 'أكثر من 60 دقيقة في اليوم', 'HI': 'एक दिन में 60+ मिनट', 'VI': 'Trên 60 phút/ngày', 'ES': '60+ min en un día', 'TH': 'วันละ 60 นาทีขึ้นไป'},
  'bonus_streak': {'KO': '연속 운동', 'EN': 'Day streak', 'JA': '連続運動', 'ZH': '连续运动', 'FR': 'Jours consécutifs', 'DE': 'Tage in Folge', 'RU': 'Дни подряд', 'AR': 'أيام متتالية', 'HI': 'लगातार व्यायाम', 'VI': 'Tập liên tiếp', 'ES': 'Días seguidos', 'TH': 'ออกกำลังกายต่อเนื่อง'},
  'bonus_week': {'KO': '일주일 개근', 'EN': 'Perfect week', 'JA': '1週間皆勤', 'ZH': '一周全勤', 'FR': 'Semaine parfaite', 'DE': 'Perfekte Woche', 'RU': 'Неделя без пропусков', 'AR': 'أسبوع كامل', 'HI': 'पूरा सप्ताह', 'VI': 'Cả tuần đều đặn', 'ES': 'Semana perfecta', 'TH': 'ครบทั้งสัปดาห์'},
  'bonus_month': {'KO': '한 달 개근', 'EN': 'Perfect month', 'JA': '1か月皆勤', 'ZH': '一个月全勤', 'FR': 'Mois parfait', 'DE': 'Perfekter Monat', 'RU': 'Месяц без пропусков', 'AR': 'شهر كامل', 'HI': 'पूरा महीना', 'VI': 'Cả tháng đều đặn', 'ES': 'Mes perfecto', 'TH': 'ครบทั้งเดือน'},

  // ---------------- 자녀에게 보내기 카드 ----------------
  'sendLocked': {'KO': '자녀와 연결하면 모은 별을 응원으로 보낼 수 있어요', 'EN': 'Link your child to send your stars as encouragement', 'JA': 'お子様と連携すると、集めた星を応援として送れます', 'ZH': '与孩子连接后，就能把星星作为鼓励送出', 'FR': 'Liez votre enfant pour lui envoyer vos étoiles', 'DE': 'Verbinde dein Kind, um ihm deine Sterne zu schicken', 'RU': 'Свяжитесь с ребёнком, чтобы отправлять звёзды', 'AR': 'اربط طفلك لترسل له نجومك تشجيعًا', 'HI': 'बच्चे को जोड़ें और सितारे हौसले के रूप में भेजें', 'VI': 'Liên kết với con để gửi sao cổ vũ', 'ES': 'Vincula a tu hijo/a para enviarle tus estrellas', 'TH': 'เชื่อมกับลูกแล้วส่งดาวเป็นกำลังใจได้'},
  'sendLockedHint': {'KO': '일반 플래너 맨 위의 "학부모방 · 자녀연결"에서 자녀 코드를 입력하면 열립니다.', 'EN': 'Enter your child\'s code via "Parent Room" at the top of the planner.', 'JA': 'プランナー上部の「保護者ルーム」でお子様のコードを入力すると開きます。', 'ZH': '在计划器顶部的“家长室”输入孩子的代码即可开启。', 'FR': 'Saisissez le code de l\'enfant via « Espace parents » en haut du planificateur.', 'DE': 'Gib oben im Planer unter „Elternbereich“ den Code deines Kindes ein.', 'RU': 'Введите код ребёнка в разделе «Для родителей» вверху планировщика.', 'AR': 'أدخل رمز طفلك من "غرفة الوالدين" أعلى المخطط.', 'HI': 'प्लानर के ऊपर "अभिभावक कक्ष" में बच्चे का कोड डालें।', 'VI': 'Nhập mã của con tại "Phòng phụ huynh" ở đầu trình lập kế hoạch.', 'ES': 'Introduce el código de tu hijo/a en "Sala de padres", arriba del planificador.', 'TH': 'ใส่รหัสของลูกที่ "ห้องผู้ปกครอง" ด้านบนของแพลนเนอร์'},
  'sendLinked': {'KO': '연결된 자녀 {n}명', 'EN': 'Linked children: {n}', 'JA': '連携中の子ども {n}人', 'ZH': '已连接的孩子 {n}名', 'FR': 'Enfants liés : {n}', 'DE': 'Verbundene Kinder: {n}', 'RU': 'Связано детей: {n}', 'AR': 'الأطفال المرتبطون: {n}', 'HI': 'जुड़े बच्चे: {n}', 'VI': 'Con đã liên kết: {n}', 'ES': 'Hijos vinculados: {n}', 'TH': 'ลูกที่เชื่อมแล้ว {n} คน'},
  'btnSendStars': {'KO': '자녀에게 별 보내기', 'EN': 'Send stars to child', 'JA': '子どもに星を送る', 'ZH': '给孩子送星星', 'FR': "Envoyer des étoiles à l'enfant", 'DE': 'Sterne an das Kind senden', 'RU': 'Отправить звёзды ребёнку', 'AR': 'أرسل نجومًا إلى الطفل', 'HI': 'बच्चे को सितारे भेजें', 'VI': 'Gửi sao cho con', 'ES': 'Enviar estrellas', 'TH': 'ส่งดาวให้ลูก'},

  // ---------------- 보내기 창 ----------------
  'sendTitle': {'KO': '자녀에게 별 보내기', 'EN': 'SEND STARS', 'JA': '子どもに星を送る', 'ZH': '给孩子送星星', 'FR': 'Envoyer des étoiles', 'DE': 'Sterne senden', 'RU': 'Отправить звёзды', 'AR': 'إرسال النجوم', 'HI': 'सितारे भेजें', 'VI': 'Gửi sao', 'ES': 'Enviar estrellas', 'TH': 'ส่งดาว'},
  'noStars': {'KO': '아직 모아 둔 별이 없습니다. 운동으로 별을 먼저 모아 주세요.', 'EN': 'No saved stars yet. Earn some by exercising first.', 'JA': 'まだ貯めた星がありません。まず運動で星を集めましょう。', 'ZH': '还没有攒下星星。请先通过运动获得星星。', 'FR': "Pas encore d'étoiles. Faites d'abord du sport pour en gagner.", 'DE': 'Noch keine Sterne gespart. Sammle zuerst welche beim Training.', 'RU': 'Звёзд пока нет. Сначала заработайте их тренировкой.', 'AR': 'لا توجد نجوم بعد. اجمع بعضها بالتمرين أولًا.', 'HI': 'अभी कोई सितारे जमा नहीं हैं। पहले व्यायाम करके कमाएं।', 'VI': 'Chưa có sao. Hãy tập luyện để nhận sao trước.', 'ES': 'Aún no tienes estrellas. Gana algunas haciendo ejercicio.', 'TH': 'ยังไม่มีดาวสะสม ออกกำลังกายเพื่อสะสมดาวก่อนนะ'},
  'sumTotal': {'KO': '총 별', 'EN': 'Total', 'JA': '合計', 'ZH': '总计', 'FR': 'Total', 'DE': 'Gesamt', 'RU': 'Всего', 'AR': 'الإجمالي', 'HI': 'कुल', 'VI': 'Tổng', 'ES': 'Total', 'TH': 'ทั้งหมด'},
  'sumSent': {'KO': '보낸 별', 'EN': 'Sent', 'JA': '送った星', 'ZH': '已送出', 'FR': 'Envoyées', 'DE': 'Gesendet', 'RU': 'Отправлено', 'AR': 'المُرسلة', 'HI': 'भेजे', 'VI': 'Đã gửi', 'ES': 'Enviadas', 'TH': 'ส่งแล้ว'},
  'sumNow': {'KO': '현재 별', 'EN': 'Now', 'JA': '現在', 'ZH': '现有', 'FR': 'Actuelles', 'DE': 'Aktuell', 'RU': 'Сейчас', 'AR': 'الحالية', 'HI': 'अभी', 'VI': 'Hiện có', 'ES': 'Actuales', 'TH': 'คงเหลือ'},
  'sendBalance': {'KO': '모아 둔 별 {n}개', 'EN': 'Saved stars: {n}', 'JA': '貯めた星 {n}個', 'ZH': '攒下的星星 {n}颗', 'FR': 'Étoiles épargnées : {n}', 'DE': 'Gesparte Sterne: {n}', 'RU': 'Накоплено: {n}', 'AR': 'النجوم المدخرة: {n}', 'HI': 'जमा सितारे: {n}', 'VI': 'Sao đã tích lũy: {n}', 'ES': 'Estrellas ahorradas: {n}', 'TH': 'ดาวที่สะสมไว้ {n} ดวง'},
  'lblReceivers': {'KO': '받을 자녀 (여러 명 고를 수 있어요)', 'EN': 'Recipients (you can pick several)', 'JA': '受け取る子ども（複数選べます）', 'ZH': '接收的孩子（可多选）', 'FR': 'Destinataires (plusieurs possibles)', 'DE': 'Empfänger (mehrere möglich)', 'RU': 'Кому (можно несколько)', 'AR': 'المستلمون (يمكن اختيار أكثر من واحد)', 'HI': 'किसे भेजें (कई चुन सकते हैं)', 'VI': 'Người nhận (chọn được nhiều)', 'ES': 'Destinatarios (puedes elegir varios)', 'TH': 'ลูกที่จะรับ (เลือกได้หลายคน)'},
  'chipAll': {'KO': '모두', 'EN': 'All', 'JA': '全員', 'ZH': '全部', 'FR': 'Tous', 'DE': 'Alle', 'RU': 'Все', 'AR': 'الكل', 'HI': 'सभी', 'VI': 'Tất cả', 'ES': 'Todos', 'TH': 'ทั้งหมด'},
  'lblMode': {'KO': '보내는 방식', 'EN': 'Type', 'JA': '送り方', 'ZH': '发送方式', 'FR': "Type d'envoi", 'DE': 'Art', 'RU': 'Тип', 'AR': 'النوع', 'HI': 'प्रकार', 'VI': 'Cách gửi', 'ES': 'Tipo', 'TH': 'วิธีส่ง'},
  'modeNormal': {'KO': '일반 응원', 'EN': 'Encouragement', 'JA': '通常の応援', 'ZH': '普通鼓励', 'FR': 'Encouragement', 'DE': 'Anfeuerung', 'RU': 'Поддержка', 'AR': 'تشجيع', 'HI': 'सामान्य हौसला', 'VI': 'Cổ vũ thường', 'ES': 'Ánimo', 'TH': 'กำลังใจทั่วไป'},
  'modeSpecial': {'KO': '🎉 특별 축하', 'EN': '🎉 Special celebration', 'JA': '🎉 特別なお祝い', 'ZH': '🎉 特别庆祝', 'FR': '🎉 Célébration spéciale', 'DE': '🎉 Besondere Feier', 'RU': '🎉 Особый праздник', 'AR': '🎉 احتفال خاص', 'HI': '🎉 विशेष बधाई', 'VI': '🎉 Chúc mừng đặc biệt', 'ES': '🎉 Celebración especial', 'TH': '🎉 ฉลองพิเศษ'},
  'specialInfo': {'KO': '수상, 등수 같은 큰 성취를 축하할 때 쓰세요.\n자녀 화면에 🎉 특별 축하로 따로 기록됩니다.', 'EN': "Use this to celebrate big achievements like an award or a rank.\nIt's recorded separately as 🎉 Special on your child's screen.", 'JA': '受賞や順位など大きな成果を祝うときに使ってください。\nお子様の画面に🎉特別なお祝いとして別に記録されます。', 'ZH': '用于庆祝获奖、名次等重大成就。\n会在孩子画面中单独记录为🎉特别庆祝。', 'FR': "Pour célébrer une grande réussite (prix, classement).\nEnregistré à part comme 🎉 Spécial chez l'enfant.", 'DE': 'Für große Erfolge wie Auszeichnungen oder Platzierungen.\nWird beim Kind separat als 🎉 Besonders angezeigt.', 'RU': 'Для больших успехов: награда, место в рейтинге.\nУ ребёнка записывается отдельно как 🎉 Особое.', 'AR': 'استخدمه للاحتفال بإنجاز كبير مثل جائزة أو ترتيب.\nيُسجَّل منفصلًا كـ🎉 خاص على شاشة طفلك.', 'HI': 'पुरस्कार या रैंक जैसी बड़ी उपलब्धि पर इस्तेमाल करें।\nबच्चे की स्क्रीन पर 🎉 विशेष के रूप में अलग दर्ज होगा।', 'VI': 'Dùng khi mừng thành tích lớn như giải thưởng, thứ hạng.\nSẽ được ghi riêng là 🎉 Đặc biệt trên màn hình của con.', 'ES': 'Úsalo para celebrar logros grandes como un premio o un puesto.\nSe registra aparte como 🎉 Especial en la pantalla de tu hijo/a.', 'TH': 'ใช้ฉลองความสำเร็จใหญ่ เช่น รางวัล หรืออันดับ\nจะบันทึกแยกเป็น 🎉 พิเศษ ในหน้าจอของลูก'},
  'lblCount': {'KO': '한 명에게 보낼 별 개수', 'EN': 'Stars per child', 'JA': '1人に送る星の数', 'ZH': '每位孩子的星星数', 'FR': "Étoiles par enfant", 'DE': 'Sterne pro Kind', 'RU': 'Звёзд на ребёнка', 'AR': 'النجوم لكل طفل', 'HI': 'प्रति बच्चा सितारे', 'VI': 'Số sao mỗi con', 'ES': 'Estrellas por hijo/a', 'TH': 'จำนวนดาวต่อคน'},
  'countHintNone': {'KO': '받을 자녀를 먼저 골라 주세요.', 'EN': 'Pick at least one child first.', 'JA': 'まず受け取る子どもを選んでください。', 'ZH': '请先选择接收的孩子。', 'FR': "Choisissez d'abord au moins un enfant.", 'DE': 'Wähle zuerst mindestens ein Kind.', 'RU': 'Сначала выберите ребёнка.', 'AR': 'اختر طفلًا واحدًا على الأقل أولًا.', 'HI': 'पहले कम से कम एक बच्चा चुनें।', 'VI': 'Hãy chọn ít nhất một con trước.', 'ES': 'Elige primero al menos un hijo/a.', 'TH': 'เลือกลูกอย่างน้อยหนึ่งคนก่อน'},
  'countHint': {'KO': '한 명당 최대 {max}개 · {c}명 × {p}개 = 모두 {t}개가 통장에서 빠져요', 'EN': 'Up to {max} per child · {c} × {p} = {t} stars leave your bank', 'JA': '1人あたり最大{max}個 · {c}人 × {p}個 = 合計{t}個が貯金から減ります', 'ZH': '每人最多{max}颗 · {c}人 × {p}颗 = 共从存折扣除{t}颗', 'FR': "Max {max} par enfant · {c} × {p} = {t} étoiles débitées", 'DE': 'Max. {max} pro Kind · {c} × {p} = {t} Sterne werden abgebucht', 'RU': 'Макс. {max} на ребёнка · {c} × {p} = спишется {t}', 'AR': 'حتى {max} لكل طفل · {c} × {p} = سيُخصم {t} نجمة', 'HI': 'प्रति बच्चा अधिकतम {max} · {c} × {p} = कुल {t} सितारे घटेंगे', 'VI': 'Tối đa {max}/con · {c} × {p} = trừ {t} sao', 'ES': 'Máx. {max} por hijo/a · {c} × {p} = se descuentan {t}', 'TH': 'สูงสุดคนละ {max} ดวง · {c} คน × {p} = หัก {t} ดวง'},
  'lblMessage': {'KO': '응원 한마디 (눌러서 고르거나 직접 써도 돼요)', 'EN': 'Message (tap one or write your own)', 'JA': '応援メッセージ（選ぶか自由に書けます）', 'ZH': '鼓励的话（可点选或自己写）', 'FR': 'Message (choisissez-en un ou écrivez le vôtre)', 'DE': 'Nachricht (antippen oder selbst schreiben)', 'RU': 'Сообщение (выберите или напишите своё)', 'AR': 'رسالة (اختر واحدة أو اكتب رسالتك)', 'HI': 'संदेश (चुनें या खुद लिखें)', 'VI': 'Lời nhắn (chọn hoặc tự viết)', 'ES': 'Mensaje (elige uno o escribe el tuyo)', 'TH': 'ข้อความ (แตะเลือกหรือเขียนเอง)'},
  'lblEditMsg': {'KO': '선택한 문구를 눌러 고쳐 쓸 수 있어요', 'EN': 'Tap to edit the chosen message', 'JA': '選んだ文を押して書き直せます', 'ZH': '点击可修改所选文字', 'FR': 'Touchez pour modifier le message choisi', 'DE': 'Tippen, um die Nachricht zu bearbeiten', 'RU': 'Нажмите, чтобы изменить текст', 'AR': 'اضغط لتعديل الرسالة المختارة', 'HI': 'चुना संदेश बदलने के लिए टैप करें', 'VI': 'Chạm để sửa lời nhắn đã chọn', 'ES': 'Toca para editar el mensaje elegido', 'TH': 'แตะเพื่อแก้ไขข้อความที่เลือก'},
  'defaultMsg': {'KO': '너의 노력을 응원해!', 'EN': "We're cheering for your effort!", 'JA': 'あなたの努力を応援してるよ！', 'ZH': '为你的努力加油！', 'FR': 'On encourage tes efforts !', 'DE': 'Wir feuern deinen Einsatz an!', 'RU': 'Мы болеем за твои старания!', 'AR': 'نحن نشجع اجتهادك!', 'HI': 'हम तुम्हारी मेहनत का हौसला बढ़ाते हैं!', 'VI': 'Bố mẹ cổ vũ nỗ lực của con!', 'ES': '¡Animamos tu esfuerzo!', 'TH': 'เป็นกำลังใจให้ความพยายามของลูกนะ!'},
  'errPickChild': {'KO': '받을 자녀를 한 명 이상 골라 주세요.', 'EN': 'Please pick at least one child.', 'JA': '受け取る子どもを1人以上選んでください。', 'ZH': '请至少选择一位孩子。', 'FR': 'Choisissez au moins un enfant.', 'DE': 'Bitte wähle mindestens ein Kind.', 'RU': 'Выберите хотя бы одного ребёнка.', 'AR': 'يرجى اختيار طفل واحد على الأقل.', 'HI': 'कृपया कम से कम एक बच्चा चुनें।', 'VI': 'Vui lòng chọn ít nhất một con.', 'ES': 'Elige al menos un hijo/a.', 'TH': 'กรุณาเลือกลูกอย่างน้อยหนึ่งคน'},
  'errCount': {'KO': '한 명에게 보낼 별 개수를 입력해 주세요.', 'EN': 'Enter how many stars to send per child.', 'JA': '1人に送る星の数を入力してください。', 'ZH': '请输入每位孩子要送的星星数。', 'FR': "Indiquez le nombre d'étoiles par enfant.", 'DE': 'Gib die Sternanzahl pro Kind ein.', 'RU': 'Введите число звёзд на ребёнка.', 'AR': 'أدخل عدد النجوم لكل طفل.', 'HI': 'प्रति बच्चा सितारों की संख्या दर्ज करें।', 'VI': 'Nhập số sao gửi cho mỗi con.', 'ES': 'Indica cuántas estrellas por hijo/a.', 'TH': 'ใส่จำนวนดาวที่จะส่งต่อคน'},
  'errNotEnough': {'KO': '모아 둔 별({b}개)이 모자랍니다. 한 명당 최대 {max}개까지 보낼 수 있어요.', 'EN': 'Not enough saved stars ({b}). You can send up to {max} per child.', 'JA': '貯めた星（{b}個）が足りません。1人あたり最大{max}個まで送れます。', 'ZH': '攒下的星星（{b}颗）不够。每人最多可送{max}颗。', 'FR': "Pas assez d'étoiles ({b}). Maximum {max} par enfant.", 'DE': 'Nicht genug Sterne ({b}). Maximal {max} pro Kind.', 'RU': 'Недостаточно звёзд ({b}). Максимум {max} на ребёнка.', 'AR': 'النجوم المدخرة ({b}) غير كافية. الحد الأقصى {max} لكل طفل.', 'HI': 'जमा सितारे ({b}) कम हैं। प्रति बच्चा अधिकतम {max} भेज सकते हैं।', 'VI': 'Không đủ sao ({b}). Tối đa {max} sao cho mỗi con.', 'ES': 'No hay suficientes estrellas ({b}). Máximo {max} por hijo/a.', 'TH': 'ดาวสะสม ({b} ดวง) ไม่พอ ส่งได้สูงสุดคนละ {max} ดวง'},
  'errCap': {'KO': '일반 응원은 한 명당 {cap}개까지 보낼 수 있습니다.', 'EN': 'Encouragement is limited to {cap} stars per child.', 'JA': '通常の応援は1人あたり{cap}個までです。', 'ZH': '普通鼓励每人最多{cap}颗。', 'FR': 'Encouragement limité à {cap} étoiles par enfant.', 'DE': 'Anfeuerung ist auf {cap} Sterne pro Kind begrenzt.', 'RU': 'Поддержка — не более {cap} звёзд на ребёнка.', 'AR': 'التشجيع محدود بـ{cap} نجمة لكل طفل.', 'HI': 'सामान्य हौसले में प्रति बच्चा {cap} सितारे तक।', 'VI': 'Cổ vũ thường tối đa {cap} sao mỗi con.', 'ES': 'El ánimo se limita a {cap} estrellas por hijo/a.', 'TH': 'กำลังใจทั่วไปส่งได้คนละไม่เกิน {cap} ดวง'},
  'errPartial': {'KO': '{names}에게는 보냈고, {fail}', 'EN': 'Sent to {names}, but {fail}', 'JA': '{names}には送りましたが、{fail}', 'ZH': '已送给{names}，但{fail}', 'FR': 'Envoyé à {names}, mais {fail}', 'DE': 'An {names} gesendet, aber {fail}', 'RU': 'Отправлено: {names}, но {fail}', 'AR': 'أُرسل إلى {names}، لكن {fail}', 'HI': '{names} को भेजा गया, पर {fail}', 'VI': 'Đã gửi cho {names}, nhưng {fail}', 'ES': 'Enviado a {names}, pero {fail}', 'TH': 'ส่งให้ {names} แล้ว แต่ {fail}'},
  'popupSpecial': {'KO': '🎉 특별 축하 별 {n}개\n{msg}', 'EN': '🎉 {n} special celebration stars\n{msg}', 'JA': '🎉 特別なお祝いの星 {n}個\n{msg}', 'ZH': '🎉 特别庆祝星星 {n}颗\n{msg}', 'FR': '🎉 {n} étoiles de célébration\n{msg}', 'DE': '🎉 {n} Feiersterne\n{msg}', 'RU': '🎉 {n} праздничных звёзд\n{msg}', 'AR': '🎉 {n} نجمة احتفال خاص\n{msg}', 'HI': '🎉 {n} विशेष बधाई सितारे\n{msg}', 'VI': '🎉 {n} sao chúc mừng đặc biệt\n{msg}', 'ES': '🎉 {n} estrellas de celebración\n{msg}', 'TH': '🎉 ดาวฉลองพิเศษ {n} ดวง\n{msg}'},
  'popupNormal': {'KO': '⭐ 별 {n}개와 함께\n{msg}', 'EN': '⭐ With {n} stars\n{msg}', 'JA': '⭐ 星{n}個と一緒に\n{msg}', 'ZH': '⭐ 附上{n}颗星星\n{msg}', 'FR': '⭐ Avec {n} étoiles\n{msg}', 'DE': '⭐ Mit {n} Sternen\n{msg}', 'RU': '⭐ Вместе с {n} звёздами\n{msg}', 'AR': '⭐ مع {n} نجمة\n{msg}', 'HI': '⭐ {n} सितारों के साथ\n{msg}', 'VI': '⭐ Kèm {n} sao\n{msg}', 'ES': '⭐ Con {n} estrellas\n{msg}', 'TH': '⭐ พร้อมดาว {n} ดวง\n{msg}'},
  'sentOk': {'KO': '{names}에게 별 {n}개씩 보냈습니다.', 'EN': 'Sent {n} stars each to {names}.', 'JA': '{names}に星を{n}個ずつ送りました。', 'ZH': '已给{names}各送{n}颗星星。', 'FR': '{n} étoiles envoyées à chacun : {names}.', 'DE': 'Je {n} Sterne an {names} gesendet.', 'RU': 'Отправлено по {n} звёзд: {names}.', 'AR': 'أُرسلت {n} نجمة لكل من {names}.', 'HI': '{names} को {n}-{n} सितारे भेजे गए।', 'VI': 'Đã gửi mỗi con {n} sao: {names}.', 'ES': 'Se enviaron {n} estrellas a cada uno: {names}.', 'TH': 'ส่งดาวคนละ {n} ดวงให้ {names} แล้ว'},
  'btnSending': {'KO': '보내는 중...', 'EN': 'Sending...', 'JA': '送信中...', 'ZH': '发送中...', 'FR': 'Envoi...', 'DE': 'Wird gesendet...', 'RU': 'Отправка...', 'AR': 'جارٍ الإرسال...', 'HI': 'भेजा जा रहा है...', 'VI': 'Đang gửi...', 'ES': 'Enviando...', 'TH': 'กำลังส่ง...'},
  'btnSend': {'KO': '보내기', 'EN': 'Send', 'JA': '送る', 'ZH': '发送', 'FR': 'Envoyer', 'DE': 'Senden', 'RU': 'Отправить', 'AR': 'إرسال', 'HI': 'भेजें', 'VI': 'Gửi', 'ES': 'Enviar', 'TH': 'ส่ง'},

  // ---------------- 서비스 오류 ----------------
  'errLogin': {'KO': '로그인 상태를 확인해 주세요.', 'EN': 'Please check that you are signed in.', 'JA': 'ログイン状態を確認してください。', 'ZH': '请确认登录状态。', 'FR': 'Vérifiez que vous êtes connecté.', 'DE': 'Bitte prüfe, ob du angemeldet bist.', 'RU': 'Проверьте, что вы вошли в аккаунт.', 'AR': 'يرجى التأكد من تسجيل الدخول.', 'HI': 'कृपया जांचें कि आप लॉग इन हैं।', 'VI': 'Vui lòng kiểm tra trạng thái đăng nhập.', 'ES': 'Comprueba que has iniciado sesión.', 'TH': 'กรุณาตรวจสอบการเข้าสู่ระบบ'},
  'errNoLink': {'KO': '자녀 연결 정보를 찾을 수 없습니다.', 'EN': 'Could not find the link to this child.', 'JA': 'お子様の連携情報が見つかりません。', 'ZH': '找不到孩子的连接信息。', 'FR': "Lien avec l'enfant introuvable.", 'DE': 'Die Verbindung zum Kind wurde nicht gefunden.', 'RU': 'Связь с ребёнком не найдена.', 'AR': 'تعذر العثور على ربط الطفل.', 'HI': 'बच्चे का लिंक नहीं मिला।', 'VI': 'Không tìm thấy liên kết với con.', 'ES': 'No se encontró el vínculo con tu hijo/a.', 'TH': 'ไม่พบข้อมูลการเชื่อมกับลูก'},
  'errNetwork': {'KO': '보내지 못했습니다. 인터넷 연결을 확인하고 다시 시도해 주세요.', 'EN': 'Could not send. Check your internet connection and try again.', 'JA': '送信できませんでした。インターネット接続を確認してもう一度お試しください。', 'ZH': '发送失败。请检查网络后重试。', 'FR': "Échec de l'envoi. Vérifiez votre connexion et réessayez.", 'DE': 'Senden fehlgeschlagen. Prüfe die Internetverbindung und versuche es erneut.', 'RU': 'Не удалось отправить. Проверьте интернет и повторите.', 'AR': 'تعذر الإرسال. تحقق من الاتصال بالإنترنت وحاول مجددًا.', 'HI': 'भेजा नहीं जा सका। इंटरनेट जांचकर फिर कोशिश करें।', 'VI': 'Gửi không thành công. Kiểm tra kết nối mạng và thử lại.', 'ES': 'No se pudo enviar. Revisa tu conexión e inténtalo de nuevo.', 'TH': 'ส่งไม่สำเร็จ ตรวจสอบอินเทอร์เน็ตแล้วลองใหม่'},
  'errBalanceLow': {'KO': '모아 둔 별({b}개)보다 많이 보낼 수 없습니다.', 'EN': 'You cannot send more than your saved stars ({b}).', 'JA': '貯めた星（{b}個）より多くは送れません。', 'ZH': '不能超过攒下的星星（{b}颗）。', 'FR': "Impossible d'envoyer plus que vos étoiles ({b}).", 'DE': 'Du kannst nicht mehr als deine gesparten Sterne ({b}) senden.', 'RU': 'Нельзя отправить больше накопленного ({b}).', 'AR': 'لا يمكنك إرسال أكثر من نجومك المدخرة ({b}).', 'HI': 'जमा सितारों ({b}) से ज़्यादा नहीं भेज सकते।', 'VI': 'Không thể gửi nhiều hơn số sao đã tích lũy ({b}).', 'ES': 'No puedes enviar más que tus estrellas ahorradas ({b}).', 'TH': 'ส่งเกินดาวที่สะสมไว้ ({b} ดวง) ไม่ได้'},

  // ---------------- 별 모으는 방법 ----------------
  'rule5min': {'KO': '운동 5분', 'EN': '5 min of exercise', 'JA': '運動5分', 'ZH': '运动5分钟', 'FR': '5 min de sport', 'DE': '5 Min. Training', 'RU': '5 мин тренировки', 'AR': '5 دقائق تمرين', 'HI': '5 मिनट व्यायाम', 'VI': '5 phút tập', 'ES': '5 min de ejercicio', 'TH': 'ออกกำลังกาย 5 นาที'},
  'rule1Star': {'KO': '별 1개', 'EN': '1 star', 'JA': '星1個', 'ZH': '1颗星星', 'FR': '1 étoile', 'DE': '1 Stern', 'RU': '1 звезда', 'AR': 'نجمة واحدة', 'HI': '1 सितारा', 'VI': '1 sao', 'ES': '1 estrella', 'TH': 'ดาว 1 ดวง'},
  'ruleRecord': {'KO': '운동 기록 (5분 이상, 하루 3번까지)', 'EN': 'Workout logged (5+ min, up to 3 a day)', 'JA': '運動の記録（5分以上、1日3回まで）', 'ZH': '运动记录（5分钟以上，每天最多3次）', 'FR': 'Séance enregistrée (5 min+, 3 par jour max)', 'DE': 'Training eingetragen (ab 5 Min., max. 3 pro Tag)', 'RU': 'Тренировка (от 5 мин, до 3 в день)', 'AR': 'تسجيل تمرين (5 دقائق+، حتى 3 يوميًا)', 'HI': 'व्यायाम दर्ज (5+ मिनट, दिन में 3 बार तक)', 'VI': 'Ghi buổi tập (từ 5 phút, tối đa 3 lần/ngày)', 'ES': 'Entrenamiento registrado (5 min+, hasta 3 al día)', 'TH': 'บันทึกการออกกำลังกาย (5 นาทีขึ้นไป วันละไม่เกิน 3 ครั้ง)'},
  'rule60': {'KO': '하루 합계 60분 이상', 'EN': '60+ min total in a day', 'JA': '1日合計60分以上', 'ZH': '单日累计60分钟以上', 'FR': '60 min+ au total dans la journée', 'DE': '60+ Min. insgesamt an einem Tag', 'RU': '60+ мин за день', 'AR': 'أكثر من 60 دقيقة في اليوم', 'HI': 'एक दिन में कुल 60+ मिनट', 'VI': 'Tổng trên 60 phút trong ngày', 'ES': '60+ min en total en un día', 'TH': 'รวมวันละ 60 นาทีขึ้นไป'},
  'ruleStreak': {'KO': '어제에 이어 오늘도 운동', 'EN': 'Exercised yesterday and today', 'JA': '昨日に続いて今日も運動', 'ZH': '昨天和今天都运动', 'FR': 'Sport hier et aujourd\'hui', 'DE': 'Gestern und heute trainiert', 'RU': 'Тренировка вчера и сегодня', 'AR': 'تمرين أمس واليوم', 'HI': 'कल और आज दोनों व्यायाम', 'VI': 'Tập cả hôm qua và hôm nay', 'ES': 'Ejercicio ayer y hoy', 'TH': 'ออกกำลังกายทั้งเมื่อวานและวันนี้'},
  'ruleWeek': {'KO': '일주일(일~토) 하루도 안 빠짐', 'EN': 'Every day of the week (Sun–Sat)', 'JA': '1週間（日〜土）毎日', 'ZH': '一周（周日至周六）每天', 'FR': 'Tous les jours de la semaine (dim.–sam.)', 'DE': 'Jeden Tag der Woche (So–Sa)', 'RU': 'Каждый день недели (вс–сб)', 'AR': 'كل يوم في الأسبوع (الأحد–السبت)', 'HI': 'पूरे सप्ताह हर दिन (रवि–शनि)', 'VI': 'Mỗi ngày trong tuần (CN–T7)', 'ES': 'Todos los días de la semana (dom–sáb)', 'TH': 'ทุกวันตลอดสัปดาห์ (อา.–ส.)'},
  'ruleMonth': {'KO': '한 달 하루도 안 빠짐', 'EN': 'Every day of the month', 'JA': '1か月毎日', 'ZH': '一个月每天', 'FR': 'Tous les jours du mois', 'DE': 'Jeden Tag im Monat', 'RU': 'Каждый день месяца', 'AR': 'كل يوم في الشهر', 'HI': 'पूरे महीने हर दिन', 'VI': 'Mỗi ngày trong tháng', 'ES': 'Todos los días del mes', 'TH': 'ทุกวันตลอดเดือน'},
  'ruleNote': {'KO': '운동 중 다른 앱으로 나가면 자녀 타이머처럼 자동으로 멈춥니다.', 'EN': "Switching to another app pauses the timer, just like your child's.", 'JA': '運動中に他のアプリへ移ると、お子様のタイマーと同じく自動で止まります。', 'ZH': '运动中切换到其他应用会自动暂停，和孩子的计时器一样。', 'FR': "Passer à une autre app met le minuteur en pause, comme pour votre enfant.", 'DE': 'Ein App-Wechsel pausiert den Timer – genau wie beim Kind.', 'RU': 'Переход в другое приложение ставит таймер на паузу, как у ребёнка.', 'AR': 'الانتقال إلى تطبيق آخر يوقف المؤقت، تمامًا مثل مؤقت طفلك.', 'HI': 'दूसरे ऐप पर जाने से टाइमर रुक जाता है, बच्चे के टाइमर की तरह।', 'VI': 'Chuyển sang ứng dụng khác sẽ dừng hẹn giờ, giống như của con.', 'ES': 'Cambiar de app pausa el temporizador, igual que el de tu hijo/a.', 'TH': 'ออกไปแอปอื่นตัวจับเวลาจะหยุด เหมือนของลูก'},

  // ---------------- 🆕 [가족 활동 체크 2026-09-30] ----------------
  'fcTitle': {'KO': '오늘의 가족 응원 체크', 'EN': 'FAMILY CHECK', 'JA': '今日の家族応援チェック', 'ZH': '今日家庭加油打卡', 'FR': 'Bilan familial du jour', 'DE': 'Familien-Check', 'RU': 'Семейная отметка дня', 'AR': 'تسجيل العائلة اليومي', 'HI': 'आज का पारिवारिक चेक', 'VI': 'Điểm danh gia đình hôm nay', 'ES': 'Registro familiar de hoy', 'TH': 'เช็กกิจกรรมครอบครัววันนี้'},
  'fcIntro': {'KO': '운동할 시간이 없는 날엔, 자녀를 위한 작은 노력을 체크하세요', 'EN': 'No time to exercise? Check the small things you did for your child.', 'JA': '運動する時間がない日は、子どものための小さな努力をチェックしましょう', 'ZH': '没时间运动的日子，就记录为孩子做的小小努力吧', 'FR': 'Pas le temps de faire du sport ? Cochez les petits gestes pour votre enfant.', 'DE': 'Keine Zeit für Sport? Hake die kleinen Dinge für dein Kind ab.', 'RU': 'Нет времени на спорт? Отметьте маленькие дела ради ребёнка.', 'AR': 'لا وقت للتمرين؟ سجّل الجهود الصغيرة التي بذلتها لطفلك.', 'HI': 'व्यायाम का समय नहीं? बच्चे के लिए किए छोटे प्रयास चेक करें।', 'VI': 'Không có thời gian tập? Hãy đánh dấu những nỗ lực nhỏ vì con.', 'ES': '¿Sin tiempo para ejercicio? Marca los pequeños esfuerzos por tu hijo/a.', 'TH': 'ไม่มีเวลาออกกำลังกาย? เช็กสิ่งเล็ก ๆ ที่ทำเพื่อลูก'},
  'fcToday': {'KO': '오늘', 'EN': 'Today', 'JA': '今日', 'ZH': '今天', 'FR': 'Aujourd\'hui', 'DE': 'Heute', 'RU': 'Сегодня', 'AR': 'اليوم', 'HI': 'आज', 'VI': 'Hôm nay', 'ES': 'Hoy', 'TH': 'วันนี้'},
  'fcYesterday': {'KO': '어제', 'EN': 'Yesterday', 'JA': '昨日', 'ZH': '昨天', 'FR': 'Hier', 'DE': 'Gestern', 'RU': 'Вчера', 'AR': 'أمس', 'HI': 'कल', 'VI': 'Hôm qua', 'ES': 'Ayer', 'TH': 'เมื่อวาน'},
  'fcYesterdayNote': {'KO': '어제 체크는 더하기만 할 수 있어요', 'EN': 'For yesterday you can only add checks.', 'JA': '昨日の分は追加のみできます', 'ZH': '昨天的只能增加', 'FR': 'Pour hier, vous pouvez seulement ajouter.', 'DE': 'Für gestern kannst du nur hinzufügen.', 'RU': 'За вчера можно только добавлять.', 'AR': 'يمكنك فقط الإضافة ليوم أمس.', 'HI': 'कल के लिए केवल जोड़ सकते हैं।', 'VI': 'Với hôm qua chỉ có thể thêm.', 'ES': 'Para ayer solo puedes añadir.', 'TH': 'ของเมื่อวานเพิ่มได้อย่างเดียว'},
  'grp_body': {'KO': '몸 활동', 'EN': 'Body', 'JA': '体の活動', 'ZH': '身体活动', 'FR': 'Corps', 'DE': 'Bewegung', 'RU': 'Тело', 'AR': 'الجسم', 'HI': 'शरीर', 'VI': 'Vận động', 'ES': 'Cuerpo', 'TH': 'ร่างกาย'},
  'grp_heart': {'KO': '자녀와 마음', 'EN': 'With my child', 'JA': '子どもと心', 'ZH': '与孩子', 'FR': 'Avec mon enfant', 'DE': 'Mit meinem Kind', 'RU': 'С ребёнком', 'AR': 'مع طفلي', 'HI': 'बच्चे के साथ', 'VI': 'Cùng con', 'ES': 'Con mi hijo/a', 'TH': 'กับลูก'},
  'grp_family': {'KO': '가족 활동', 'EN': 'Family', 'JA': '家族の活動', 'ZH': '家庭活动', 'FR': 'Famille', 'DE': 'Familie', 'RU': 'Семья', 'AR': 'العائلة', 'HI': 'परिवार', 'VI': 'Gia đình', 'ES': 'Familia', 'TH': 'ครอบครัว'},
  'grp_self': {'KO': '자기 관리', 'EN': 'Self-care', 'JA': '自己管理', 'ZH': '自我管理', 'FR': 'Soin de soi', 'DE': 'Selbstfürsorge', 'RU': 'Забота о себе', 'AR': 'العناية بالنفس', 'HI': 'स्व-देखभाल', 'VI': 'Chăm sóc bản thân', 'ES': 'Autocuidado', 'TH': 'ดูแลตัวเอง'},
  'it_walk': {'KO': '걷기', 'EN': 'Walking', 'JA': 'ウォーキング', 'ZH': '步行', 'FR': 'Marche', 'DE': 'Gehen', 'RU': 'Ходьба', 'AR': 'المشي', 'HI': 'पैदल चलना', 'VI': 'Đi bộ', 'ES': 'Caminar', 'TH': 'เดิน'},
  'it_stretch': {'KO': '스트레칭', 'EN': 'Stretching', 'JA': 'ストレッチ', 'ZH': '拉伸', 'FR': 'Étirements', 'DE': 'Dehnen', 'RU': 'Растяжка', 'AR': 'التمدد', 'HI': 'स्ट्रेचिंग', 'VI': 'Giãn cơ', 'ES': 'Estiramientos', 'TH': 'ยืดเหยียด'},
  'it_stairs': {'KO': '계단 오르기', 'EN': 'Taking the stairs', 'JA': '階段を上る', 'ZH': '爬楼梯', 'FR': 'Monter les escaliers', 'DE': 'Treppensteigen', 'RU': 'Подъём по лестнице', 'AR': 'صعود الدرج', 'HI': 'सीढ़ियां चढ़ना', 'VI': 'Leo cầu thang', 'ES': 'Subir escaleras', 'TH': 'ขึ้นบันได'},
  'it_steps': {'KO': '걸음 수', 'EN': 'Steps', 'JA': '歩数', 'ZH': '步数', 'FR': 'Pas', 'DE': 'Schritte', 'RU': 'Шаги', 'AR': 'الخطوات', 'HI': 'कदम', 'VI': 'Số bước', 'ES': 'Pasos', 'TH': 'จำนวนก้าว'},
  'it_cheerMsg': {'KO': '자녀에게 응원 문자', 'EN': 'Cheer message to my child', 'JA': '子どもへの応援メッセージ', 'ZH': '给孩子的加油消息', 'FR': 'Message d\'encouragement', 'DE': 'Aufmunternde Nachricht', 'RU': 'Сообщение поддержки ребёнку', 'AR': 'رسالة تشجيع لطفلي', 'HI': 'बच्चे को हौसला संदेश', 'VI': 'Tin nhắn cổ vũ con', 'ES': 'Mensaje de ánimo', 'TH': 'ข้อความให้กำลังใจลูก'},
  'it_talk': {'KO': '자녀와 10분 이상 대화', 'EN': 'Talked with my child 10+ min', 'JA': '子どもと10分以上会話', 'ZH': '与孩子聊天10分钟以上', 'FR': 'Discuté 10 min+ avec mon enfant', 'DE': '10+ Min. mit dem Kind gesprochen', 'RU': 'Разговор с ребёнком 10+ мин', 'AR': 'تحدثت مع طفلي 10 دقائق+', 'HI': 'बच्चे से 10+ मिनट बात', 'VI': 'Trò chuyện với con 10+ phút', 'ES': 'Hablé con mi hijo/a 10+ min', 'TH': 'คุยกับลูก 10 นาทีขึ้นไป'},
  'it_homework': {'KO': '공부·숙제 함께 봐 주기', 'EN': 'Helped with study/homework', 'JA': '勉強・宿題を一緒に見る', 'ZH': '陪孩子看功课', 'FR': 'Aide aux devoirs', 'DE': 'Bei Hausaufgaben geholfen', 'RU': 'Помог(ла) с уроками', 'AR': 'ساعدت في الدراسة/الواجب', 'HI': 'पढ़ाई/होमवर्क में मदद', 'VI': 'Kèm con học bài', 'ES': 'Ayudé con los deberes', 'TH': 'ช่วยดูการบ้าน'},
  'it_praise': {'KO': '칭찬 한마디 하기', 'EN': 'Gave a word of praise', 'JA': 'ほめ言葉をかける', 'ZH': '说一句称赞', 'FR': 'Un mot de félicitation', 'DE': 'Ein Lob ausgesprochen', 'RU': 'Похвалил(а)', 'AR': 'قلت كلمة مدح', 'HI': 'तारीफ का एक शब्द', 'VI': 'Khen con một câu', 'ES': 'Dije un elogio', 'TH': 'ชมลูกหนึ่งคำ'},
  'it_meal': {'KO': '자녀와 함께 식사', 'EN': 'Ate a meal together', 'JA': '子どもと一緒に食事', 'ZH': '和孩子一起吃饭', 'FR': 'Repas ensemble', 'DE': 'Gemeinsam gegessen', 'RU': 'Поели вместе', 'AR': 'تناولنا وجبة معًا', 'HI': 'साथ में भोजन', 'VI': 'Ăn cùng con', 'ES': 'Comimos juntos', 'TH': 'กินข้าวกับลูก'},
  'it_familyWalk': {'KO': '가족 산책·함께 운동', 'EN': 'Family walk or workout', 'JA': '家族で散歩・運動', 'ZH': '家庭散步/一起运动', 'FR': 'Balade ou sport en famille', 'DE': 'Familienspaziergang/-sport', 'RU': 'Семейная прогулка или спорт', 'AR': 'نزهة أو تمرين عائلي', 'HI': 'पारिवारिक सैर/व्यायाम', 'VI': 'Gia đình đi dạo/tập cùng', 'ES': 'Paseo o ejercicio en familia', 'TH': 'เดินเล่น/ออกกำลังกายกับครอบครัว'},
  'it_readTogether': {'KO': '자녀와 함께 책 읽기', 'EN': 'Read together with my child', 'JA': '子どもと一緒に読書', 'ZH': '和孩子一起读书', 'FR': 'Lecture avec mon enfant', 'DE': 'Mit dem Kind gelesen', 'RU': 'Читали вместе', 'AR': 'قرأنا معًا', 'HI': 'बच्चे के साथ पढ़ना', 'VI': 'Đọc sách cùng con', 'ES': 'Leímos juntos', 'TH': 'อ่านหนังสือกับลูก'},
  'it_outing': {'KO': '주말 가족 나들이', 'EN': 'Weekend family outing', 'JA': '週末の家族のお出かけ', 'ZH': '周末家庭出游', 'FR': 'Sortie familiale du week-end', 'DE': 'Wochenendausflug', 'RU': 'Семейная прогулка в выходные', 'AR': 'نزهة عائلية في العطلة', 'HI': 'सप्ताहांत पारिवारिक सैर', 'VI': 'Đi chơi cuối tuần cùng gia đình', 'ES': 'Salida familiar de fin de semana', 'TH': 'เที่ยวกับครอบครัววันหยุด'},
  'it_reading': {'KO': '책 읽기', 'EN': 'Reading', 'JA': '読書', 'ZH': '读书', 'FR': 'Lecture', 'DE': 'Lesen', 'RU': 'Чтение', 'AR': 'القراءة', 'HI': 'पढ़ना', 'VI': 'Đọc sách', 'ES': 'Lectura', 'TH': 'อ่านหนังสือ'},
  'it_earlySleep': {'KO': '일찍 자기 (11시 전)', 'EN': 'Slept early (before 11 pm)', 'JA': '早寝（23時前）', 'ZH': '早睡（23点前）', 'FR': 'Couché tôt (avant 23 h)', 'DE': 'Früh geschlafen (vor 23 Uhr)', 'RU': 'Рано лёг (до 23:00)', 'AR': 'نمت مبكرًا (قبل 11 مساءً)', 'HI': 'जल्दी सोए (रात 11 से पहले)', 'VI': 'Ngủ sớm (trước 23h)', 'ES': 'Dormí temprano (antes de las 23 h)', 'TH': 'นอนเร็ว (ก่อน 5 ทุ่ม)'},
  'fcUnit_min': {'KO': '{n}분', 'EN': '{n} min', 'JA': '{n}分', 'ZH': '{n}分钟', 'FR': '{n} min', 'DE': '{n} Min.', 'RU': '{n} мин', 'AR': '{n} دقيقة', 'HI': '{n} मिनट', 'VI': '{n} phút', 'ES': '{n} min', 'TH': '{n} นาที'},
  'fcUnit_stairs': {'KO': '{n}계단', 'EN': '{n} stairs', 'JA': '{n}段', 'ZH': '{n}级台阶', 'FR': '{n} marches', 'DE': '{n} Stufen', 'RU': '{n} ступенек', 'AR': '{n} درجة', 'HI': '{n} सीढ़ियां', 'VI': '{n} bậc', 'ES': '{n} escalones', 'TH': '{n} ขั้น'},
  'fcUnit_steps': {'KO': '{n}보', 'EN': '{n} steps', 'JA': '{n}歩', 'ZH': '{n}步', 'FR': '{n} pas', 'DE': '{n} Schritte', 'RU': '{n} шагов', 'AR': '{n} خطوة', 'HI': '{n} कदम', 'VI': '{n} bước', 'ES': '{n} pasos', 'TH': '{n} ก้าว'},
  'fcUnit_times': {'KO': '{n}회', 'EN': '{n}×', 'JA': '{n}回', 'ZH': '{n}次', 'FR': '{n} fois', 'DE': '{n}×', 'RU': '{n} раз', 'AR': '{n} مرة', 'HI': '{n} बार', 'VI': '{n} lần', 'ES': '{n} vez/veces', 'TH': '{n} ครั้ง'},
  'fcPerUnit': {'KO': '{u}마다 별 {s}', 'EN': '{s} ★ per {u}', 'JA': '{u}ごとに星{s}', 'ZH': '每{u}得{s}颗星', 'FR': '{s} ★ par {u}', 'DE': '{s} ★ pro {u}', 'RU': '{s} ★ за {u}', 'AR': '{s} ★ لكل {u}', 'HI': 'हर {u} पर {s} ★', 'VI': '{s} ★ mỗi {u}', 'ES': '{s} ★ por {u}', 'TH': 'ทุก {u} ได้ {s} ★'},
  'fcAuto': {'KO': '자동 인정 · 오늘 {n}/{m}회', 'EN': 'Counted automatically · {n}/{m} today', 'JA': '自動で加算 · 今日{n}/{m}回', 'ZH': '自动计入 · 今天{n}/{m}次', 'FR': 'Compté automatiquement · {n}/{m}', 'DE': 'Automatisch gezählt · {n}/{m}', 'RU': 'Засчитывается само · {n}/{m}', 'AR': 'يُحتسب تلقائيًا · {n}/{m}', 'HI': 'अपने आप गिना जाता है · {n}/{m}', 'VI': 'Tự động tính · {n}/{m} hôm nay', 'ES': 'Se cuenta solo · {n}/{m}', 'TH': 'นับอัตโนมัติ · วันนี้ {n}/{m}'},
  'fcTotal': {'KO': '오늘 체크 별 {n} / {cap}', 'EN': 'Check stars {n} / {cap}', 'JA': 'チェックの星 {n} / {cap}', 'ZH': '打卡星星 {n} / {cap}', 'FR': 'Étoiles du bilan {n} / {cap}', 'DE': 'Check-Sterne {n} / {cap}', 'RU': 'Звёзды отметок {n} / {cap}', 'AR': 'نجوم التسجيل {n} / {cap}', 'HI': 'चेक सितारे {n} / {cap}', 'VI': 'Sao điểm danh {n} / {cap}', 'ES': 'Estrellas del registro {n} / {cap}', 'TH': 'ดาวจากการเช็ก {n} / {cap}'},
  'fcLimit': {'KO': '하루 최대 {cap}개까지예요', 'EN': 'Daily limit is {cap} stars', 'JA': '1日最大{cap}個までです', 'ZH': '每天最多{cap}颗', 'FR': 'Limite de {cap} étoiles par jour', 'DE': 'Maximal {cap} Sterne pro Tag', 'RU': 'Не более {cap} звёзд в день', 'AR': 'الحد اليومي {cap} نجمة', 'HI': 'रोज़ अधिकतम {cap} सितारे', 'VI': 'Tối đa {cap} sao mỗi ngày', 'ES': 'Máximo {cap} estrellas al día', 'TH': 'สูงสุดวันละ {cap} ดวง'},
  'fcSaved': {'KO': '별 +{n}개가 통장에 쌓였어요', 'EN': '+{n} stars added to your bank', 'JA': '星+{n}個が貯金されました', 'ZH': '存入星星 +{n}颗', 'FR': '+{n} étoiles ajoutées', 'DE': '+{n} Sterne gutgeschrieben', 'RU': '+{n} звёзд в банке', 'AR': 'أُضيفت +{n} نجمة', 'HI': '+{n} सितारे जमा हुए', 'VI': 'Đã cộng +{n} sao', 'ES': '+{n} estrellas añadidas', 'TH': 'เพิ่มดาว +{n} ดวงแล้ว'},
  'fcRemoved': {'KO': '체크를 줄여 별 {n}개가 빠졌어요', 'EN': '{n} stars removed', 'JA': 'チェックを減らし星{n}個が引かれました', 'ZH': '减少打卡，扣除{n}颗星', 'FR': '{n} étoiles retirées', 'DE': '{n} Sterne abgezogen', 'RU': 'Снято {n} звёзд', 'AR': 'أُزيلت {n} نجمة', 'HI': '{n} सितारे घटाए गए', 'VI': 'Đã trừ {n} sao', 'ES': 'Se quitaron {n} estrellas', 'TH': 'หักดาว {n} ดวงแล้ว'},
  'fcNoChange': {'KO': '바뀐 것이 없어요', 'EN': 'Nothing changed', 'JA': '変更はありません', 'ZH': '没有变化', 'FR': 'Aucun changement', 'DE': 'Keine Änderung', 'RU': 'Изменений нет', 'AR': 'لا يوجد تغيير', 'HI': 'कोई बदलाव नहीं', 'VI': 'Không có thay đổi', 'ES': 'Sin cambios', 'TH': 'ไม่มีการเปลี่ยนแปลง'},
  'fcClearTitle': {'KO': '오늘 체크를 모두 취소할까요?', 'EN': 'Clear all of today\'s checks?', 'JA': '今日のチェックをすべて取り消しますか？', 'ZH': '取消今天的全部打卡吗？', 'FR': 'Effacer tous les pointages d\'aujourd\'hui ?', 'DE': 'Alle heutigen Checks löschen?', 'RU': 'Отменить все отметки за сегодня?', 'AR': 'مسح كل تسجيلات اليوم؟', 'HI': 'आज के सभी चेक हटाएं?', 'VI': 'Hủy tất cả điểm danh hôm nay?', 'ES': '¿Borrar todos los registros de hoy?', 'TH': 'ยกเลิกการเช็กวันนี้ทั้งหมด?'},
  'fcClearMsg': {'KO': '오늘 체크한 별이 통장에서 빠집니다.\n자동 인정된 응원 문자는 그대로예요.', 'EN': 'Today\'s check stars will be removed from your bank.\nAuto-counted cheer messages stay.', 'JA': '今日のチェックの星が引かれます。\n自動加算の応援メッセージはそのままです。', 'ZH': '今天打卡的星星将被扣除。\n自动计入的加油消息保留。', 'FR': 'Les étoiles d\'aujourd\'hui seront retirées.\nLes messages comptés automatiquement restent.', 'DE': 'Die heutigen Check-Sterne werden abgezogen.\nAutomatisch gezählte Nachrichten bleiben.', 'RU': 'Сегодняшние звёзды будут сняты.\nАвтоматические сообщения останутся.', 'AR': 'ستُزال نجوم تسجيل اليوم.\nتبقى رسائل التشجيع المحتسبة تلقائيًا.', 'HI': 'आज के चेक सितारे घटा दिए जाएंगे।\nअपने आप गिने संदेश बने रहेंगे।', 'VI': 'Sao điểm danh hôm nay sẽ bị trừ.\nTin nhắn cổ vũ tự động vẫn giữ.', 'ES': 'Se quitarán las estrellas de hoy.\nLos mensajes contados solos se mantienen.', 'TH': 'ดาวจากการเช็กวันนี้จะถูกหัก\nข้อความให้กำลังใจที่นับอัตโนมัติยังอยู่'},
  'fcErrDay': {'KO': '오늘과 어제만 체크할 수 있어요', 'EN': 'You can only check today and yesterday.', 'JA': '今日と昨日だけチェックできます', 'ZH': '只能打卡今天和昨天', 'FR': 'Seuls aujourd\'hui et hier sont possibles.', 'DE': 'Nur heute und gestern möglich.', 'RU': 'Можно отмечать только сегодня и вчера.', 'AR': 'يمكن التسجيل لليوم وأمس فقط.', 'HI': 'केवल आज और कल चेक कर सकते हैं।', 'VI': 'Chỉ điểm danh được hôm nay và hôm qua.', 'ES': 'Solo hoy y ayer.', 'TH': 'เช็กได้เฉพาะวันนี้และเมื่อวาน'},
  'fcErrLimit': {'KO': '하루 최대 20개를 넘을 수 없어요', 'EN': 'You cannot exceed 20 stars a day.', 'JA': '1日20個を超えられません', 'ZH': '每天不能超过20颗', 'FR': 'Pas plus de 20 étoiles par jour.', 'DE': 'Nicht mehr als 20 Sterne pro Tag.', 'RU': 'Не больше 20 звёзд в день.', 'AR': 'لا يمكن تجاوز 20 نجمة يوميًا.', 'HI': 'रोज़ 20 से ज़्यादा नहीं।', 'VI': 'Không vượt quá 20 sao mỗi ngày.', 'ES': 'No más de 20 estrellas al día.', 'TH': 'เกินวันละ 20 ดวงไม่ได้'},
  'fcErrSpent': {'KO': '이미 자녀에게 보낸 별이라 줄일 수 없어요', 'EN': 'These stars were already sent, so they can\'t be removed.', 'JA': 'すでに子どもに送った星なので減らせません', 'ZH': '星星已送给孩子，无法减少', 'FR': 'Étoiles déjà envoyées, impossible de retirer.', 'DE': 'Bereits gesendet, kann nicht abgezogen werden.', 'RU': 'Звёзды уже отправлены, снять нельзя.', 'AR': 'أُرسلت النجوم بالفعل، لا يمكن إزالتها.', 'HI': 'सितारे भेजे जा चुके हैं, घटा नहीं सकते।', 'VI': 'Sao đã gửi cho con, không thể trừ.', 'ES': 'Ya enviadas, no se pueden quitar.', 'TH': 'ส่งดาวให้ลูกแล้ว หักคืนไม่ได้'},
  'btnTimerMode': {'KO': '운동 타이머로 모으기', 'EN': 'Earn with timer', 'JA': 'タイマーで集める', 'ZH': '用计时器攒星', 'FR': 'Gagner avec le minuteur', 'DE': 'Mit Timer sammeln', 'RU': 'Копить таймером', 'AR': 'اجمع بالمؤقت', 'HI': 'टाइमर से कमाएं', 'VI': 'Nhận sao bằng hẹn giờ', 'ES': 'Ganar con temporizador', 'TH': 'สะสมด้วยตัวจับเวลา'},
  'btnCheckMode': {'KO': '가족 활동 체크', 'EN': 'Family check', 'JA': '家族活動チェック', 'ZH': '家庭活动打卡', 'FR': 'Bilan familial', 'DE': 'Familien-Check', 'RU': 'Семейные отметки', 'AR': 'تسجيل العائلة', 'HI': 'पारिवारिक चेक', 'VI': 'Điểm danh gia đình', 'ES': 'Registro familiar', 'TH': 'เช็กกิจกรรมครอบครัว'},
  'colCheck': {'KO': '가족 활동 별', 'EN': 'Check stars', 'JA': '家族活動の星', 'ZH': '家庭活动星', 'FR': 'Étoiles du bilan', 'DE': 'Check-Sterne', 'RU': 'За отметки', 'AR': 'نجوم التسجيل', 'HI': 'चेक सितारे', 'VI': 'Sao điểm danh', 'ES': 'Estrellas del registro', 'TH': 'ดาวจากการเช็ก'},
  'ruleCheck': {'KO': '가족 활동 체크 (하루 최대 20개)', 'EN': 'Family check (up to 20 a day)', 'JA': '家族活動チェック（1日最大20個）', 'ZH': '家庭活动打卡（每天最多20颗）', 'FR': 'Bilan familial (20 max/jour)', 'DE': 'Familien-Check (max. 20 pro Tag)', 'RU': 'Семейные отметки (до 20 в день)', 'AR': 'تسجيل العائلة (حتى 20 يوميًا)', 'HI': 'पारिवारिक चेक (रोज़ 20 तक)', 'VI': 'Điểm danh gia đình (tối đa 20/ngày)', 'ES': 'Registro familiar (hasta 20 al día)', 'TH': 'เช็กกิจกรรมครอบครัว (วันละไม่เกิน 20)'},

  // ---------------- 🆕 [응원 가족 2026-09-30] ----------------
  'rel_mom': {'KO': '엄마', 'EN': 'Mom', 'JA': 'ママ', 'ZH': '妈妈', 'FR': 'Maman', 'DE': 'Mama', 'RU': 'Мама', 'AR': 'أمي', 'HI': 'मम्मी', 'VI': 'Mẹ', 'ES': 'Mamá', 'TH': 'แม่'},
  'rel_dad': {'KO': '아빠', 'EN': 'Dad', 'JA': 'パパ', 'ZH': '爸爸', 'FR': 'Papa', 'DE': 'Papa', 'RU': 'Папа', 'AR': 'أبي', 'HI': 'पापा', 'VI': 'Bố', 'ES': 'Papá', 'TH': 'พ่อ'},
  'rel_guardian': {'KO': '보호자', 'EN': 'Guardian', 'JA': '保護者', 'ZH': '监护人', 'FR': 'Tuteur', 'DE': 'Erziehungsberechtigte/r', 'RU': 'Опекун', 'AR': 'ولي الأمر', 'HI': 'अभिभावक', 'VI': 'Người giám hộ', 'ES': 'Tutor', 'TH': 'ผู้ปกครอง'},
  'rel_grandma': {'KO': '할머니', 'EN': 'Grandma', 'JA': 'おばあちゃん', 'ZH': '奶奶', 'FR': 'Mamie', 'DE': 'Oma', 'RU': 'Бабушка', 'AR': 'جدتي', 'HI': 'दादी', 'VI': 'Bà nội', 'ES': 'Abuela', 'TH': 'ย่า'},
  'rel_grandpa': {'KO': '할아버지', 'EN': 'Grandpa', 'JA': 'おじいちゃん', 'ZH': '爷爷', 'FR': 'Papi', 'DE': 'Opa', 'RU': 'Дедушка', 'AR': 'جدي', 'HI': 'दादा', 'VI': 'Ông nội', 'ES': 'Abuelo', 'TH': 'ปู่'},
  'rel_grandmaM': {'KO': '외할머니', 'EN': 'Grandma (mom\'s side)', 'JA': '母方のおばあちゃん', 'ZH': '外婆', 'FR': 'Mamie (côté maman)', 'DE': 'Oma (mütterlich)', 'RU': 'Бабушка (по маме)', 'AR': 'جدتي (من الأم)', 'HI': 'नानी', 'VI': 'Bà ngoại', 'ES': 'Abuela materna', 'TH': 'ยาย'},
  'rel_grandpaM': {'KO': '외할아버지', 'EN': 'Grandpa (mom\'s side)', 'JA': '母方のおじいちゃん', 'ZH': '外公', 'FR': 'Papi (côté maman)', 'DE': 'Opa (mütterlich)', 'RU': 'Дедушка (по маме)', 'AR': 'جدي (من الأم)', 'HI': 'नाना', 'VI': 'Ông ngoại', 'ES': 'Abuelo materno', 'TH': 'ตา'},
  'rel_auntM': {'KO': '이모', 'EN': 'Aunt (mom\'s sister)', 'JA': 'おば（母の姉妹）', 'ZH': '姨妈', 'FR': 'Tante (sœur de maman)', 'DE': 'Tante (Mamas Schwester)', 'RU': 'Тётя (сестра мамы)', 'AR': 'خالة', 'HI': 'मौसी', 'VI': 'Dì', 'ES': 'Tía (hermana de mamá)', 'TH': 'น้า/ป้า (ฝั่งแม่)'},
  'rel_auntP': {'KO': '고모', 'EN': 'Aunt (dad\'s sister)', 'JA': 'おば（父の姉妹）', 'ZH': '姑姑', 'FR': 'Tante (sœur de papa)', 'DE': 'Tante (Papas Schwester)', 'RU': 'Тётя (сестра папы)', 'AR': 'عمة', 'HI': 'बुआ', 'VI': 'Cô', 'ES': 'Tía (hermana de papá)', 'TH': 'อา/ป้า (ฝั่งพ่อ)'},
  'rel_uncleP': {'KO': '삼촌', 'EN': 'Uncle (dad\'s side)', 'JA': 'おじ（父方）', 'ZH': '叔叔', 'FR': 'Oncle (côté papa)', 'DE': 'Onkel (väterlich)', 'RU': 'Дядя (по папе)', 'AR': 'عم', 'HI': 'चाचा', 'VI': 'Chú', 'ES': 'Tío (paterno)', 'TH': 'อา/ลุง (ฝั่งพ่อ)'},
  'rel_uncleM': {'KO': '외삼촌', 'EN': 'Uncle (mom\'s side)', 'JA': 'おじ（母方）', 'ZH': '舅舅', 'FR': 'Oncle (côté maman)', 'DE': 'Onkel (mütterlich)', 'RU': 'Дядя (по маме)', 'AR': 'خال', 'HI': 'मामा', 'VI': 'Cậu', 'ES': 'Tío (materno)', 'TH': 'น้า/ลุง (ฝั่งแม่)'},
  'rel_brother': {'KO': '형·오빠', 'EN': 'Big brother', 'JA': 'お兄ちゃん', 'ZH': '哥哥', 'FR': 'Grand frère', 'DE': 'Großer Bruder', 'RU': 'Старший брат', 'AR': 'الأخ الأكبر', 'HI': 'बड़ा भाई', 'VI': 'Anh trai', 'ES': 'Hermano mayor', 'TH': 'พี่ชาย'},
  'rel_sister': {'KO': '누나·언니', 'EN': 'Big sister', 'JA': 'お姉ちゃん', 'ZH': '姐姐', 'FR': 'Grande sœur', 'DE': 'Große Schwester', 'RU': 'Старшая сестра', 'AR': 'الأخت الكبرى', 'HI': 'बड़ी बहन', 'VI': 'Chị gái', 'ES': 'Hermana mayor', 'TH': 'พี่สาว'},
  'rel_uncleW': {'KO': '이모부', 'EN': 'Uncle (aunt\'s husband)', 'JA': 'おじ（母方のおばの夫）', 'ZH': '姨父', 'FR': 'Oncle (mari de la tante)', 'DE': 'Onkel (Mann der Tante)', 'RU': 'Дядя (муж тёти)', 'AR': 'زوج الخالة', 'HI': 'मौसा', 'VI': 'Dượng', 'ES': 'Tío (esposo de la tía)', 'TH': 'น้าเขย'},
  'senderMore': {'KO': '보호자 관계를 골라 주세요', 'EN': 'Choose your relationship', 'JA': '続柄を選んでください', 'ZH': '请选择您的关系', 'FR': 'Choisissez votre lien', 'DE': 'Wähle deine Beziehung', 'RU': 'Выберите, кем вы приходитесь', 'AR': 'اختر صلة القرابة', 'HI': 'अपना रिश्ता चुनें', 'VI': 'Chọn mối quan hệ', 'ES': 'Elige tu relación', 'TH': 'เลือกความสัมพันธ์'},
  'dashParentReqTitle': {'KO': '보호자 연결 신청', 'EN': 'Guardian connection requests', 'JA': '保護者連携の申請', 'ZH': '监护人连接申请', 'FR': 'Demandes de tuteur', 'DE': 'Anfragen als Erziehungsberechtigte/r', 'RU': 'Заявки опекунов', 'AR': 'طلبات ربط ولي الأمر', 'HI': 'अभिभावक जुड़ने के अनुरोध', 'VI': 'Yêu cầu kết nối phụ huynh', 'ES': 'Solicitudes de tutor', 'TH': 'คำขอเชื่อมต่อผู้ปกครอง'},
  'parentReqSent': {'KO': '이미 보호자가 연결된 아이예요. 먼저 연결된 보호자에게 승인 요청을 보냈어요. 승인되면 코드를 한 번 더 넣어 주세요.', 'EN': 'This child already has a guardian. A request was sent for approval. Once approved, enter the code again.', 'JA': 'すでに保護者が連携しています。承認依頼を送りました。承認後、もう一度コードを入力してください。', 'ZH': '该孩子已有监护人。已发送批准请求，批准后请再次输入代码。', 'FR': 'Cet enfant a déjà un tuteur. Une demande d\'approbation a été envoyée. Une fois approuvée, saisissez à nouveau le code.', 'DE': 'Für dieses Kind gibt es schon Erziehungsberechtigte. Eine Freigabe-Anfrage wurde gesendet. Nach der Freigabe den Code erneut eingeben.', 'RU': 'У ребёнка уже есть опекун. Запрос на одобрение отправлен. После одобрения введите код ещё раз.', 'AR': 'لهذا الطفل ولي أمر بالفعل. تم إرسال طلب موافقة. بعد الموافقة أدخل الرمز مرة أخرى.', 'HI': 'इस बच्चे के अभिभावक पहले से जुड़े हैं। स्वीकृति अनुरोध भेजा गया। स्वीकृति के बाद कोड फिर से डालें।', 'VI': 'Bé đã có phụ huynh kết nối. Đã gửi yêu cầu duyệt. Sau khi được duyệt, hãy nhập lại mã.', 'ES': 'Este niño ya tiene un tutor. Se envió una solicitud de aprobación. Cuando se apruebe, ingresa el código de nuevo.', 'TH': 'เด็กคนนี้มีผู้ปกครองเชื่อมต่อแล้ว ได้ส่งคำขออนุมัติแล้ว เมื่ออนุมัติให้ใส่รหัสอีกครั้ง'},
  'rel_other': {'KO': '기타', 'EN': 'Other', 'JA': 'その他', 'ZH': '其他', 'FR': 'Autre', 'DE': 'Andere', 'RU': 'Другое', 'AR': 'أخرى', 'HI': 'अन्य', 'VI': 'Khác', 'ES': 'Otro', 'TH': 'อื่น ๆ'},
  'supConnectBtn': {'KO': '응원 가족으로 연결 (손주·조카 등)', 'EN': 'Join as a family supporter', 'JA': '応援家族として連携（孫・甥姪など）', 'ZH': '作为加油家人连接（孙辈·侄甥等）', 'FR': 'Rejoindre comme soutien familial', 'DE': 'Als Familien-Unterstützer verbinden', 'RU': 'Подключиться как член семьи', 'AR': 'الانضمام كداعم من العائلة', 'HI': 'परिवार समर्थक के रूप में जुड़ें', 'VI': 'Kết nối làm người thân cổ vũ', 'ES': 'Unirse como familiar que anima', 'TH': 'เชื่อมต่อเป็นครอบครัวผู้ให้กำลังใจ'},
  'supPending': {'KO': '승인 기다리는 중 · 코드 {c}', 'EN': 'Waiting for approval · Code {c}', 'JA': '承認待ち · コード {c}', 'ZH': '等待批准 · 代码 {c}', 'FR': 'En attente d\'approbation · Code {c}', 'DE': 'Wartet auf Freigabe · Code {c}', 'RU': 'Ожидает одобрения · Код {c}', 'AR': 'بانتظار الموافقة · الرمز {c}', 'HI': 'स्वीकृति की प्रतीक्षा · कोड {c}', 'VI': 'Đang chờ duyệt · Mã {c}', 'ES': 'Esperando aprobación · Código {c}', 'TH': 'รออนุมัติ · รหัส {c}'},
  'supMonthLine': {'KO': '이번 달 {h}시간 · {d}일 공부', 'EN': 'This month: {h} h · {d} days of study', 'JA': '今月 {h}時間 · {d}日勉強', 'ZH': '本月 {h}小时 · 学习{d}天', 'FR': 'Ce mois : {h} h · {d} jours d\'étude', 'DE': 'Diesen Monat: {h} Std. · {d} Lerntage', 'RU': 'В этом месяце: {h} ч · {d} дн. учёбы', 'AR': 'هذا الشهر: {h} ساعة · {d} أيام دراسة', 'HI': 'इस महीने: {h} घंटे · {d} दिन पढ़ाई', 'VI': 'Tháng này: {h} giờ · {d} ngày học', 'ES': 'Este mes: {h} h · {d} días de estudio', 'TH': 'เดือนนี้ {h} ชม. · เรียน {d} วัน'},
  'supDlgTitle': {'KO': '응원 가족 신청', 'EN': 'JOIN AS FAMILY SUPPORTER', 'JA': '応援家族の申請', 'ZH': '申请成为加油家人', 'FR': 'Demande de soutien familial', 'DE': 'Familien-Unterstützer werden', 'RU': 'Заявка члена семьи', 'AR': 'طلب الانضمام كداعم', 'HI': 'परिवार समर्थक आवेदन', 'VI': 'Đăng ký người thân cổ vũ', 'ES': 'Solicitud de familiar que anima', 'TH': 'สมัครเป็นครอบครัวผู้ให้กำลังใจ'},
  'supDlgIntro': {'KO': '응원할 아이의 6자리 코드를 넣고, 아이와의 관계를 골라 주세요. 아이의 보호자가 승인하면 별과 응원을 보낼 수 있어요.', 'EN': 'Enter the child\'s 6-digit code and choose your relationship. Once the child\'s guardian approves, you can send stars and cheers.', 'JA': '応援する子どもの6桁のコードを入力し、関係を選んでください。保護者が承認すると星と応援を送れます。', 'ZH': '输入孩子的6位代码并选择关系。孩子的监护人批准后即可发送星星和加油。', 'FR': 'Saisissez le code à 6 chiffres de l\'enfant et votre lien. Une fois approuvé par le parent, vous pourrez envoyer étoiles et encouragements.', 'DE': 'Gib den 6-stelligen Code des Kindes ein und wähle die Beziehung. Nach Freigabe durch die Eltern kannst du Sterne senden.', 'RU': 'Введите 6-значный код ребёнка и выберите, кем вы ему приходитесь. После одобрения родителем можно отправлять звёзды.', 'AR': 'أدخل رمز الطفل المكوّن من 6 أرقام واختر صلة القرابة. بعد موافقة ولي الأمر يمكنك إرسال النجوم والتشجيع.', 'HI': 'बच्चे का 6 अंकों का कोड डालें और रिश्ता चुनें। अभिभावक की स्वीकृति के बाद आप सितारे भेज सकते हैं।', 'VI': 'Nhập mã 6 số của con và chọn mối quan hệ. Khi phụ huynh duyệt, bạn có thể gửi sao và lời cổ vũ.', 'ES': 'Ingresa el código de 6 dígitos del niño/a y elige tu relación. Cuando el tutor apruebe, podrás enviar estrellas.', 'TH': 'ใส่รหัส 6 หลักของเด็กและเลือกความสัมพันธ์ เมื่อผู้ปกครองอนุมัติแล้วจะส่งดาวและกำลังใจได้'},
  'supCodeLabel': {'KO': '아이 코드 (6자리)', 'EN': 'Child\'s code (6 digits)', 'JA': '子どものコード（6桁）', 'ZH': '孩子代码（6位）', 'FR': 'Code de l\'enfant (6 chiffres)', 'DE': 'Code des Kindes (6-stellig)', 'RU': 'Код ребёнка (6 цифр)', 'AR': 'رمز الطفل (6 أرقام)', 'HI': 'बच्चे का कोड (6 अंक)', 'VI': 'Mã của con (6 số)', 'ES': 'Código del niño/a (6 dígitos)', 'TH': 'รหัสเด็ก (6 หลัก)'},
  'supNameLabel': {'KO': '내 이름', 'EN': 'My name', 'JA': '自分の名前', 'ZH': '我的名字', 'FR': 'Mon nom', 'DE': 'Mein Name', 'RU': 'Моё имя', 'AR': 'اسمي', 'HI': 'मेरा नाम', 'VI': 'Tên của tôi', 'ES': 'Mi nombre', 'TH': 'ชื่อของฉัน'},
  'supRelLabel': {'KO': '아이와의 관계', 'EN': 'Relationship to the child', 'JA': '子どもとの関係', 'ZH': '与孩子的关系', 'FR': 'Lien avec l\'enfant', 'DE': 'Beziehung zum Kind', 'RU': 'Кем приходитесь ребёнку', 'AR': 'صلة القرابة بالطفل', 'HI': 'बच्चे से रिश्ता', 'VI': 'Quan hệ với con', 'ES': 'Relación con el niño/a', 'TH': 'ความสัมพันธ์กับเด็ก'},
  'supOtherHint': {'KO': '관계 직접 쓰기 (예: 큰아빠)', 'EN': 'Write the relationship', 'JA': '関係を入力', 'ZH': '自行填写关系', 'FR': 'Précisez le lien', 'DE': 'Beziehung eingeben', 'RU': 'Напишите, кем приходитесь', 'AR': 'اكتب صلة القرابة', 'HI': 'रिश्ता लिखें', 'VI': 'Tự nhập mối quan hệ', 'ES': 'Escribe la relación', 'TH': 'พิมพ์ความสัมพันธ์เอง'},
  'supSendReq': {'KO': '신청하기', 'EN': 'Send request', 'JA': '申請する', 'ZH': '提交申请', 'FR': 'Envoyer', 'DE': 'Anfrage senden', 'RU': 'Отправить', 'AR': 'إرسال الطلب', 'HI': 'अनुरोध भेजें', 'VI': 'Gửi yêu cầu', 'ES': 'Enviar solicitud', 'TH': 'ส่งคำขอ'},
  'supReqDone': {'KO': '신청했어요. 보호자가 승인하면 별을 보낼 수 있어요.', 'EN': 'Request sent. You can send stars once the guardian approves.', 'JA': '申請しました。保護者が承認すると星を送れます。', 'ZH': '已提交申请。监护人批准后即可发送星星。', 'FR': 'Demande envoyée. Vous pourrez envoyer des étoiles après approbation.', 'DE': 'Anfrage gesendet. Nach Freigabe kannst du Sterne senden.', 'RU': 'Заявка отправлена. После одобрения можно отправлять звёзды.', 'AR': 'تم إرسال الطلب. يمكنك إرسال النجوم بعد موافقة ولي الأمر.', 'HI': 'अनुरोध भेजा गया। स्वीकृति के बाद सितारे भेज सकते हैं।', 'VI': 'Đã gửi yêu cầu. Khi phụ huynh duyệt, bạn có thể gửi sao.', 'ES': 'Solicitud enviada. Podrás enviar estrellas cuando el tutor apruebe.', 'TH': 'ส่งคำขอแล้ว เมื่อผู้ปกครองอนุมัติจะส่งดาวได้'},
  'errSup6': {'KO': '6자리 숫자를 넣어 주세요', 'EN': 'Enter 6 digits', 'JA': '6桁の数字を入力してください', 'ZH': '请输入6位数字', 'FR': 'Saisissez 6 chiffres', 'DE': 'Bitte 6 Ziffern eingeben', 'RU': 'Введите 6 цифр', 'AR': 'أدخل 6 أرقام', 'HI': '6 अंक डालें', 'VI': 'Hãy nhập 6 chữ số', 'ES': 'Ingresa 6 dígitos', 'TH': 'กรุณาใส่ตัวเลข 6 หลัก'},
  'errSupCode': {'KO': '없는 코드예요. 아이에게 코드를 다시 확인해 주세요', 'EN': 'Code not found. Please check with the child', 'JA': '存在しないコードです。子どもに確認してください', 'ZH': '代码不存在，请向孩子确认', 'FR': 'Code introuvable. Vérifiez auprès de l\'enfant', 'DE': 'Code nicht gefunden. Bitte beim Kind nachfragen', 'RU': 'Код не найден. Уточните у ребёнка', 'AR': 'الرمز غير موجود. تحقق مع الطفل', 'HI': 'कोड नहीं मिला। बच्चे से जाँचें', 'VI': 'Không tìm thấy mã. Hãy hỏi lại con', 'ES': 'Código no encontrado. Verifícalo con el niño/a', 'TH': 'ไม่พบรหัส กรุณาตรวจสอบกับเด็ก'},
  'errSupFull': {'KO': '응원 가족 자리가 가득 찼거나 신청할 수 없는 코드예요', 'EN': 'The supporter spots are full, or this code cannot accept requests', 'JA': '応援家族の枠がいっぱいか、申請できないコードです', 'ZH': '加油家人名额已满或该代码无法申请', 'FR': 'Places pleines ou code indisponible', 'DE': 'Plätze voll oder Code nicht verfügbar', 'RU': 'Мест нет или код недоступен', 'AR': 'الأماكن ممتلئة أو لا يمكن التقديم بهذا الرمز', 'HI': 'स्थान भरे हैं या इस कोड पर आवेदन नहीं हो सकता', 'VI': 'Đã đủ chỗ hoặc mã không nhận đăng ký', 'ES': 'Plazas llenas o código no disponible', 'TH': 'ที่นั่งเต็มหรือรหัสนี้สมัครไม่ได้'},
  'senderLabel': {'KO': '보내는 사람', 'EN': 'From', 'JA': '送る人', 'ZH': '发送人', 'FR': 'De la part de', 'DE': 'Von', 'RU': 'От кого', 'AR': 'المُرسِل', 'HI': 'भेजने वाला', 'VI': 'Người gửi', 'ES': 'De parte de', 'TH': 'ผู้ส่ง'},
  'popupFrom': {'KO': '{who}의 응원', 'EN': 'Cheer from {who}', 'JA': '{who}からの応援', 'ZH': '来自{who}的加油', 'FR': 'Encouragement de {who}', 'DE': 'Anfeuerung von {who}', 'RU': 'Поддержка от {who}', 'AR': 'تشجيع من {who}', 'HI': '{who} की ओर से प्रोत्साहन', 'VI': 'Cổ vũ từ {who}', 'ES': 'Ánimo de {who}', 'TH': 'กำลังใจจาก {who}'},
  'giftByFamily': {'KO': '응원해 주는 가족', 'EN': 'Family cheering for you', 'JA': '応援してくれる家族', 'ZH': '为你加油的家人', 'FR': 'La famille qui t\'encourage', 'DE': 'Deine Familie feuert dich an', 'RU': 'Семья, которая тебя поддерживает', 'AR': 'عائلتك التي تشجعك', 'HI': 'तुम्हें प्रोत्साहित करने वाला परिवार', 'VI': 'Gia đình cổ vũ con', 'ES': 'La familia que te anima', 'TH': 'ครอบครัวที่ให้กำลังใจ'},
  'giftActsWho': {'KO': '오늘 {who}의 노력: {list}', 'EN': 'Today {who} did: {list}', 'JA': '今日の{who}の努力: {list}', 'ZH': '今天{who}的努力: {list}', 'FR': 'Aujourd\'hui {who} a fait : {list}', 'DE': 'Heute hat {who}: {list}', 'RU': 'Сегодня {who}: {list}', 'AR': 'اليوم قام {who} بـ: {list}', 'HI': 'आज {who} ने: {list}', 'VI': 'Hôm nay {who}: {list}', 'ES': 'Hoy {who} hizo: {list}', 'TH': 'วันนี้ {who} ทำ: {list}'},
  'dashSupBar': {'KO': '응원 가족 {n}/{max}', 'EN': 'Family supporters {n}/{max}', 'JA': '応援家族 {n}/{max}', 'ZH': '加油家人 {n}/{max}', 'FR': 'Soutiens {n}/{max}', 'DE': 'Unterstützer {n}/{max}', 'RU': 'Семья {n}/{max}', 'AR': 'الداعمون {n}/{max}', 'HI': 'परिवार समर्थक {n}/{max}', 'VI': 'Người thân {n}/{max}', 'ES': 'Familiares {n}/{max}', 'TH': 'ครอบครัว {n}/{max}'},
  'dashSupReq': {'KO': '신청 {n}건', 'EN': '{n} request(s)', 'JA': '申請 {n}件', 'ZH': '{n}个申请', 'FR': '{n} demande(s)', 'DE': '{n} Anfrage(n)', 'RU': 'Заявок: {n}', 'AR': '{n} طلب', 'HI': '{n} अनुरोध', 'VI': '{n} yêu cầu', 'ES': '{n} solicitud(es)', 'TH': 'คำขอ {n} รายการ'},
  'dashSupTitle': {'KO': '응원 가족 관리', 'EN': 'Family Supporters', 'JA': '応援家族の管理', 'ZH': '加油家人管理', 'FR': 'Soutiens familiaux', 'DE': 'Familien-Unterstützer', 'RU': 'Члены семьи', 'AR': 'الداعمون من العائلة', 'HI': 'परिवार समर्थक', 'VI': 'Người thân cổ vũ', 'ES': 'Familiares que animan', 'TH': 'ครอบครัวผู้ให้กำลังใจ'},
  'dashSupReqTitle': {'KO': '승인 기다리는 신청', 'EN': 'Waiting for approval', 'JA': '承認待ちの申請', 'ZH': '等待批准的申请', 'FR': 'En attente d\'approbation', 'DE': 'Wartende Anfragen', 'RU': 'Ожидают одобрения', 'AR': 'بانتظار الموافقة', 'HI': 'स्वीकृति प्रतीक्षित', 'VI': 'Đang chờ duyệt', 'ES': 'Pendientes de aprobación', 'TH': 'รออนุมัติ'},
  'dashSupListTitle': {'KO': '응원 가족', 'EN': 'Supporters', 'JA': '応援家族', 'ZH': '加油家人', 'FR': 'Soutiens', 'DE': 'Unterstützer', 'RU': 'Члены семьи', 'AR': 'الداعمون', 'HI': 'समर्थक', 'VI': 'Người thân', 'ES': 'Familiares', 'TH': 'ครอบครัว'},
  'dashApprove': {'KO': '승인', 'EN': 'Approve', 'JA': '承認', 'ZH': '批准', 'FR': 'Approuver', 'DE': 'Freigeben', 'RU': 'Одобрить', 'AR': 'موافقة', 'HI': 'स्वीकार', 'VI': 'Duyệt', 'ES': 'Aprobar', 'TH': 'อนุมัติ'},
  'dashReject': {'KO': '거절', 'EN': 'Decline', 'JA': '拒否', 'ZH': '拒绝', 'FR': 'Refuser', 'DE': 'Ablehnen', 'RU': 'Отклонить', 'AR': 'رفض', 'HI': 'अस्वीकार', 'VI': 'Từ chối', 'ES': 'Rechazar', 'TH': 'ปฏิเสธ'},
  'dashRemove': {'KO': '해제', 'EN': 'Remove', 'JA': '解除', 'ZH': '解除', 'FR': 'Retirer', 'DE': 'Entfernen', 'RU': 'Удалить', 'AR': 'إزالة', 'HI': 'हटाएं', 'VI': 'Gỡ', 'ES': 'Quitar', 'TH': 'ยกเลิก'},
  'dashSupEmpty': {'KO': '아직 응원 가족이 없어요.\n할머니·삼촌 등이 일반 회원으로 가입한 뒤, 부모 응원별 화면에서 이 아이의 코드로 신청하면 여기에 나타나요.', 'EN': 'No supporters yet.\nWhen grandparents or relatives sign up as general members and request with this child\'s code, they will appear here.', 'JA': 'まだ応援家族がいません。\n祖父母などが一般会員で登録し、この子のコードで申請するとここに表示されます。', 'ZH': '还没有加油家人。\n祖父母等以普通会员注册并用此孩子的代码申请后，会显示在这里。', 'FR': 'Aucun soutien pour l\'instant.\nLes proches inscrits en compte général qui envoient une demande avec le code de l\'enfant apparaîtront ici.', 'DE': 'Noch keine Unterstützer.\nVerwandte mit allgemeinem Konto, die mit dem Code anfragen, erscheinen hier.', 'RU': 'Пока никого нет.\nРодственники с обычным аккаунтом, подавшие заявку по коду ребёнка, появятся здесь.', 'AR': 'لا يوجد داعمون بعد.\nسيظهر الأقارب هنا بعد التسجيل كعضو عام والتقديم برمز الطفل.', 'HI': 'अभी कोई समर्थक नहीं।\nरिश्तेदार सामान्य सदस्य बनकर इस बच्चे के कोड से आवेदन करेंगे तो यहाँ दिखेंगे।', 'VI': 'Chưa có người thân nào.\nKhi ông bà, họ hàng đăng ký tài khoản thường và gửi yêu cầu bằng mã của con, họ sẽ hiện ở đây.', 'ES': 'Aún no hay familiares.\nCuando se registren como miembros generales y soliciten con el código del niño/a, aparecerán aquí.', 'TH': 'ยังไม่มีครอบครัวผู้ให้กำลังใจ\nเมื่อญาติสมัครสมาชิกทั่วไปและส่งคำขอด้วยรหัสของเด็ก จะแสดงที่นี่'},
  'dashSupFull': {'KO': '응원 가족은 최대 5명이에요', 'EN': 'Up to 5 supporters', 'JA': '応援家族は最大5人です', 'ZH': '加油家人最多5人', 'FR': '5 soutiens maximum', 'DE': 'Maximal 5 Unterstützer', 'RU': 'Не больше 5 человек', 'AR': '5 داعمين كحد أقصى', 'HI': 'अधिकतम 5 समर्थक', 'VI': 'Tối đa 5 người', 'ES': 'Máximo 5 familiares', 'TH': 'สูงสุด 5 คน'},
  'dashRemoveConfirm': {'KO': '{who} — 응원 가족에서 해제할까요?', 'EN': 'Remove {who} from supporters?', 'JA': '{who} — 応援家族から解除しますか？', 'ZH': '{who} — 要从加油家人中解除吗？', 'FR': 'Retirer {who} des soutiens ?', 'DE': '{who} als Unterstützer entfernen?', 'RU': 'Удалить {who}?', 'AR': 'إزالة {who} من الداعمين؟', 'HI': '{who} को समर्थकों से हटाएं?', 'VI': 'Gỡ {who} khỏi người thân cổ vũ?', 'ES': '¿Quitar a {who}?', 'TH': 'ยกเลิก {who} จากครอบครัวผู้ให้กำลังใจ?'},

  // ---------------- 학부모방 장학금 탭 카드 ----------------
  'parentCardSaved': {'KO': '모아 둔 별 {n}개', 'EN': 'Saved stars: {n}', 'JA': '貯めた星 {n}個', 'ZH': '攒下的星星 {n}颗', 'FR': 'Étoiles épargnées : {n}', 'DE': 'Gesparte Sterne: {n}', 'RU': 'Накоплено: {n}', 'AR': 'النجوم المدخرة: {n}', 'HI': 'जमा सितारे: {n}', 'VI': 'Sao đã tích lũy: {n}', 'ES': 'Estrellas ahorradas: {n}', 'TH': 'ดาวที่สะสมไว้ {n} ดวง'},
  'btnExercise': {'KO': '운동하기', 'EN': 'Exercise', 'JA': '運動する', 'ZH': '去运动', 'FR': 'Faire du sport', 'DE': 'Trainieren', 'RU': 'Тренироваться', 'AR': 'تمرّن', 'HI': 'व्यायाम करें', 'VI': 'Tập luyện', 'ES': 'Hacer ejercicio', 'TH': 'ออกกำลังกาย'},

  // ---------------- 학생 황금색 카드 ----------------
  'giftActs': {'KO': '오늘 엄마 아빠는: {list}', 'EN': 'Today Mom & Dad: {list}', 'JA': '今日のママとパパ: {list}', 'ZH': '今天爸爸妈妈: {list}', 'FR': 'Aujourd\'hui, Papa et Maman : {list}', 'DE': 'Heute Mama & Papa: {list}', 'RU': 'Сегодня мама и папа: {list}', 'AR': 'اليوم أمي وأبي: {list}', 'HI': 'आज मम्मी-पापा: {list}', 'VI': 'Hôm nay bố mẹ: {list}', 'ES': 'Hoy mamá y papá: {list}', 'TH': 'วันนี้พ่อแม่: {list}'},
  'giftActEx': {'KO': '운동 {n}분', 'EN': 'exercise {n} min', 'JA': '運動{n}分', 'ZH': '运动{n}分钟', 'FR': 'sport {n} min', 'DE': 'Sport {n} Min.', 'RU': 'спорт {n} мин', 'AR': 'تمرين {n} دقيقة', 'HI': 'व्यायाम {n} मिनट', 'VI': 'tập {n} phút', 'ES': 'ejercicio {n} min', 'TH': 'ออกกำลังกาย {n} นาที'},
  'giftTitle': {'KO': '부모님이 보내 준 응원별', 'EN': 'CHEER STARS FROM PARENTS', 'JA': '保護者からの応援スター', 'ZH': '爸妈送来的加油星', 'FR': 'Étoiles de mes parents', 'DE': 'Sterne von meinen Eltern', 'RU': 'Звёзды от родителей', 'AR': 'نجوم التشجيع من الوالدين', 'HI': 'माता-पिता के प्रोत्साहन सितारे', 'VI': 'Sao cổ vũ từ bố mẹ', 'ES': 'Estrellas de mis padres', 'TH': 'ดาวให้กำลังใจจากพ่อแม่'},
  'giftTotal': {'KO': '받은 응원별 전체', 'EN': 'Total received', 'JA': 'もらった応援スター合計', 'ZH': '收到的星星总数', 'FR': 'Total reçu', 'DE': 'Insgesamt erhalten', 'RU': 'Всего получено', 'AR': 'إجمالي ما وصلك', 'HI': 'कुल मिले', 'VI': 'Tổng đã nhận', 'ES': 'Total recibido', 'TH': 'ได้รับทั้งหมด'},
  'giftNormal': {'KO': '일반 응원', 'EN': 'Encouragement', 'JA': '通常の応援', 'ZH': '普通鼓励', 'FR': 'Encouragement', 'DE': 'Anfeuerung', 'RU': 'Поддержка', 'AR': 'تشجيع', 'HI': 'सामान्य हौसला', 'VI': 'Cổ vũ thường', 'ES': 'Ánimo', 'TH': 'กำลังใจทั่วไป'},
  'giftSpecial': {'KO': '특별 축하', 'EN': 'Special', 'JA': '特別なお祝い', 'ZH': '特别庆祝', 'FR': 'Spécial', 'DE': 'Besonders', 'RU': 'Особое', 'AR': 'خاص', 'HI': 'विशेष', 'VI': 'Đặc biệt', 'ES': 'Especial', 'TH': 'พิเศษ'},
  'giftRecent': {'KO': '최근 받은 응원', 'EN': 'Recent cheers', 'JA': '最近の応援', 'ZH': '最近收到的鼓励', 'FR': 'Encouragements récents', 'DE': 'Letzte Anfeuerungen', 'RU': 'Недавние', 'AR': 'أحدث التشجيعات', 'HI': 'हाल के हौसले', 'VI': 'Cổ vũ gần đây', 'ES': 'Ánimos recientes', 'TH': 'กำลังใจล่าสุด'},
  'giftEmpty': {'KO': '아직 받은 응원별이 없어요. 부모님이 운동하며 모은 별을 보내 주면 여기에 쌓입니다.', 'EN': 'No cheer stars yet. Stars your parents earn by exercising will appear here.', 'JA': 'まだ応援スターはありません。保護者が運動で集めた星を送るとここに貯まります。', 'ZH': '还没有收到加油星。爸妈运动攒下的星星送来后会显示在这里。', 'FR': "Pas encore d'étoiles. Celles que tes parents gagnent en faisant du sport apparaîtront ici.", 'DE': 'Noch keine Sterne. Sterne, die deine Eltern beim Sport sammeln, erscheinen hier.', 'RU': 'Пока звёзд нет. Здесь появятся звёзды, которые родители заработают спортом.', 'AR': 'لا توجد نجوم بعد. ستظهر هنا النجوم التي يجمعها والداك بالتمرين.', 'HI': 'अभी कोई सितारे नहीं। माता-पिता के व्यायाम से कमाए सितारे यहां दिखेंगे।', 'VI': 'Chưa có sao cổ vũ. Sao bố mẹ tập luyện có được sẽ hiện ở đây.', 'ES': 'Aún no hay estrellas. Aquí aparecerán las que tus padres ganen haciendo ejercicio.', 'TH': 'ยังไม่มีดาวให้กำลังใจ ดาวที่พ่อแม่สะสมจากการออกกำลังกายจะมาอยู่ที่นี่'},
  'giftNote': {'KO': '※ 부모님이 운동해서 모은 별이에요. 내 공부 별·장학금과는 따로 기록됩니다.', 'EN': '※ Stars your parents earned by exercising. Kept separate from your study stars and scholarship.', 'JA': '※ 保護者が運動で集めた星です。勉強の星や奨学金とは別に記録されます。', 'ZH': '※ 这是爸妈运动攒下的星星，与学习星星和奖学金分开记录。', 'FR': '※ Étoiles gagnées par tes parents en faisant du sport, séparées de tes étoiles d\'étude et de ta bourse.', 'DE': '※ Sterne, die deine Eltern beim Sport gesammelt haben – getrennt von Lernsternen und Stipendium.', 'RU': '※ Звёзды, заработанные родителями спортом. Учитываются отдельно от учебных звёзд и стипендии.', 'AR': '※ نجوم جمعها والداك بالتمرين، وتُسجّل منفصلة عن نجوم الدراسة والمنحة.', 'HI': '※ ये माता-पिता ने व्यायाम से कमाए हैं। पढ़ाई के सितारों और छात्रवृत्ति से अलग दर्ज होते हैं।', 'VI': '※ Sao bố mẹ tập luyện có được, ghi riêng với sao học tập và học bổng.', 'ES': '※ Estrellas que tus padres ganaron haciendo ejercicio. Se guardan aparte de tus estrellas de estudio y beca.', 'TH': '※ ดาวที่พ่อแม่สะสมจากการออกกำลังกาย บันทึกแยกจากดาวการเรียนและทุนการศึกษา'},
};

/// 번역 꺼내기.
/// - lang을 안 주면 일반 플래너 언어 선택(appLanguage)을 따름
/// - args로 {n}, {m} 같은 자리를 채움
String cs(String key, {String? lang, Map<String, Object>? args}) {
  final String l = (lang ?? appLanguage.current).toUpperCase();
  final Map<String, String>? m = kCheerStarsText[key];
  String s = m?[l] ?? m?['EN'] ?? m?['KO'] ?? key;
  args?.forEach((k, v) => s = s.replaceAll('{$k}', '$v'));
  return s;
}

/// 영문 원문 (한국어 모드에서 제목 윗줄에 쓰는 영어)
String csEn(String key) => kCheerStarsText[key]?['EN'] ?? key;

/// 한국어 원문
String csKo(String key) => kCheerStarsText[key]?['KO'] ?? key;
