// exercise_type_data.dart (v2)
//
// 각 종목의 필드는 아래 실제 트래킹 관행/스포츠과학 자료를 근거로 선정했다.
// - 골프: 페어웨이 안착률·그린 적중률(GIR)이 스코어와 가장 상관관계가 높은 지표
//         (Arccos/Shot Scope 트래킹 데이터, MyGolfSpy·GOLF.com 분석 기준)
// - 수영: SWOLF(스트로크수+시간)가 대표적 효율 지표 (MySwimPro 등 표준)
// - 러닝: 페이스·케이던스·심박수가 3대 핵심 지표 (COROS/Garmin/TrainingPeaks 공통)
// - 헬스: 볼륨(세트x횟수x중량)과 RPE/추정1RM이 표준 트레이닝 지표 (RPE 기반 자기조절 트레이닝)
// - 등산/자전거: 누적 상승고도가 거리보다 체력 소모를 더 잘 설명 (Strava Elevation 기준)
//
// 위 근거 지표는 "필수 입력"이 아니라 "제공되는 필드"다. 사용자가 부담스러우면
// isRequired: false인 필드는 비워둘 수 있다.

import 'exercise_models.dart';

// ---------------------------------------------------------------------------
// 여러 종목이 공유하는 필드 (재사용 헬퍼)
// ---------------------------------------------------------------------------

ExerciseField _distanceKmField({String label = '거리', String enLabel = 'Distance', String unit = 'km', String? section, String? sectionEn}) =>
    ExerciseField(
      key: 'distanceKm',
      type: ExerciseFieldType.number,
      label: label,
      enLabel: enLabel,
      unit: unit,
      section: section,
      sectionEn: sectionEn,
    );

ExerciseField _caloriesField({String? section, String? sectionEn}) => ExerciseField(
  key: 'calories',
  type: ExerciseFieldType.number,
  label: '칼로리',
  enLabel: 'Calories',
  unit: 'kcal',
  isCalculated: true,
  section: section,
  sectionEn: sectionEn,
);

ExerciseField _courseField({String label = '코스/장소', String enLabel = 'Course/Location', String? section, String? sectionEn}) => ExerciseField(
  key: 'course',
  type: ExerciseFieldType.text,
  label: label,
  enLabel: enLabel,
  section: section,
  sectionEn: sectionEn,
);

ExerciseField _elevationGainField({String? section, String? sectionEn}) => ExerciseField(
  key: 'elevationGainM',
  type: ExerciseFieldType.number,
  label: '누적 상승고도',
  enLabel: 'Elevation Gain',
  unit: 'm',
  section: section,
  sectionEn: sectionEn,
);

/// 라켓 구기종목(테니스/배드민턴/탁구) 공통 필드.
/// 스포츠과학적으로 승패/세트스코어 외에 "위너-언포스드에러 비율"이 경기력 지표로 쓰이나,
/// 취미 기록 수준에서는 부담을 줄여 선택 입력으로 둔다.
List<ExerciseField> _racketSportFields() => const [
  ExerciseField(
    key: 'matchType',
    type: ExerciseFieldType.select,
    label: '경기 방식',
    enLabel: 'Match Type',
    options: ['단식', '복식'],
    optionEnLabels: ['Singles', 'Doubles'],
    section: '경기 정보',
    sectionEn: 'Match Info',
  ),
  ExerciseField(
    key: 'opponent',
    type: ExerciseFieldType.text,
    label: '상대',
    enLabel: 'Opponent',
    isRequired: false,
    section: '경기 정보',
    sectionEn: 'Match Info',
  ),
  ExerciseField(
    key: 'setScore',
    type: ExerciseFieldType.text,
    label: '세트 스코어',
    enLabel: 'Set Score',
    section: '경기 정보',
    sectionEn: 'Match Info',
  ),
  ExerciseField(
    key: 'result',
    type: ExerciseFieldType.select,
    label: '승패',
    enLabel: 'Result',
    options: ['승', '패'],
    optionEnLabels: ['Win', 'Loss'],
    section: '경기 정보',
    sectionEn: 'Match Info',
  ),
  ExerciseField(
    key: 'winners',
    type: ExerciseFieldType.number,
    label: '위너(득점타)',
    enLabel: 'Winners',
    isRequired: false,
    section: '경기 기록',
    sectionEn: 'Match Stats',
  ),
  ExerciseField(
    key: 'unforcedErrors',
    type: ExerciseFieldType.number,
    label: '언포스드 에러',
    enLabel: 'Unforced Errors',
    isRequired: false,
    section: '경기 기록',
    sectionEn: 'Match Stats',
  ),
  // ✅ [2026-09-14 신규] 테니스/배드민턴/탁구 공통으로 랠리 지속성 지표
  ExerciseField(
    key: 'avgRallyLength',
    type: ExerciseFieldType.number,
    label: '랠리 평균 길이',
    enLabel: 'Avg Rally Length',
    unit: 'shot',
    isRequired: false,
    section: '경기 기록',
    sectionEn: 'Match Stats',
  ),
];

/// 팀 구기종목(농구/축구) 공통 필드.
List<ExerciseField> _teamSportFields() => const [
  ExerciseField(
    key: 'position',
    type: ExerciseFieldType.text,
    label: '포지션',
    enLabel: 'Position',
    section: '경기 정보',
    sectionEn: 'Match Info',
  ),
  ExerciseField(
    key: 'gameDurationMin',
    type: ExerciseFieldType.number,
    label: '경기 시간',
    enLabel: 'Game Duration',
    unit: '분',
    isRequired: false,
    section: '경기 정보',
    sectionEn: 'Match Info',
  ),
  ExerciseField(
    key: 'points',
    type: ExerciseFieldType.number,
    label: '득점',
    enLabel: 'Points',
    section: '경기 기록',
    sectionEn: 'Match Stats',
  ),
  ExerciseField(
    key: 'assists',
    type: ExerciseFieldType.number,
    label: '어시스트',
    enLabel: 'Assists',
    isRequired: false,
    section: '경기 기록',
    sectionEn: 'Match Stats',
  ),
  ExerciseField(
    key: 'distanceKm',
    type: ExerciseFieldType.number,
    label: '이동거리(추정)',
    enLabel: 'Distance (Est.)',
    unit: 'km',
    isRequired: false,
    section: '경기 기록',
    sectionEn: 'Match Stats',
  ),
];

// ---------------------------------------------------------------------------
// 기본 제공 16개 운동 종목
// ---------------------------------------------------------------------------

final List<ExerciseType> kDefaultExerciseTypes = [
  // 1. 골프 - Arccos/Shot Scope 데이터 기준 페어웨이/GIR/퍼팅이 스코어를 가장 잘 설명
  // ✅ [2026-09-13 개편] 사용자 제공 스프레드시트 12항목 기준으로 5개 신규 필드
  // 추가(라운드 수/티 위치/코스 총 거리/PAR 합계/이글 수) + 기존 항목은 유지.
  // 총 16개 필드를 4개 구획(라운드 정보/코스·스코어/숏게임·퍼팅/페어웨이·페널티)으로
  // 나눠서, 세부기록 화면에서 골드색 소제목+구분선으로 묶어 보여줌.
  ExerciseType(
    id: 'golf',
    name: '골프',
    icon: '🏌️',
    isDefault: true,
    sortOrder: 1,
    fields: const [
      // --- 구획 1: 라운드 정보 ---
      ExerciseField(
        key: 'roundCount',
        type: ExerciseFieldType.counter,
        label: '라운드 수',
        enLabel: 'Rounds',
        section: '라운드 정보',
        sectionEn: 'Round Info',
        isRequired: false,
      ),
      ExerciseField(
        key: 'course',
        type: ExerciseFieldType.text,
        label: '코스명',
        enLabel: 'Course Name',
        section: '라운드 정보',
        sectionEn: 'Round Info',
      ),
      ExerciseField(
        key: 'teePosition',
        type: ExerciseFieldType.select,
        label: '티 위치',
        enLabel: 'Tee Position',
        options: ['블랙', '블루', '골드', '레드'],
        optionEnLabels: ['Black', 'Blue', 'Gold', 'Red'],
        section: '라운드 정보',
        sectionEn: 'Round Info',
        isRequired: false,
      ),
      ExerciseField(
        key: 'holeType',
        type: ExerciseFieldType.select,
        label: '총 홀 수',
        enLabel: 'Total Holes',
        options: ['9홀', '18홀'],
        optionEnLabels: ['9 Holes', '18 Holes'],
        section: '라운드 정보',
        sectionEn: 'Round Info',
      ),
      // --- 구획 2: 코스 · 스코어 ---
      ExerciseField(
        key: 'courseDistanceM',
        type: ExerciseFieldType.number,
        label: '코스 총 거리',
        enLabel: 'Course Distance',
        unit: 'm',
        section: '코스 · 스코어',
        sectionEn: 'Course & Score',
        isRequired: false,
      ),
      ExerciseField(
        key: 'parTotal',
        type: ExerciseFieldType.number,
        label: 'PAR 합계',
        enLabel: 'Total Par',
        section: '코스 · 스코어',
        sectionEn: 'Course & Score',
        isRequired: false,
      ),
      ExerciseField(
        key: 'totalScore',
        type: ExerciseFieldType.number,
        label: '총타수',
        enLabel: 'Total Score',
        section: '코스 · 스코어',
        sectionEn: 'Course & Score',
      ),
      ExerciseField(
        key: 'scoreToPar',
        type: ExerciseFieldType.number,
        label: '오버파(스코어-기준파)',
        enLabel: 'Score to Par',
        isCalculated: true,
        section: '코스 · 스코어',
        sectionEn: 'Course & Score',
      ),
      // --- 구획 3: 숏게임 · 퍼팅 ---
      ExerciseField(
        key: 'putts',
        type: ExerciseFieldType.number,
        label: '총 퍼팅수',
        enLabel: 'Total Putts',
        section: '숏게임 · 퍼팅',
        sectionEn: 'Short Game & Putting',
      ),
      ExerciseField(
        key: 'threePutts',
        type: ExerciseFieldType.counter,
        label: '3퍼팅 횟수',
        enLabel: '3-Putts',
        isRequired: false,
        section: '숏게임 · 퍼팅',
        sectionEn: 'Short Game & Putting',
      ),
      ExerciseField(
        key: 'eagle',
        type: ExerciseFieldType.counter,
        label: '이글',
        enLabel: 'Eagles',
        isRequired: false,
        section: '숏게임 · 퍼팅',
        sectionEn: 'Short Game & Putting',
      ),
      ExerciseField(
        key: 'birdie',
        type: ExerciseFieldType.counter,
        label: '버디',
        enLabel: 'Birdies',
        section: '숏게임 · 퍼팅',
        sectionEn: 'Short Game & Putting',
      ),
      ExerciseField(
        key: 'bogeyOrWorse',
        type: ExerciseFieldType.counter,
        label: '보기 이상',
        enLabel: 'Bogey or Worse',
        section: '숏게임 · 퍼팅',
        sectionEn: 'Short Game & Putting',
      ),
      // --- 구획 4: 페어웨이 · 그린 · 페널티 ---
      ExerciseField(
        key: 'fairwaysHit',
        type: ExerciseFieldType.number,
        label: '페어웨이 안착 (14개 중)',
        enLabel: 'Fairways Hit (of 14)',
        section: '페어웨이 · 그린 · 페널티',
        sectionEn: 'Fairways, Greens & Penalties',
      ),
      ExerciseField(
        key: 'greensInRegulation',
        type: ExerciseFieldType.number,
        label: '그린 적중 GIR (18개 중)',
        enLabel: 'Greens in Regulation (of 18)',
        section: '페어웨이 · 그린 · 페널티',
        sectionEn: 'Fairways, Greens & Penalties',
      ),
      ExerciseField(
        key: 'ob',
        type: ExerciseFieldType.counter,
        label: 'OB/벌타',
        enLabel: 'OB/Penalty',
        section: '페어웨이 · 그린 · 페널티',
        sectionEn: 'Fairways, Greens & Penalties',
      ),
    ],
  ),

  // 2. 수영 - SWOLF(효율), 페이스, 영법별 구분이 표준 (MySwimPro 등)
  ExerciseType(
    id: 'swimming',
    name: '수영',
    icon: '🏊',
    isDefault: true,
    sortOrder: 2,
    fields: const [
      ExerciseField(
        key: 'stroke',
        type: ExerciseFieldType.multiSelect,
        label: '영법',
        enLabel: 'Stroke',
        options: ['자유형', '평영', '배영', '접영', '혼계영'],
        optionEnLabels: ['Freestyle', 'Breaststroke', 'Backstroke', 'Butterfly', 'Individual Medley'],
        section: '영법 · 거리',
        sectionEn: 'Stroke & Distance',
      ),
      ExerciseField(
        key: 'distanceM',
        type: ExerciseFieldType.number,
        label: '총 거리',
        enLabel: 'Total Distance',
        unit: 'm',
        section: '영법 · 거리',
        sectionEn: 'Stroke & Distance',
      ),
      ExerciseField(
        key: 'laps',
        type: ExerciseFieldType.number,
        label: '레인(25m) 왕복 수',
        enLabel: 'Laps (25m)',
        section: '영법 · 거리',
        sectionEn: 'Stroke & Distance',
      ),
      // ✅ [2026-09-14 신규] 수영장 길이(25m/50m)에 따라 SWOLF·페이스 계산 기준이
      // 달라지므로 별도 항목으로 분리.
      ExerciseField(
        key: 'poolLength',
        type: ExerciseFieldType.select,
        label: '수영장 길이',
        enLabel: 'Pool Length',
        options: ['25m', '50m'],
        optionEnLabels: ['25m', '50m'],
        section: '영법 · 거리',
        sectionEn: 'Stroke & Distance',
        isRequired: false,
      ),
      ExerciseField(
        key: 'pacePer100m',
        type: ExerciseFieldType.number,
        label: '페이스 (100m당)',
        enLabel: 'Pace (per 100m)',
        unit: '분',
        isCalculated: true,
        section: '페이스 · 효율',
        sectionEn: 'Pace & Efficiency',
      ),
      ExerciseField(
        key: 'maxPacePer100m',
        type: ExerciseFieldType.number,
        label: '최고 페이스 (100m당)',
        enLabel: 'Max Pace (per 100m)',
        unit: '분',
        isRequired: false,
        section: '페이스 · 효율',
        sectionEn: 'Pace & Efficiency',
      ),
      ExerciseField(
        key: 'strokeCountPerLap',
        type: ExerciseFieldType.number,
        label: '25m당 평균 스트로크수',
        enLabel: 'Avg Strokes/25m',
        isRequired: false,
        section: '페이스 · 효율',
        sectionEn: 'Pace & Efficiency',
      ),
      ExerciseField(
        key: 'swolf',
        type: ExerciseFieldType.number,
        label: 'SWOLF (25m 시간+스트로크수)',
        enLabel: 'SWOLF',
        isCalculated: true,
        section: '페이스 · 효율',
        sectionEn: 'Pace & Efficiency',
      ),
      ExerciseField(
        key: 'restTimeTotalMin',
        type: ExerciseFieldType.number,
        label: '쉬는 시간 총합',
        enLabel: 'Total Rest Time',
        unit: '분',
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      ExerciseField(
        key: 'waterTempC',
        type: ExerciseFieldType.number,
        label: '수온',
        enLabel: 'Water Temperature',
        unit: '°C',
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      ExerciseField(
        key: 'calories',
        type: ExerciseFieldType.number,
        label: '칼로리',
        enLabel: 'Calories',
        unit: 'kcal',
        isCalculated: true,
        section: '기타',
        sectionEn: 'Other',
      ),
    ],
  ),

  // 3. 달리기 - 페이스/케이던스/심박수 3대 핵심 지표 (Garmin/COROS/TrainingPeaks 공통 권고)
  ExerciseType(
    id: 'running',
    name: '달리기',
    icon: '🏃',
    isDefault: true,
    sortOrder: 3,
    fields: [
      _distanceKmField(section: '거리 · 페이스', sectionEn: 'Distance & Pace'),
      const ExerciseField(
        key: 'paceMinPerKm',
        type: ExerciseFieldType.number,
        label: '페이스(km당)',
        enLabel: 'Pace (per km)',
        unit: '분',
        isCalculated: true,
        section: '거리 · 페이스',
        sectionEn: 'Distance & Pace',
      ),
      const ExerciseField(
        key: 'maxPaceMinPerKm',
        type: ExerciseFieldType.number,
        label: '최고 페이스(km당)',
        enLabel: 'Max Pace (per km)',
        unit: '분',
        isRequired: false,
        section: '거리 · 페이스',
        sectionEn: 'Distance & Pace',
      ),
      const ExerciseField(
        key: 'cadenceSpm',
        type: ExerciseFieldType.number,
        label: '케이던스',
        enLabel: 'Cadence',
        unit: 'spm(분당 걸음)',
        isRequired: false,
        section: '케이던스 · 보폭',
        sectionEn: 'Cadence & Stride',
      ),
      const ExerciseField(
        key: 'maxCadenceSpm',
        type: ExerciseFieldType.number,
        label: '최고 케이던스',
        enLabel: 'Max Cadence',
        unit: 'spm',
        isRequired: false,
        section: '케이던스 · 보폭',
        sectionEn: 'Cadence & Stride',
      ),
      const ExerciseField(
        key: 'avgStrideCm',
        type: ExerciseFieldType.number,
        label: '평균 보폭',
        enLabel: 'Avg Stride Length',
        unit: 'cm',
        isRequired: false,
        section: '케이던스 · 보폭',
        sectionEn: 'Cadence & Stride',
      ),
      const ExerciseField(
        key: 'runType',
        type: ExerciseFieldType.select,
        label: '러닝 타입',
        enLabel: 'Run Type',
        options: ['일반', '인터벌', '트랙', '언덕', '장거리'],
        optionEnLabels: ['General', 'Interval', 'Track', 'Hill', 'Long Distance'],
        isRequired: false,
        section: '고도 · 기타',
        sectionEn: 'Elevation & Other',
      ),
      _elevationGainField(section: '고도 · 기타', sectionEn: 'Elevation & Other'),
      const ExerciseField(
        key: 'elevationLossM',
        type: ExerciseFieldType.number,
        label: '누적 하강고도',
        enLabel: 'Elevation Loss',
        unit: 'm',
        isRequired: false,
        section: '고도 · 기타',
        sectionEn: 'Elevation & Other',
      ),
      _caloriesField(section: '고도 · 기타', sectionEn: 'Elevation & Other'),
      _courseField(section: '고도 · 기타', sectionEn: 'Elevation & Other'),
    ],
  ),

  // 4. 걷기
  ExerciseType(
    id: 'walking',
    name: '걷기',
    icon: '🚶',
    isDefault: true,
    sortOrder: 4,
    fields: [
      _distanceKmField(section: '거리 · 걸음', sectionEn: 'Distance & Steps'),
      const ExerciseField(
        key: 'steps',
        type: ExerciseFieldType.number,
        label: '걸음수',
        enLabel: 'Steps',
        unit: '보',
        section: '거리 · 걸음',
        sectionEn: 'Distance & Steps',
      ),
      const ExerciseField(
        key: 'paceMinPerKm',
        type: ExerciseFieldType.number,
        label: '페이스(km당)',
        enLabel: 'Pace (per km)',
        unit: '분',
        isCalculated: true,
        section: '거리 · 걸음',
        sectionEn: 'Distance & Steps',
      ),
      const ExerciseField(
        key: 'maxPaceMinPerKm',
        type: ExerciseFieldType.number,
        label: '최고 페이스(km당)',
        enLabel: 'Max Pace (per km)',
        unit: '분',
        isRequired: false,
        section: '거리 · 걸음',
        sectionEn: 'Distance & Steps',
      ),
      const ExerciseField(
        key: 'avgStrideM',
        type: ExerciseFieldType.number,
        label: '평균 보폭',
        enLabel: 'Avg Stride Length',
        unit: 'm',
        isRequired: false,
        section: '보행 패턴',
        sectionEn: 'Gait Pattern',
      ),
      const ExerciseField(
        key: 'cadenceSpm',
        type: ExerciseFieldType.number,
        label: '케이던스',
        enLabel: 'Cadence',
        unit: 'spm',
        isRequired: false,
        section: '보행 패턴',
        sectionEn: 'Gait Pattern',
      ),
      const ExerciseField(
        key: 'walkType',
        type: ExerciseFieldType.select,
        label: '걷기 타입',
        enLabel: 'Walk Type',
        options: ['산책', '도보', '계단', '러닝워크'],
        optionEnLabels: ['Stroll', 'Walk', 'Stairs', 'Power Walk'],
        isRequired: false,
        section: '보행 패턴',
        sectionEn: 'Gait Pattern',
      ),
      const ExerciseField(
        key: 'elevationChangeM',
        type: ExerciseFieldType.number,
        label: '고도 변화',
        enLabel: 'Elevation Change',
        unit: 'm',
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      const ExerciseField(
        key: 'restCount',
        type: ExerciseFieldType.counter,
        label: '휴식 횟수',
        enLabel: 'Rest Count',
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      _caloriesField(section: '기타', sectionEn: 'Other'),
    ],
  ),

  // 5. 헬스 - 볼륨(세트x횟수x중량)과 세트별 RPE가 표준 진행상황 추적 지표
  ExerciseType(
    id: 'gym',
    name: '헬스',
    icon: '🏋️',
    isDefault: true,
    sortOrder: 5,
    fields: const [
      ExerciseField(
        key: 'bodyPart',
        type: ExerciseFieldType.multiSelect,
        label: '운동 부위',
        enLabel: 'Body Part',
        options: ['가슴', '등', '하체', '어깨', '팔', '복근', '전신'],
        optionEnLabels: ['Chest', 'Back', 'Legs', 'Shoulders', 'Arms', 'Abs', 'Full Body'],
        section: '종목 정보',
        sectionEn: 'Exercise Info',
      ),
      ExerciseField(
        key: 'exerciseName',
        type: ExerciseFieldType.text,
        label: '종목명',
        enLabel: 'Exercise Name',
        section: '종목 정보',
        sectionEn: 'Exercise Info',
      ),
      ExerciseField(
        key: 'equipment',
        type: ExerciseFieldType.select,
        label: '사용 장비',
        enLabel: 'Equipment',
        options: ['바벨', '덤벨', '머신', '케이블', '맨몸', '케틀벨', '이지바', '트랩바', '체스트프레스/숄더프레스', '케이블 크로스오버'],
        optionEnLabels: ['Barbell', 'Dumbbell', 'Machine', 'Cable', 'Bodyweight', 'Kettlebell', 'EZ-Bar', 'Trap Bar', 'Chest Press/Shoulder Press', 'Cable Crossover'],
        isRequired: false,
        section: '종목 정보',
        sectionEn: 'Exercise Info',
      ),
      ExerciseField(
        key: 'sets',
        type: ExerciseFieldType.multiSet,
        label: '세트 (중량x횟수, 세트별 RPE 포함)',
        enLabel: 'Sets (Weight x Reps, RPE)',
        section: '세트 기록',
        sectionEn: 'Set Log',
      ),
      ExerciseField(
        // ✅ [2026-09-14 추가] 계획만 하고 누락됐던 항목
        key: 'totalSets',
        type: ExerciseFieldType.number,
        label: '총 세트 수',
        enLabel: 'Total Sets',
        isCalculated: true,
        section: '세트 기록',
        sectionEn: 'Set Log',
      ),
      ExerciseField(
        key: 'restBetweenSetsSec',
        type: ExerciseFieldType.number,
        label: '세트 간 쉬는 시간',
        enLabel: 'Rest Between Sets',
        unit: '초',
        isRequired: false,
        section: '세트 기록',
        sectionEn: 'Set Log',
      ),
      ExerciseField(
        key: 'rir',
        type: ExerciseFieldType.counter,
        label: 'RIR (여유 횟수)',
        enLabel: 'RIR (Reps in Reserve)',
        isRequired: false,
        section: '세트 기록',
        sectionEn: 'Set Log',
      ),
      ExerciseField(
        key: 'tempo',
        type: ExerciseFieldType.text,
        label: '템포 표기',
        enLabel: 'Tempo',
        isRequired: false,
        section: '세트 기록',
        sectionEn: 'Set Log',
      ),
      ExerciseField(
        key: 'toFailure',
        type: ExerciseFieldType.select,
        label: '실패세트 여부',
        enLabel: 'To Failure',
        options: ['예', '아니오'],
        optionEnLabels: ['Yes', 'No'],
        isRequired: false,
        section: '세트 기록',
        sectionEn: 'Set Log',
      ),
      ExerciseField(
        key: 'volumeLoad',
        type: ExerciseFieldType.number,
        label: '총 볼륨 (중량x횟수 합)',
        enLabel: 'Total Volume',
        unit: 'kg',
        isCalculated: true,
        section: '볼륨 · 1RM',
        sectionEn: 'Volume & 1RM',
      ),
      ExerciseField(
        key: 'estimated1rm',
        type: ExerciseFieldType.number,
        label: '추정 1RM (Epley 공식)',
        enLabel: 'Estimated 1RM',
        unit: 'kg',
        isCalculated: true,
        section: '볼륨 · 1RM',
        sectionEn: 'Volume & 1RM',
      ),
    ],
  ),

  // 6. 필라테스
  ExerciseType(
    id: 'pilates',
    name: '필라테스',
    icon: '🧘',
    isDefault: true,
    sortOrder: 6,
    fields: [
      ExerciseField(
        key: 'programName',
        type: ExerciseFieldType.text,
        label: '프로그램명',
        enLabel: 'Program',
        section: '프로그램',
        sectionEn: 'Program',
      ),
      ExerciseField(
        key: 'equipment',
        type: ExerciseFieldType.select,
        label: '기구 유형',
        enLabel: 'Equipment',
        options: ['매트', '리포머', '캐딜락', '기타'],
        optionEnLabels: ['Mat', 'Reformer', 'Cadillac', 'Other'],
        isRequired: false,
        section: '프로그램',
        sectionEn: 'Program',
      ),
      ExerciseField(
        key: 'focusArea',
        type: ExerciseFieldType.select,
        label: '집중 부위',
        enLabel: 'Focus Area',
        options: ['코어', '전신', '유연성', '자세교정', '재활'],
        optionEnLabels: ['Core', 'Full Body', 'Flexibility', 'Posture Correction', 'Rehab'],
        isRequired: false,
        section: '프로그램',
        sectionEn: 'Program',
      ),
      ExerciseField(
        key: 'difficulty',
        type: ExerciseFieldType.select,
        label: '난이도',
        enLabel: 'Difficulty',
        options: ['초급', '중급', '고급'],
        optionEnLabels: ['Beginner', 'Intermediate', 'Advanced'],
        section: '프로그램',
        sectionEn: 'Program',
      ),
      ExerciseField(
        key: 'instructor',
        type: ExerciseFieldType.text,
        label: '강사',
        enLabel: 'Instructor',
        isRequired: false,
        section: '프로그램',
        sectionEn: 'Program',
      ),
      // ✅ [2026-09-14 신규]
      ExerciseField(
        key: 'totalMoves',
        type: ExerciseFieldType.number,
        label: '총 동작 수',
        enLabel: 'Total Moves',
        isRequired: false,
        section: '동작 · 자가평가',
        sectionEn: 'Moves & Self-Rating',
      ),
      ExerciseField(
        key: 'coreHoldTimeSec',
        type: ExerciseFieldType.number,
        label: '코어 유지 시간 총합',
        enLabel: 'Core Hold Time',
        unit: '초',
        isRequired: false,
        section: '동작 · 자가평가',
        sectionEn: 'Moves & Self-Rating',
      ),
      ExerciseField(
        key: 'toolsUsed',
        type: ExerciseFieldType.multiSelect,
        label: '사용 도구',
        enLabel: 'Tools Used',
        options: ['링', '볼', '밴드', '볼스터', '롤러'],
        optionEnLabels: ['Ring', 'Ball', 'Band', 'Bolster', 'Roller'],
        isRequired: false,
        section: '동작 · 자가평가',
        sectionEn: 'Moves & Self-Rating',
      ),
      // ✅ [2026-09-14 추가] 자가평가 3항목
      ExerciseField(
        key: 'breathScore',
        type: ExerciseFieldType.counter,
        label: '호흡 정확도 자가 점수 (1~10)',
        enLabel: 'Breath Accuracy Score (1-10)',
        isRequired: false,
        section: '동작 · 자가평가',
        sectionEn: 'Moves & Self-Rating',
      ),
      ExerciseField(
        key: 'balanceScore',
        type: ExerciseFieldType.counter,
        label: '균형 자가 점수 (1~10)',
        enLabel: 'Balance Score (1-10)',
        isRequired: false,
        section: '동작 · 자가평가',
        sectionEn: 'Moves & Self-Rating',
      ),
      ExerciseField(
        key: 'flexibilityScore',
        type: ExerciseFieldType.counter,
        label: '유연성 자가 점수 (1~10)',
        enLabel: 'Flexibility Score (1-10)',
        isRequired: false,
        section: '동작 · 자가평가',
        sectionEn: 'Moves & Self-Rating',
      ),
      _caloriesField(section: '기타', sectionEn: 'Other'),
    ],
  ),

  // 7. 요가
  ExerciseType(
    id: 'yoga',
    name: '요가',
    icon: '🧘',
    isDefault: true,
    sortOrder: 7,
    fields: [
      ExerciseField(
        key: 'style',
        type: ExerciseFieldType.multiSelect,
        label: '유형',
        enLabel: 'Style',
        options: ['하타', '빈야사', '아쉬탕가', '인요가', '기타'],
        optionEnLabels: ['Hatha', 'Vinyasa', 'Ashtanga', 'Yin Yoga', 'Other'],
        isRequired: false,
        section: '스타일 · 프로그램',
        sectionEn: 'Style & Program',
      ),
      ExerciseField(
        key: 'programName',
        type: ExerciseFieldType.text,
        label: '프로그램명',
        enLabel: 'Program',
        section: '스타일 · 프로그램',
        sectionEn: 'Style & Program',
      ),
      ExerciseField(
        key: 'focusArea',
        type: ExerciseFieldType.select,
        label: '집중 부위',
        enLabel: 'Focus Area',
        options: ['코어', '전신', '유연성', '균형', '이완/명상'],
        optionEnLabels: ['Core', 'Full Body', 'Flexibility', 'Balance', 'Relaxation/Meditation'],
        isRequired: false,
        section: '스타일 · 프로그램',
        sectionEn: 'Style & Program',
      ),
      ExerciseField(
        key: 'difficulty',
        type: ExerciseFieldType.select,
        label: '난이도',
        enLabel: 'Difficulty',
        options: ['초급', '중급', '고급'],
        optionEnLabels: ['Beginner', 'Intermediate', 'Advanced'],
        section: '스타일 · 프로그램',
        sectionEn: 'Style & Program',
      ),
      // ✅ [2026-09-14 신규]
      ExerciseField(
        key: 'asanaCount',
        type: ExerciseFieldType.number,
        label: '수행 동작(아사나) 수',
        enLabel: 'Asana Count',
        isRequired: false,
        section: '수련 구성',
        sectionEn: 'Practice Breakdown',
      ),
      ExerciseField(
        key: 'meditationTimeMin',
        type: ExerciseFieldType.number,
        label: '명상 시간',
        enLabel: 'Meditation Time',
        unit: '분',
        isRequired: false,
        section: '수련 구성',
        sectionEn: 'Practice Breakdown',
      ),
      ExerciseField(
        key: 'breathingTimeMin',
        type: ExerciseFieldType.number,
        label: '호흡(프라나야마) 시간',
        enLabel: 'Breathing Practice Time',
        unit: '분',
        isRequired: false,
        section: '수련 구성',
        sectionEn: 'Practice Breakdown',
      ),
      ExerciseField(
        key: 'balanceHoldTimeSec',
        type: ExerciseFieldType.number,
        label: '균형 유지 시간 총합',
        enLabel: 'Balance Hold Time',
        unit: '초',
        isRequired: false,
        section: '수련 구성',
        sectionEn: 'Practice Breakdown',
      ),
      // ✅ [2026-09-14 추가] 4항목
      ExerciseField(
        key: 'challengePoseCount',
        type: ExerciseFieldType.counter,
        label: '어려운(챌린지) 동작 수',
        enLabel: 'Challenge Pose Count',
        isRequired: false,
        section: '수련 구성',
        sectionEn: 'Practice Breakdown',
      ),
      ExerciseField(
        key: 'inversionCount',
        type: ExerciseFieldType.counter,
        label: '인버션(거꾸로) 동작 수',
        enLabel: 'Inversion Count',
        isRequired: false,
        section: '수련 구성',
        sectionEn: 'Practice Breakdown',
      ),
      ExerciseField(
        key: 'flexibilityScore',
        type: ExerciseFieldType.counter,
        label: '유연성 자가 점수 (1~10)',
        enLabel: 'Flexibility Score (1-10)',
        isRequired: false,
        section: '자가 평가',
        sectionEn: 'Self-Rating',
      ),
      ExerciseField(
        key: 'meditationDepthScore',
        type: ExerciseFieldType.counter,
        label: '명상 깊이 자가 점수 (1~10)',
        enLabel: 'Meditation Depth Score (1-10)',
        isRequired: false,
        section: '자가 평가',
        sectionEn: 'Self-Rating',
      ),
      _caloriesField(section: '기타', sectionEn: 'Other'),
    ],
  ),

  // 8. 등산 - 거리보다 누적 상승/하강 고도가 체력 소모를 더 잘 설명 (Strava/트레일 표준)
  ExerciseType(
    id: 'hiking',
    name: '등산',
    icon: '🥾',
    isDefault: true,
    sortOrder: 8,
    fields: [
      _courseField(label: '산/코스명', enLabel: 'Mountain/Course Name', section: '코스 정보', sectionEn: 'Course Info'),
      _distanceKmField(section: '코스 정보', sectionEn: 'Course Info'),
      const ExerciseField(
        key: 'difficulty',
        type: ExerciseFieldType.select,
        label: '난이도',
        enLabel: 'Difficulty',
        options: ['쉬움', '보통', '어려움'],
        optionEnLabels: ['Easy', 'Normal', 'Hard'],
        isRequired: false,
        section: '코스 정보',
        sectionEn: 'Course Info',
      ),
      _elevationGainField(section: '고도', sectionEn: 'Elevation'),
      const ExerciseField(
        key: 'elevationLossM',
        type: ExerciseFieldType.number,
        label: '누적 하강고도',
        enLabel: 'Elevation Loss',
        unit: 'm',
        isRequired: false,
        section: '고도',
        sectionEn: 'Elevation',
      ),
      const ExerciseField(
        key: 'peakAltitudeM',
        type: ExerciseFieldType.number,
        label: '최고점 해발',
        enLabel: 'Peak Altitude',
        unit: 'm',
        isRequired: false,
        section: '고도',
        sectionEn: 'Elevation',
      ),
      const ExerciseField(
        key: 'movementAid',
        type: ExerciseFieldType.select,
        label: '이동 방식',
        enLabel: 'Movement Aid',
        options: ['도보', '트레킹폴', '등산스틱', '없음'],
        optionEnLabels: ['On Foot', 'Trekking Poles', 'Hiking Sticks', 'None'],
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      // ✅ [2026-09-14 추가] 3항목
      const ExerciseField(
        key: 'ascentPaceMinPerKm',
        type: ExerciseFieldType.number,
        label: '평균 페이스(상행)',
        enLabel: 'Avg Pace (Ascent)',
        unit: '분/km',
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      const ExerciseField(
        key: 'restCount',
        type: ExerciseFieldType.counter,
        label: '휴식 횟수',
        enLabel: 'Rest Count',
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      const ExerciseField(
        key: 'restTimeTotalMin',
        type: ExerciseFieldType.number,
        label: '휴식 시간 총합',
        enLabel: 'Total Rest Time',
        unit: '분',
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      _caloriesField(section: '기타', sectionEn: 'Other'),
    ],
  ),

  // 9. 자전거 - 평균/최고속도, 케이던스, 파워가 표준 지표 (Strava/사이클링 파워미터 관행)
  ExerciseType(
    id: 'cycling',
    name: '자전거',
    icon: '🚴',
    isDefault: true,
    sortOrder: 9,
    fields: [
      _distanceKmField(section: '거리 · 속도', sectionEn: 'Distance & Speed'),
      const ExerciseField(
        key: 'avgSpeedKmh',
        type: ExerciseFieldType.number,
        label: '평균속도',
        enLabel: 'Avg Speed',
        unit: 'km/h',
        isCalculated: true,
        section: '거리 · 속도',
        sectionEn: 'Distance & Speed',
      ),
      const ExerciseField(
        key: 'maxSpeedKmh',
        type: ExerciseFieldType.number,
        label: '최고속도',
        enLabel: 'Max Speed',
        unit: 'km/h',
        isRequired: false,
        section: '거리 · 속도',
        sectionEn: 'Distance & Speed',
      ),
      const ExerciseField(
        key: 'avgCadenceRpm',
        type: ExerciseFieldType.number,
        label: '평균 케이던스',
        enLabel: 'Avg Cadence',
        unit: 'rpm',
        isRequired: false,
        section: '케이던스 · 파워',
        sectionEn: 'Cadence & Power',
      ),
      // ✅ [2026-09-14 추가]
      const ExerciseField(
        key: 'maxCadenceRpm',
        type: ExerciseFieldType.number,
        label: '최고 케이던스',
        enLabel: 'Max Cadence',
        unit: 'rpm',
        isRequired: false,
        section: '케이던스 · 파워',
        sectionEn: 'Cadence & Power',
      ),
      const ExerciseField(
        key: 'avgPowerWatts',
        type: ExerciseFieldType.number,
        label: '평균 파워',
        enLabel: 'Avg Power',
        unit: 'W',
        isRequired: false,
        section: '케이던스 · 파워',
        sectionEn: 'Cadence & Power',
      ),
      const ExerciseField(
        key: 'maxPowerWatts',
        type: ExerciseFieldType.number,
        label: '최고 파워',
        enLabel: 'Max Power',
        unit: 'W',
        isRequired: false,
        section: '케이던스 · 파워',
        sectionEn: 'Cadence & Power',
      ),
      _elevationGainField(section: '기타', sectionEn: 'Other'),
      const ExerciseField(
        key: 'bikeType',
        type: ExerciseFieldType.select,
        label: '자전거 종류',
        enLabel: 'Bike Type',
        options: ['로드', 'MTB', '픽시', '하이브리드', 'eBike'],
        optionEnLabels: ['Road', 'MTB', 'Fixie', 'Hybrid', 'eBike'],
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      const ExerciseField(
        key: 'rideType',
        type: ExerciseFieldType.select,
        label: '라이딩 타입',
        enLabel: 'Ride Type',
        options: ['일반', '인터벌', '내리막', '힐클라임'],
        optionEnLabels: ['General', 'Interval', 'Downhill', 'Hill Climb'],
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      const ExerciseField(
        key: 'routeType',
        type: ExerciseFieldType.select,
        label: '경로 타입',
        enLabel: 'Route Type',
        options: ['도로', '오프로드', '혼합'],
        optionEnLabels: ['Road', 'Off-Road', 'Mixed'],
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      _caloriesField(section: '기타', sectionEn: 'Other'),
    ],
  ),

  // ✅ [2026-09-14 개편] 예전엔 테니스/배드민턴/탁구가 _racketSportFields(),
  // 농구/축구가 _teamSportFields()라는 "공용 틀"을 같이 써서, 종목마다 고유한
  // 스프레드시트 항목(예: 테니스 서브 에이스, 농구 2점/3점슛 등)이 대부분
  // 빠져 있었다. 5종목을 완전히 분리해서 각자 전용 필드로 다시 만들었다.

  // 10. 테니스
  ExerciseType(
    id: 'tennis',
    name: '테니스',
    icon: '🎾',
    isDefault: true,
    sortOrder: 10,
    fields: const [
      ExerciseField(
        key: 'setCount',
        type: ExerciseFieldType.number,
        label: '세트 수',
        enLabel: 'Sets',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'gamesWon',
        type: ExerciseFieldType.number,
        label: '본인 게임 수 합계',
        enLabel: 'Games Won',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'opponentType',
        type: ExerciseFieldType.select,
        label: '상대 유형',
        enLabel: 'Opponent Type',
        options: ['단식', '복식', '훈련', '친선'],
        optionEnLabels: ['Singles', 'Doubles', 'Practice', 'Friendly'],
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'aces',
        type: ExerciseFieldType.counter,
        label: '서브 에이스',
        enLabel: 'Aces',
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'doubleFaults',
        type: ExerciseFieldType.counter,
        label: '더블폴트',
        enLabel: 'Double Faults',
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'serveAttempts',
        type: ExerciseFieldType.number,
        label: '서브 시도 횟수',
        enLabel: 'Serve Attempts',
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'firstServePct',
        type: ExerciseFieldType.number,
        label: '1st Serve 성공률',
        enLabel: '1st Serve %',
        unit: '%',
        isCalculated: true,
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'firstServePointsPct',
        type: ExerciseFieldType.number,
        label: '1st Serve 포인트 성공률',
        enLabel: '1st Serve Points %',
        unit: '%',
        isRequired: false,
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'maxServeSpeedKmh',
        type: ExerciseFieldType.number,
        label: '서브 최고속도',
        enLabel: 'Max Serve Speed',
        unit: 'km/h',
        isRequired: false,
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'winners',
        type: ExerciseFieldType.number,
        label: '위너(득점타)',
        enLabel: 'Winners',
        section: '랠리',
        sectionEn: 'Rally',
      ),
      ExerciseField(
        key: 'unforcedErrors',
        type: ExerciseFieldType.number,
        label: '언포스드 에러',
        enLabel: 'Unforced Errors',
        section: '랠리',
        sectionEn: 'Rally',
      ),
      ExerciseField(
        key: 'avgRallyLength',
        type: ExerciseFieldType.number,
        label: '랠리 평균 길이',
        enLabel: 'Avg Rally Length',
        unit: 'shot',
        isRequired: false,
        section: '랠리',
        sectionEn: 'Rally',
      ),
    ],
  ),

  // 11. 배드민턴
  ExerciseType(
    id: 'badminton',
    name: '배드민턴',
    icon: '🏸',
    isDefault: true,
    sortOrder: 11,
    fields: const [
      ExerciseField(
        key: 'matchCount',
        type: ExerciseFieldType.number,
        label: '경기 수',
        enLabel: 'Matches',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'shuttleType',
        type: ExerciseFieldType.select,
        label: '셔틀콕 종류',
        enLabel: 'Shuttle Type',
        options: ['깃털', '플라스틱', '연습용'],
        optionEnLabels: ['Feather', 'Plastic', 'Practice'],
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'shuttleUsed',
        type: ExerciseFieldType.number,
        label: '셔틀콕 사용량',
        enLabel: 'Shuttles Used',
        unit: '개',
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'totalScore',
        type: ExerciseFieldType.number,
        label: '본 게임 점수 합계',
        enLabel: 'Total Score',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'smashAttempts',
        type: ExerciseFieldType.number,
        label: '스매시 시도 수',
        enLabel: 'Smash Attempts',
        section: '스매시 · 드롭샷',
        sectionEn: 'Smash & Drop Shot',
      ),
      ExerciseField(
        key: 'smashSuccessRate',
        type: ExerciseFieldType.number,
        label: '스매시 성공률',
        enLabel: 'Smash Success Rate',
        unit: '%',
        section: '스매시 · 드롭샷',
        sectionEn: 'Smash & Drop Shot',
      ),
      ExerciseField(
        key: 'dropShotSuccessRate',
        type: ExerciseFieldType.number,
        label: '드롭샷 성공률',
        enLabel: 'Drop Shot Success Rate',
        unit: '%',
        isRequired: false,
        section: '스매시 · 드롭샷',
        sectionEn: 'Smash & Drop Shot',
      ),
      ExerciseField(
        key: 'avgRallyLength',
        type: ExerciseFieldType.number,
        label: '평균 래리 길이',
        enLabel: 'Avg Rally Length',
        unit: 'shot',
        isRequired: false,
        section: '이동 · 장비',
        sectionEn: 'Movement & Gear',
      ),
      ExerciseField(
        key: 'distanceKm',
        type: ExerciseFieldType.number,
        label: '이동 거리',
        enLabel: 'Distance',
        unit: 'km',
        isRequired: false,
        section: '이동 · 장비',
        sectionEn: 'Movement & Gear',
      ),
      ExerciseField(
        key: 'racketWeightG',
        type: ExerciseFieldType.number,
        label: '라켓 무게',
        enLabel: 'Racket Weight',
        unit: 'g',
        isRequired: false,
        section: '이동 · 장비',
        sectionEn: 'Movement & Gear',
      ),
    ],
  ),

  // 12. 탁구
  ExerciseType(
    id: 'tabletennis',
    name: '탁구',
    icon: '🏓',
    isDefault: true,
    sortOrder: 12,
    fields: const [
      ExerciseField(
        key: 'setCount',
        type: ExerciseFieldType.number,
        label: '세트 수',
        enLabel: 'Sets',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'totalScore',
        type: ExerciseFieldType.number,
        label: '본인 점수 합계',
        enLabel: 'Total Score',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'opponentType',
        type: ExerciseFieldType.select,
        label: '상대 유형',
        enLabel: 'Opponent Type',
        options: ['단식', '복식', '훈련', '친선'],
        optionEnLabels: ['Singles', 'Doubles', 'Practice', 'Friendly'],
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'serveSpinType',
        type: ExerciseFieldType.select,
        label: '서브 회전 종류',
        enLabel: 'Serve Spin Type',
        options: ['톱스핀', '백스핀', '노스핀', '횡회전', '리프트'],
        optionEnLabels: ['Topspin', 'Backspin', 'No Spin', 'Sidespin', 'Lift'],
        isRequired: false,
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'serveAttempts',
        type: ExerciseFieldType.number,
        label: '서브 시도 수',
        enLabel: 'Serve Attempts',
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'serveSuccessRate',
        type: ExerciseFieldType.number,
        label: '서브 성공률',
        enLabel: 'Serve Success Rate',
        unit: '%',
        isCalculated: true,
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'attackAttempts',
        type: ExerciseFieldType.number,
        label: '공격(스매시) 시도 수',
        enLabel: 'Attack Attempts',
        section: '공격',
        sectionEn: 'Attack',
      ),
      ExerciseField(
        key: 'attackSuccessRate',
        type: ExerciseFieldType.number,
        label: '공격(스매시) 성공률',
        enLabel: 'Attack Success Rate',
        unit: '%',
        section: '공격',
        sectionEn: 'Attack',
      ),
      ExerciseField(
        key: 'forehandWinners',
        type: ExerciseFieldType.number,
        label: '포핸드 위너 수',
        enLabel: 'Forehand Winners',
        isRequired: false,
        section: '공격',
        sectionEn: 'Attack',
      ),
      ExerciseField(
        key: 'backhandWinners',
        type: ExerciseFieldType.number,
        label: '백핸드 위너 수',
        enLabel: 'Backhand Winners',
        isRequired: false,
        section: '공격',
        sectionEn: 'Attack',
      ),
      ExerciseField(
        key: 'avgRallyLength',
        type: ExerciseFieldType.number,
        label: '랠리 평균 길이',
        enLabel: 'Avg Rally Length',
        unit: 'shot',
        isRequired: false,
        section: '공격',
        sectionEn: 'Attack',
      ),
    ],
  ),

  // 13. 농구
  ExerciseType(
    id: 'basketball',
    name: '농구',
    icon: '🏀',
    isDefault: true,
    sortOrder: 13,
    fields: const [
      ExerciseField(
        key: 'position',
        type: ExerciseFieldType.text,
        label: '포지션',
        enLabel: 'Position',
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'gameDurationMin',
        type: ExerciseFieldType.number,
        label: '경기 시간',
        enLabel: 'Game Duration',
        unit: '분',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'distanceKm',
        type: ExerciseFieldType.number,
        label: '이동 거리',
        enLabel: 'Distance',
        unit: 'km',
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'points',
        type: ExerciseFieldType.number,
        label: '득점',
        enLabel: 'Points',
        section: '슈팅',
        sectionEn: 'Shooting',
      ),
      ExerciseField(
        key: 'fg2Made',
        type: ExerciseFieldType.number,
        label: '2점슛 성공',
        enLabel: '2-Pt Made',
        isRequired: false,
        section: '슈팅',
        sectionEn: 'Shooting',
      ),
      ExerciseField(
        key: 'fg2Attempted',
        type: ExerciseFieldType.number,
        label: '2점슛 시도',
        enLabel: '2-Pt Attempted',
        isRequired: false,
        section: '슈팅',
        sectionEn: 'Shooting',
      ),
      ExerciseField(
        key: 'fg3Made',
        type: ExerciseFieldType.number,
        label: '3점슛 성공',
        enLabel: '3-Pt Made',
        isRequired: false,
        section: '슈팅',
        sectionEn: 'Shooting',
      ),
      ExerciseField(
        key: 'fg3Attempted',
        type: ExerciseFieldType.number,
        label: '3점슛 시도',
        enLabel: '3-Pt Attempted',
        isRequired: false,
        section: '슈팅',
        sectionEn: 'Shooting',
      ),
      ExerciseField(
        key: 'ftMade',
        type: ExerciseFieldType.number,
        label: '자유투 성공',
        enLabel: 'FT Made',
        isRequired: false,
        section: '슈팅',
        sectionEn: 'Shooting',
      ),
      ExerciseField(
        key: 'ftAttempted',
        type: ExerciseFieldType.number,
        label: '자유투 시도',
        enLabel: 'FT Attempted',
        isRequired: false,
        section: '슈팅',
        sectionEn: 'Shooting',
      ),
      ExerciseField(
        key: 'assists',
        type: ExerciseFieldType.number,
        label: '어시스트',
        enLabel: 'Assists',
        section: '수비 · 기타',
        sectionEn: 'Defense & Other',
      ),
      ExerciseField(
        key: 'reboundsOff',
        type: ExerciseFieldType.counter,
        label: '공격 리바운드',
        enLabel: 'Off. Rebounds',
        isRequired: false,
        section: '수비 · 기타',
        sectionEn: 'Defense & Other',
      ),
      ExerciseField(
        key: 'reboundsDef',
        type: ExerciseFieldType.counter,
        label: '수비 리바운드',
        enLabel: 'Def. Rebounds',
        isRequired: false,
        section: '수비 · 기타',
        sectionEn: 'Defense & Other',
      ),
      ExerciseField(
        key: 'fouls',
        type: ExerciseFieldType.counter,
        label: '파울 수',
        enLabel: 'Fouls',
        isRequired: false,
        section: '수비 · 기타',
        sectionEn: 'Defense & Other',
      ),
    ],
  ),

  // 14. 축구
  ExerciseType(
    id: 'soccer',
    name: '축구',
    icon: '⚽',
    isDefault: true,
    sortOrder: 14,
    fields: const [
      ExerciseField(
        key: 'position',
        type: ExerciseFieldType.select,
        label: '포지션',
        enLabel: 'Position',
        options: ['GK', 'DF', 'MF', 'FW'],
        optionEnLabels: ['GK', 'DF', 'MF', 'FW'],
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'gameDurationMin',
        type: ExerciseFieldType.number,
        label: '경기 시간',
        enLabel: 'Game Duration',
        unit: '분',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'distanceKm',
        type: ExerciseFieldType.number,
        label: '운동 거리',
        enLabel: 'Distance',
        unit: 'km',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'maxSpeedKmh',
        type: ExerciseFieldType.number,
        label: '최다 속도',
        enLabel: 'Max Speed',
        unit: 'km/h',
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'sprintCount',
        type: ExerciseFieldType.number,
        label: '스프린트 수',
        enLabel: 'Sprint Count',
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'passAttempts',
        type: ExerciseFieldType.number,
        label: '패스 시도 수',
        enLabel: 'Pass Attempts',
        section: '패스',
        sectionEn: 'Passing',
      ),
      ExerciseField(
        key: 'passSuccess',
        type: ExerciseFieldType.number,
        label: '패스 성공 수',
        enLabel: 'Passes Completed',
        section: '패스',
        sectionEn: 'Passing',
      ),
      ExerciseField(
        key: 'passSuccessRate',
        type: ExerciseFieldType.number,
        label: '패스 성공률',
        enLabel: 'Pass Success Rate',
        unit: '%',
        isCalculated: true,
        section: '패스',
        sectionEn: 'Passing',
      ),
      ExerciseField(
        key: 'shots',
        type: ExerciseFieldType.number,
        label: '슈팅 수',
        enLabel: 'Shots',
        section: '득점 · 수비',
        sectionEn: 'Scoring & Defense',
      ),
      ExerciseField(
        key: 'shotsOnTarget',
        type: ExerciseFieldType.number,
        label: '유효 슈팅(온타깃)',
        enLabel: 'Shots on Target',
        section: '득점 · 수비',
        sectionEn: 'Scoring & Defense',
      ),
      ExerciseField(
        key: 'goals',
        type: ExerciseFieldType.counter,
        label: '골',
        enLabel: 'Goals',
        section: '득점 · 수비',
        sectionEn: 'Scoring & Defense',
      ),
      ExerciseField(
        key: 'assists',
        type: ExerciseFieldType.counter,
        label: '어시스트',
        enLabel: 'Assists',
        section: '득점 · 수비',
        sectionEn: 'Scoring & Defense',
      ),
      ExerciseField(
        key: 'tackleSuccessRate',
        type: ExerciseFieldType.number,
        label: '태클 성공률',
        enLabel: 'Tackle Success Rate',
        unit: '%',
        isRequired: false,
        section: '득점 · 수비',
        sectionEn: 'Scoring & Defense',
      ),
    ],
  ),

  // 15. 스키
  ExerciseType(
    id: 'skiing',
    name: '스키',
    icon: '⛷️',
    isDefault: true,
    sortOrder: 15,
    fields: [
      ExerciseField(
        key: 'resort',
        type: ExerciseFieldType.text,
        label: '스키장명',
        enLabel: 'Resort Name',
        isRequired: false,
        section: '장비 · 코스',
        sectionEn: 'Equipment & Course',
      ),
      // ✅ [2026-09-14 추가] 장비/슬로프 종류
      ExerciseField(
        key: 'equipmentType',
        type: ExerciseFieldType.select,
        label: '사용 장비',
        enLabel: 'Equipment',
        options: ['스키', '스노보드'],
        optionEnLabels: ['Ski', 'Snowboard'],
        section: '장비 · 코스',
        sectionEn: 'Equipment & Course',
      ),
      ExerciseField(
        key: 'slopeType',
        type: ExerciseFieldType.select,
        label: '슬로프 종류',
        enLabel: 'Slope Type',
        options: ['알파인', '크로스컨트리', '프리스타일', '백컨트리'],
        optionEnLabels: ['Alpine', 'Cross-Country', 'Freestyle', 'Backcountry'],
        isRequired: false,
        section: '장비 · 코스',
        sectionEn: 'Equipment & Course',
      ),
      ExerciseField(
        key: 'slopeDifficulty',
        type: ExerciseFieldType.select,
        label: '슬로프 난이도',
        enLabel: 'Slope Difficulty',
        options: ['초급', '중급', '상급'],
        optionEnLabels: ['Beginner', 'Intermediate', 'Advanced'],
        section: '장비 · 코스',
        sectionEn: 'Equipment & Course',
      ),
      ExerciseField(
        key: 'weatherSnow',
        type: ExerciseFieldType.select,
        label: '눈/날씨',
        enLabel: 'Snow Condition',
        options: ['파우더', '습설', '인공', '아이스'],
        optionEnLabels: ['Powder', 'Wet Snow', 'Artificial', 'Ice'],
        isRequired: false,
        section: '장비 · 코스',
        sectionEn: 'Equipment & Course',
      ),
      ExerciseField(
        key: 'runCount',
        type: ExerciseFieldType.counter,
        label: '활강 횟수',
        enLabel: 'Run Count',
        section: '활강 기록',
        sectionEn: 'Run Log',
      ),
      ExerciseField(
        key: 'totalDistanceKm',
        type: ExerciseFieldType.number,
        label: '총 활강거리',
        enLabel: 'Total Distance',
        unit: 'km',
        isRequired: false,
        section: '활강 기록',
        sectionEn: 'Run Log',
      ),
      // ✅ [2026-09-14 추가] 고도/속도/리프트
      ExerciseField(
        key: 'totalDescentM',
        type: ExerciseFieldType.number,
        label: '총 고도 강하',
        enLabel: 'Total Descent',
        unit: 'm',
        isRequired: false,
        section: '활강 기록',
        sectionEn: 'Run Log',
      ),
      ExerciseField(
        key: 'liftAscentM',
        type: ExerciseFieldType.number,
        label: '총 고도 상승(리프트)',
        enLabel: 'Lift Ascent',
        unit: 'm',
        isRequired: false,
        section: '활강 기록',
        sectionEn: 'Run Log',
      ),
      ExerciseField(
        key: 'avgSpeedKmh',
        type: ExerciseFieldType.number,
        label: '평균속도',
        enLabel: 'Avg Speed',
        unit: 'km/h',
        isRequired: false,
        section: '활강 기록',
        sectionEn: 'Run Log',
      ),
      ExerciseField(
        key: 'maxSpeedKmh',
        type: ExerciseFieldType.number,
        label: '최고속도',
        enLabel: 'Max Speed',
        unit: 'km/h',
        isRequired: false,
        section: '활강 기록',
        sectionEn: 'Run Log',
      ),
      ExerciseField(
        key: 'liftCount',
        type: ExerciseFieldType.counter,
        label: '리프트/곤돌라 이용 횟수',
        enLabel: 'Lift Rides',
        isRequired: false,
        section: '활강 기록',
        sectionEn: 'Run Log',
      ),
      _caloriesField(section: '기타', sectionEn: 'Other'),
    ],
  ),

  // 16. 기타 - 커스텀 종목을 만들기 전 임시 범용 기록용
  ExerciseType(
    id: 'etc',
    name: '기타',
    icon: '💪',
    isDefault: true,
    sortOrder: 16,
    fields: const [
      ExerciseField(
        key: 'activityName',
        type: ExerciseFieldType.text,
        label: '운동명',
        enLabel: 'Activity Name',
        section: '기본 정보',
        sectionEn: 'Basic Info',
      ),
      // ✅ [2026-09-14 추가] 3항목
      ExerciseField(
        key: 'categoryTags',
        type: ExerciseFieldType.multiSelect,
        label: '종목 카테고리 태그',
        enLabel: 'Category Tags',
        options: ['가벼움', '중강도', '고강도', '유산소', '근력'],
        optionEnLabels: ['Light', 'Moderate', 'High Intensity', 'Cardio', 'Strength'],
        section: '기본 정보',
        sectionEn: 'Basic Info',
      ),
      ExerciseField(
        key: 'bodyPartsUsed',
        type: ExerciseFieldType.multiSelect,
        label: '가동 부위',
        enLabel: 'Body Parts Used',
        options: ['전신', '상체', '하체', '코어'],
        optionEnLabels: ['Full Body', 'Upper Body', 'Lower Body', 'Core'],
        isRequired: false,
        section: '기본 정보',
        sectionEn: 'Basic Info',
      ),
      ExerciseField(
        key: 'equipmentUsed',
        type: ExerciseFieldType.text,
        label: '사용 장비/도구',
        enLabel: 'Equipment Used',
        isRequired: false,
        section: '기본 정보',
        sectionEn: 'Basic Info',
      ),
      ExerciseField(
        key: 'note',
        type: ExerciseFieldType.text,
        label: '상세 내용',
        enLabel: 'Details',
        isRequired: false,
        section: '기본 정보',
        sectionEn: 'Basic Info',
      ),
    ],
  ),
];
