// exercise_type_data.dart (v3)
//
// 🆕 [2026-09-29 v3] 화면에 보이는 한글 이름(label)을 모두 "누구나 뜻을 아는 쉬운 말"로
// 바꿨다 (예: 케이던스 → 1분당 걸음 수, SWOLF → 수영 효율 점수).
// - 저장되는 속 이름(key)과 선택지 값(options)은 한 글자도 바꾸지 않았다
//   → 지난 기록·분석 화면이 그대로 이어진다.
// - 영문 이름(enLabel)도 그대로 두었다 → English 모드와 10개국어 번역 사전이 그대로 쓰인다.
// - 어려운 항목의 한 줄 설명은 exercise_field_help.dart에 따로 모아 두었다.
//
// 각 종목의 필드는 아래 실제 트래킹 관행/스포츠과학 자료를 근거로 선정했다.
// - 골프: 페어웨이 안착률·그린 적중률(GIR)이 스코어와 가장 상관관계가 높은 지표
// - 수영: SWOLF(스트로크수+시간)가 대표적 효율 지표
// - 러닝: 페이스·케이던스·심박수가 3대 핵심 지표
// - 헬스: 볼륨(세트x횟수x중량)과 RPE/추정1RM이 표준 트레이닝 지표
// - 등산/자전거: 누적 상승고도가 거리보다 체력 소모를 더 잘 설명
//
// 위 근거 지표는 "필수 입력"이 아니라 "제공되는 필드"다.

import 'exercise_models.dart';

// 🆕 [자유운동 2026-10-07] "기타" → "자유운동" 화면 이름 (예전에 저장된 이름이 '기타'여도 자유운동으로 보이게)
String exerciseDisplayName(ExerciseType t) => t.id == 'etc' ? '자유 운동' : t.name;

// 🆕 [자유운동 2026-10-07] 접었다 펴서 기록하는 맨몸 운동 목록 (unit: 회 / 초) — 'en' = 영문 이름
const List<Map<String, String>> kFreeMoves = [
  {'key': 'jumprope', 'name': '줄넘기', 'en': 'Jump Rope', 'emoji': '🪢', 'unit': '회'},
  {'key': 'pushup', 'name': '푸시업', 'en': 'Push-ups', 'emoji': '💪', 'unit': '회'},
  {'key': 'squat', 'name': '스쿼트', 'en': 'Squats', 'emoji': '🦵', 'unit': '회'},
  {'key': 'pullup', 'name': '턱걸이', 'en': 'Pull-ups', 'emoji': '🧗', 'unit': '회'},
  {'key': 'situp', 'name': '윗몸 일으키기', 'en': 'Sit-ups', 'emoji': '🔥', 'unit': '회'},
  {'key': 'lunge', 'name': '런지', 'en': 'Lunges', 'emoji': '🚶', 'unit': '회'},
  {'key': 'plank', 'name': '플랭크', 'en': 'Plank', 'emoji': '🧱', 'unit': '초'},
  {'key': 'burpee', 'name': '버피 테스트', 'en': 'Burpees', 'emoji': '⚡', 'unit': '회'},
];

// 🆕 [2026-10-07] 10개 외국어 운동 이름
const Map<String, Map<String, String>> kFreeMoveNames = {
  'jumprope': {'JA': '縄跳び', 'ZH': '跳绳', 'FR': 'Corde à sauter', 'DE': 'Seilspringen', 'RU': 'Скакалка', 'AR': 'نط الحبل', 'HI': 'रस्सी कूद', 'VI': 'Nhảy dây', 'ES': 'Saltar la cuerda', 'TH': 'กระโดดเชือก'},
  'pushup': {'JA': '腕立て伏せ', 'ZH': '俯卧撑', 'FR': 'Pompes', 'DE': 'Liegestütze', 'RU': 'Отжимания', 'AR': 'تمرين الضغط', 'HI': 'पुश-अप', 'VI': 'Hít đất', 'ES': 'Flexiones', 'TH': 'วิดพื้น'},
  'squat': {'JA': 'スクワット', 'ZH': '深蹲', 'FR': 'Squats', 'DE': 'Kniebeugen', 'RU': 'Приседания', 'AR': 'القرفصاء', 'HI': 'स्क्वाट', 'VI': 'Squat', 'ES': 'Sentadillas', 'TH': 'สควอท'},
  'pullup': {'JA': '懸垂', 'ZH': '引体向上', 'FR': 'Tractions', 'DE': 'Klimmzüge', 'RU': 'Подтягивания', 'AR': 'العقلة', 'HI': 'पुल-अप', 'VI': 'Kéo xà', 'ES': 'Dominadas', 'TH': 'ดึงข้อ'},
  'situp': {'JA': '腹筋運動', 'ZH': '仰卧起坐', 'FR': 'Redressements assis', 'DE': 'Sit-ups', 'RU': 'Подъёмы туловища', 'AR': 'تمرين البطن', 'HI': 'सिट-अप', 'VI': 'Gập bụng', 'ES': 'Abdominales', 'TH': 'ซิทอัพ'},
  'lunge': {'JA': 'ランジ', 'ZH': '弓步蹲', 'FR': 'Fentes', 'DE': 'Ausfallschritte', 'RU': 'Выпады', 'AR': 'الطعن', 'HI': 'लंज', 'VI': 'Chùng chân', 'ES': 'Zancadas', 'TH': 'ลันจ์'},
  'plank': {'JA': 'プランク', 'ZH': '平板支撑', 'FR': 'Planche', 'DE': 'Unterarmstütz', 'RU': 'Планка', 'AR': 'البلانك', 'HI': 'प्लैंक', 'VI': 'Plank', 'ES': 'Plancha', 'TH': 'แพลงก์'},
  'burpee': {'JA': 'バーピー', 'ZH': '波比跳', 'FR': 'Burpees', 'DE': 'Burpees', 'RU': 'Бёрпи', 'AR': 'بيربي', 'HI': 'बर्पी', 'VI': 'Burpee', 'ES': 'Burpees', 'TH': 'เบอร์พี'},
};

/// 화면 언어에 맞는 운동 이름 (KO=한글, EN=영어, 10개 언어=그 언어)
String freeMoveLabel(Map<String, String> m, String lang) {
  if (lang == 'KO') return m['name']!;
  if (lang == 'EN') return m['en']!;
  return kFreeMoveNames[m['key']]?[lang] ?? m['en']!;
}

/// 저장된 한글 이름으로 운동 찾기 (분석 화면용)
Map<String, String>? freeMoveByName(String koName) {
  for (final m in kFreeMoves) {
    if (m['name'] == koName) return m;
  }
  return null;
}

/// 단위(회 · 초 · 세트)를 화면 언어로
const Map<String, Map<String, String>> kFreeUnits = {
  '회': {'KO': '회', 'EN': 'reps', 'JA': '回', 'ZH': '次', 'FR': 'rép.', 'DE': 'Wdh.', 'RU': 'раз', 'AR': 'مرة', 'HI': 'बार', 'VI': 'lần', 'ES': 'rep.', 'TH': 'ครั้ง'},
  '초': {'KO': '초', 'EN': 'sec', 'JA': '秒', 'ZH': '秒', 'FR': 's', 'DE': 'Sek.', 'RU': 'сек', 'AR': 'ث', 'HI': 'सेकंड', 'VI': 'giây', 'ES': 's', 'TH': 'วินาที'},
  '세트': {'KO': '세트', 'EN': 'sets', 'JA': 'セット', 'ZH': '组', 'FR': 'séries', 'DE': 'Sätze', 'RU': 'подх.', 'AR': 'مجموعات', 'HI': 'सेट', 'VI': 'hiệp', 'ES': 'series', 'TH': 'เซ็ต'},
};
String freeUnitLabel(String unitKo, String lang) => kFreeUnits[unitKo]?[lang] ?? kFreeUnits[unitKo]?['EN'] ?? unitKo;

// ---------------------------------------------------------------------------
// 여러 종목이 공유하는 필드 (재사용 헬퍼)
// ---------------------------------------------------------------------------

ExerciseField _distanceKmField({String label = '거리', String enLabel = 'Distance', String unit = 'km', String? section, String? sectionEn}) =>
    ExerciseField(
      key: 'distanceKm',
      type: ExerciseFieldType.number,
      label: label,
      enLabel: enLabel,
      unit: unit,
      section: section,
      sectionEn: sectionEn,
    );

ExerciseField _caloriesField({String? section, String? sectionEn}) => ExerciseField(
  key: 'calories',
  type: ExerciseFieldType.number,
  label: '소모 칼로리',
  enLabel: 'Calories',
  unit: 'kcal',
  isCalculated: true,
  section: section,
  sectionEn: sectionEn,
);

ExerciseField _courseField({String label = '코스/장소', String enLabel = 'Course/Location', String? section, String? sectionEn}) => ExerciseField(
  key: 'course',
  type: ExerciseFieldType.text,
  label: label,
  enLabel: enLabel,
  section: section,
  sectionEn: sectionEn,
);

ExerciseField _elevationGainField({String? section, String? sectionEn}) => ExerciseField(
  key: 'elevationGainM',
  type: ExerciseFieldType.number,
  label: '오르막 높이 합계',
  enLabel: 'Elevation Gain',
  unit: 'm',
  section: section,
  sectionEn: sectionEn,
);

/// 라켓 구기종목 공통 필드 (2026-09-14 이후 종목별로 분리되어 지금은 쓰이지 않음 - 보관용)
List<ExerciseField> _racketSportFields() => const [
  ExerciseField(
    key: 'matchType',
    type: ExerciseFieldType.select,
    label: '경기 방식',
    enLabel: 'Match Type',
    options: ['단식', '복식'],
    optionEnLabels: ['Singles', 'Doubles'],
    section: '경기 정보',
    sectionEn: 'Match Info',
  ),
  ExerciseField(
    key: 'opponent',
    type: ExerciseFieldType.text,
    label: '상대',
    enLabel: 'Opponent',
    isRequired: false,
    section: '경기 정보',
    sectionEn: 'Match Info',
  ),
  ExerciseField(
    key: 'setScore',
    type: ExerciseFieldType.text,
    label: '세트 점수',
    enLabel: 'Set Score',
    section: '경기 정보',
    sectionEn: 'Match Info',
  ),
  ExerciseField(
    key: 'result',
    type: ExerciseFieldType.select,
    label: '이김/짐',
    enLabel: 'Result',
    options: ['승', '패'],
    optionEnLabels: ['Win', 'Loss'],
    section: '경기 정보',
    sectionEn: 'Match Info',
  ),
  ExerciseField(
    key: 'winners',
    type: ExerciseFieldType.number,
    label: '바로 점수 낸 공격',
    enLabel: 'Winners',
    isRequired: false,
    section: '경기 기록',
    sectionEn: 'Match Stats',
  ),
  ExerciseField(
    key: 'unforcedErrors',
    type: ExerciseFieldType.number,
    label: '내 실수로 잃은 점수',
    enLabel: 'Unforced Errors',
    isRequired: false,
    section: '경기 기록',
    sectionEn: 'Match Stats',
  ),
  ExerciseField(
    key: 'avgRallyLength',
    type: ExerciseFieldType.number,
    label: '평균 주고받은 횟수',
    enLabel: 'Avg Rally Length',
    unit: '회',
    isRequired: false,
    section: '경기 기록',
    sectionEn: 'Match Stats',
  ),
];

/// 팀 구기종목 공통 필드 (2026-09-14 이후 종목별로 분리되어 지금은 쓰이지 않음 - 보관용)
List<ExerciseField> _teamSportFields() => const [
  ExerciseField(
    key: 'position',
    type: ExerciseFieldType.text,
    label: '맡은 자리',
    enLabel: 'Position',
    section: '경기 정보',
    sectionEn: 'Match Info',
  ),
  ExerciseField(
    key: 'gameDurationMin',
    type: ExerciseFieldType.number,
    label: '경기 시간',
    enLabel: 'Game Duration',
    unit: '분',
    isRequired: false,
    section: '경기 정보',
    sectionEn: 'Match Info',
  ),
  ExerciseField(
    key: 'points',
    type: ExerciseFieldType.number,
    label: '득점',
    enLabel: 'Points',
    section: '경기 기록',
    sectionEn: 'Match Stats',
  ),
  ExerciseField(
    key: 'assists',
    type: ExerciseFieldType.number,
    label: '득점 도움',
    enLabel: 'Assists',
    isRequired: false,
    section: '경기 기록',
    sectionEn: 'Match Stats',
  ),
  ExerciseField(
    key: 'distanceKm',
    type: ExerciseFieldType.number,
    label: '뛴 거리(어림)',
    enLabel: 'Distance (Est.)',
    unit: 'km',
    isRequired: false,
    section: '경기 기록',
    sectionEn: 'Match Stats',
  ),
];

// ---------------------------------------------------------------------------
// 기본 제공 16개 운동 종목
// ---------------------------------------------------------------------------

final List<ExerciseType> kDefaultExerciseTypes = [
  // 1. 골프
  ExerciseType(
    id: 'golf',
    name: '골프',
    icon: '🏌️',
    isDefault: true,
    sortOrder: 1,
    fields: const [
      // --- 구획 1: 라운드 정보 ---
      ExerciseField(
        key: 'roundCount',
        type: ExerciseFieldType.counter,
        label: '경기(라운드) 수',
        enLabel: 'Rounds',
        section: '라운드 정보',
        sectionEn: 'Round Info',
        isRequired: false,
      ),
      ExerciseField(
        key: 'course',
        type: ExerciseFieldType.text,
        label: '골프장 이름',
        enLabel: 'Course Name',
        section: '라운드 정보',
        sectionEn: 'Round Info',
      ),
      ExerciseField(
        key: 'teePosition',
        type: ExerciseFieldType.select,
        label: '첫 샷 치는 자리(티) 색',
        enLabel: 'Tee Position',
        options: ['블랙', '블루', '골드', '레드'],
        optionEnLabels: ['Black', 'Blue', 'Gold', 'Red'],
        section: '라운드 정보',
        sectionEn: 'Round Info',
        isRequired: false,
      ),
      ExerciseField(
        key: 'holeType',
        type: ExerciseFieldType.select,
        label: '총 홀 수',
        enLabel: 'Total Holes',
        options: ['9홀', '18홀'],
        optionEnLabels: ['9 Holes', '18 Holes'],
        section: '라운드 정보',
        sectionEn: 'Round Info',
      ),
      // --- 구획 2: 코스 · 점수 ---
      ExerciseField(
        key: 'courseDistanceM',
        type: ExerciseFieldType.number,
        label: '코스 총 거리',
        enLabel: 'Course Distance',
        unit: 'm',
        section: '코스 · 점수',
        sectionEn: 'Course & Score',
        isRequired: false,
      ),
      ExerciseField(
        key: 'parTotal',
        type: ExerciseFieldType.number,
        label: '기준 타수 합계',
        enLabel: 'Total Par',
        section: '코스 · 점수',
        sectionEn: 'Course & Score',
        isRequired: false,
      ),
      ExerciseField(
        key: 'totalScore',
        type: ExerciseFieldType.number,
        label: '내가 친 총 타수',
        enLabel: 'Total Score',
        section: '코스 · 점수',
        sectionEn: 'Course & Score',
      ),
      ExerciseField(
        key: 'scoreToPar',
        type: ExerciseFieldType.number,
        label: '기준보다 더 친 타수',
        enLabel: 'Score to Par',
        isCalculated: true,
        section: '코스 · 점수',
        sectionEn: 'Course & Score',
      ),
      // --- 구획 3: 그린 · 홀 결과 ---
      ExerciseField(
        key: 'putts',
        type: ExerciseFieldType.number,
        label: '그린에서 친 타수',
        enLabel: 'Total Putts',
        section: '그린 · 홀 결과',
        sectionEn: 'Short Game & Putting',
      ),
      ExerciseField(
        key: 'threePutts',
        type: ExerciseFieldType.counter,
        label: '그린에서 3번 이상 친 홀',
        enLabel: '3-Putts',
        isRequired: false,
        section: '그린 · 홀 결과',
        sectionEn: 'Short Game & Putting',
      ),
      ExerciseField(
        key: 'eagle',
        type: ExerciseFieldType.counter,
        label: '기준보다 2타 적은 홀',
        enLabel: 'Eagles',
        isRequired: false,
        section: '그린 · 홀 결과',
        sectionEn: 'Short Game & Putting',
      ),
      ExerciseField(
        key: 'birdie',
        type: ExerciseFieldType.counter,
        label: '기준보다 1타 적은 홀',
        enLabel: 'Birdies',
        section: '그린 · 홀 결과',
        sectionEn: 'Short Game & Putting',
      ),
      ExerciseField(
        key: 'bogeyOrWorse',
        type: ExerciseFieldType.counter,
        label: '기준보다 더 친 홀',
        enLabel: 'Bogey or Worse',
        section: '그린 · 홀 결과',
        sectionEn: 'Short Game & Putting',
      ),
      // --- 구획 4: 잔디 안착 · 그린 · 벌타 ---
      ExerciseField(
        key: 'fairwaysHit',
        type: ExerciseFieldType.number,
        label: '첫 샷 잔디 안착 수',
        enLabel: 'Fairways Hit (of 14)',
        section: '잔디 안착 · 그린 · 벌타',
        sectionEn: 'Fairways, Greens & Penalties',
      ),
      ExerciseField(
        key: 'greensInRegulation',
        type: ExerciseFieldType.number,
        label: '제때 그린 도착 수',
        enLabel: 'Greens in Regulation (of 18)',
        section: '잔디 안착 · 그린 · 벌타',
        sectionEn: 'Fairways, Greens & Penalties',
      ),
      ExerciseField(
        key: 'ob',
        type: ExerciseFieldType.counter,
        label: '벌타 수',
        enLabel: 'OB/Penalty',
        section: '잔디 안착 · 그린 · 벌타',
        sectionEn: 'Fairways, Greens & Penalties',
      ),
    ],
  ),

  // 2. 수영
  ExerciseType(
    id: 'swimming',
    name: '수영',
    icon: '🏊',
    isDefault: true,
    sortOrder: 2,
    fields: const [
      ExerciseField(
        key: 'stroke',
        type: ExerciseFieldType.multiSelect,
        label: '헤엄친 방법',
        enLabel: 'Stroke',
        options: ['자유형', '평영', '배영', '접영', '혼계영'],
        optionEnLabels: ['Freestyle', 'Breaststroke', 'Backstroke', 'Butterfly', 'Individual Medley'],
        section: '헤엄 방법 · 거리',
        sectionEn: 'Stroke & Distance',
      ),
      ExerciseField(
        key: 'distanceM',
        type: ExerciseFieldType.number,
        label: '총 거리',
        enLabel: 'Total Distance',
        unit: 'm',
        section: '헤엄 방법 · 거리',
        sectionEn: 'Stroke & Distance',
      ),
      ExerciseField(
        key: 'laps',
        type: ExerciseFieldType.number,
        label: '25m 간 횟수',
        enLabel: 'Laps (25m)',
        section: '헤엄 방법 · 거리',
        sectionEn: 'Stroke & Distance',
      ),
      ExerciseField(
        key: 'poolLength',
        type: ExerciseFieldType.select,
        label: '수영장 길이',
        enLabel: 'Pool Length',
        options: ['25m', '50m'],
        optionEnLabels: ['25m', '50m'],
        section: '헤엄 방법 · 거리',
        sectionEn: 'Stroke & Distance',
        isRequired: false,
      ),
      ExerciseField(
        key: 'pacePer100m',
        type: ExerciseFieldType.number,
        label: '100m 걸린 시간',
        enLabel: 'Pace (per 100m)',
        unit: '분',
        isCalculated: true,
        section: '빠르기 · 효율',
        sectionEn: 'Pace & Efficiency',
      ),
      ExerciseField(
        key: 'maxPacePer100m',
        type: ExerciseFieldType.number,
        label: '100m 가장 빠른 시간',
        enLabel: 'Max Pace (per 100m)',
        unit: '분',
        isRequired: false,
        section: '빠르기 · 효율',
        sectionEn: 'Pace & Efficiency',
      ),
      ExerciseField(
        key: 'strokeCountPerLap',
        type: ExerciseFieldType.number,
        label: '25m 팔 젓기 횟수',
        enLabel: 'Avg Strokes/25m',
        isRequired: false,
        section: '빠르기 · 효율',
        sectionEn: 'Pace & Efficiency',
      ),
      ExerciseField(
        key: 'swolf',
        type: ExerciseFieldType.number,
        label: '수영 효율 점수',
        enLabel: 'SWOLF',
        isCalculated: true,
        section: '빠르기 · 효율',
        sectionEn: 'Pace & Efficiency',
      ),
      ExerciseField(
        key: 'restTimeTotalMin',
        type: ExerciseFieldType.number,
        label: '쉰 시간 합계',
        enLabel: 'Total Rest Time',
        unit: '분',
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      ExerciseField(
        key: 'waterTempC',
        type: ExerciseFieldType.number,
        label: '물 온도',
        enLabel: 'Water Temperature',
        unit: '°C',
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      ExerciseField(
        key: 'calories',
        type: ExerciseFieldType.number,
        label: '소모 칼로리',
        enLabel: 'Calories',
        unit: 'kcal',
        isCalculated: true,
        section: '기타',
        sectionEn: 'Other',
      ),
    ],
  ),

  // 3. 달리기
  ExerciseType(
    id: 'running',
    name: '달리기',
    icon: '🏃',
    isDefault: true,
    sortOrder: 3,
    fields: [
      _distanceKmField(section: '거리 · 빠르기', sectionEn: 'Distance & Pace'),
      const ExerciseField(
        key: 'paceMinPerKm',
        type: ExerciseFieldType.number,
        label: '1km 걸린 시간',
        enLabel: 'Pace (per km)',
        unit: '분',
        isCalculated: true,
        section: '거리 · 빠르기',
        sectionEn: 'Distance & Pace',
      ),
      const ExerciseField(
        key: 'maxPaceMinPerKm',
        type: ExerciseFieldType.number,
        label: '1km 가장 빠른 시간',
        enLabel: 'Max Pace (per km)',
        unit: '분',
        isRequired: false,
        section: '거리 · 빠르기',
        sectionEn: 'Distance & Pace',
      ),
      const ExerciseField(
        key: 'cadenceSpm',
        type: ExerciseFieldType.number,
        label: '1분당 걸음 수',
        enLabel: 'Cadence',
        unit: '걸음',
        isRequired: false,
        section: '걸음 수 · 보폭',
        sectionEn: 'Cadence & Stride',
      ),
      const ExerciseField(
        key: 'maxCadenceSpm',
        type: ExerciseFieldType.number,
        label: '1분당 최고 걸음 수',
        enLabel: 'Max Cadence',
        unit: '걸음',
        isRequired: false,
        section: '걸음 수 · 보폭',
        sectionEn: 'Cadence & Stride',
      ),
      const ExerciseField(
        key: 'avgStrideCm',
        type: ExerciseFieldType.number,
        label: '한 걸음 평균 길이',
        enLabel: 'Avg Stride Length',
        unit: 'cm',
        isRequired: false,
        section: '걸음 수 · 보폭',
        sectionEn: 'Cadence & Stride',
      ),
      const ExerciseField(
        key: 'runType',
        type: ExerciseFieldType.select,
        label: '달리기 종류',
        enLabel: 'Run Type',
        options: ['일반', '인터벌', '트랙', '언덕', '장거리'],
        optionEnLabels: ['General', 'Interval', 'Track', 'Hill', 'Long Distance'],
        isRequired: false,
        section: '높이 · 기타',
        sectionEn: 'Elevation & Other',
      ),
      _elevationGainField(section: '높이 · 기타', sectionEn: 'Elevation & Other'),
      const ExerciseField(
        key: 'elevationLossM',
        type: ExerciseFieldType.number,
        label: '내리막 높이 합계',
        enLabel: 'Elevation Loss',
        unit: 'm',
        isRequired: false,
        section: '높이 · 기타',
        sectionEn: 'Elevation & Other',
      ),
      _caloriesField(section: '높이 · 기타', sectionEn: 'Elevation & Other'),
      _courseField(section: '높이 · 기타', sectionEn: 'Elevation & Other'),
    ],
  ),

  // 4. 걷기
  ExerciseType(
    id: 'walking',
    name: '걷기',
    icon: '🚶',
    isDefault: true,
    sortOrder: 4,
    fields: [
      _distanceKmField(section: '거리 · 걸음', sectionEn: 'Distance & Steps'),
      const ExerciseField(
        key: 'steps',
        type: ExerciseFieldType.number,
        label: '걸음 수',
        enLabel: 'Steps',
        unit: '보',
        section: '거리 · 걸음',
        sectionEn: 'Distance & Steps',
      ),
      const ExerciseField(
        key: 'paceMinPerKm',
        type: ExerciseFieldType.number,
        label: '1km 걸린 시간',
        enLabel: 'Pace (per km)',
        unit: '분',
        isCalculated: true,
        section: '거리 · 걸음',
        sectionEn: 'Distance & Steps',
      ),
      const ExerciseField(
        key: 'maxPaceMinPerKm',
        type: ExerciseFieldType.number,
        label: '1km 가장 빠른 시간',
        enLabel: 'Max Pace (per km)',
        unit: '분',
        isRequired: false,
        section: '거리 · 걸음',
        sectionEn: 'Distance & Steps',
      ),
      const ExerciseField(
        key: 'avgStrideM',
        type: ExerciseFieldType.number,
        label: '한 걸음 평균 길이',
        enLabel: 'Avg Stride Length',
        unit: 'm',
        isRequired: false,
        section: '걷는 모습',
        sectionEn: 'Gait Pattern',
      ),
      const ExerciseField(
        key: 'cadenceSpm',
        type: ExerciseFieldType.number,
        label: '1분당 걸음 수',
        enLabel: 'Cadence',
        unit: '걸음',
        isRequired: false,
        section: '걷는 모습',
        sectionEn: 'Gait Pattern',
      ),
      const ExerciseField(
        key: 'walkType',
        type: ExerciseFieldType.select,
        label: '걷기 종류',
        enLabel: 'Walk Type',
        options: ['산책', '도보', '계단', '러닝워크'],
        optionEnLabels: ['Stroll', 'Walk', 'Stairs', 'Power Walk'],
        isRequired: false,
        section: '걷는 모습',
        sectionEn: 'Gait Pattern',
      ),
      const ExerciseField(
        key: 'elevationChangeM',
        type: ExerciseFieldType.number,
        label: '높낮이 차이',
        enLabel: 'Elevation Change',
        unit: 'm',
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      const ExerciseField(
        key: 'restCount',
        type: ExerciseFieldType.counter,
        label: '쉰 횟수',
        enLabel: 'Rest Count',
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      _caloriesField(section: '기타', sectionEn: 'Other'),
    ],
  ),

  // 5. 헬스
  ExerciseType(
    id: 'gym',
    name: '헬스',
    icon: '🏋️',
    isDefault: true,
    sortOrder: 5,
    fields: const [
      ExerciseField(
        key: 'bodyPart',
        type: ExerciseFieldType.multiSelect,
        label: '운동 부위',
        enLabel: 'Body Part',
        options: ['가슴', '등', '하체', '어깨', '팔', '복근', '전신'],
        optionEnLabels: ['Chest', 'Back', 'Legs', 'Shoulders', 'Arms', 'Abs', 'Full Body'],
        section: '운동 정보',
        sectionEn: 'Exercise Info',
      ),
      ExerciseField(
        key: 'exerciseName',
        type: ExerciseFieldType.text,
        label: '운동 이름',
        enLabel: 'Exercise Name',
        section: '운동 정보',
        sectionEn: 'Exercise Info',
      ),
      ExerciseField(
        key: 'equipment',
        type: ExerciseFieldType.select,
        label: '사용 기구',
        enLabel: 'Equipment',
        options: ['바벨', '덤벨', '머신', '케이블', '맨몸', '케틀벨', '이지바', '트랩바', '체스트프레스/숄더프레스', '케이블 크로스오버'],
        optionEnLabels: ['Barbell', 'Dumbbell', 'Machine', 'Cable', 'Bodyweight', 'Kettlebell', 'EZ-Bar', 'Trap Bar', 'Chest Press/Shoulder Press', 'Cable Crossover'],
        isRequired: false,
        section: '운동 정보',
        sectionEn: 'Exercise Info',
      ),
      ExerciseField(
        key: 'sets',
        type: ExerciseFieldType.multiSet,
        label: '세트 기록 (무게 × 횟수)',
        enLabel: 'Sets (Weight x Reps, RPE)',
        section: '세트 기록',
        sectionEn: 'Set Log',
      ),
      ExerciseField(
        key: 'totalSets',
        type: ExerciseFieldType.number,
        label: '총 세트 수',
        enLabel: 'Total Sets',
        isCalculated: true,
        section: '세트 기록',
        sectionEn: 'Set Log',
      ),
      ExerciseField(
        key: 'restBetweenSetsSec',
        type: ExerciseFieldType.number,
        label: '세트 사이 쉰 시간',
        enLabel: 'Rest Between Sets',
        unit: '초',
        isRequired: false,
        section: '세트 기록',
        sectionEn: 'Set Log',
      ),
      ExerciseField(
        key: 'rir',
        type: ExerciseFieldType.counter,
        label: '더 할 수 있었던 횟수',
        enLabel: 'RIR (Reps in Reserve)',
        isRequired: false,
        section: '세트 기록',
        sectionEn: 'Set Log',
      ),
      ExerciseField(
        key: 'tempo',
        type: ExerciseFieldType.text,
        label: '동작 속도',
        enLabel: 'Tempo',
        isRequired: false,
        section: '세트 기록',
        sectionEn: 'Set Log',
      ),
      ExerciseField(
        key: 'toFailure',
        type: ExerciseFieldType.select,
        label: '더 못 할 때까지 했나요',
        enLabel: 'To Failure',
        options: ['예', '아니오'],
        optionEnLabels: ['Yes', 'No'],
        isRequired: false,
        section: '세트 기록',
        sectionEn: 'Set Log',
      ),
      ExerciseField(
        key: 'volumeLoad',
        type: ExerciseFieldType.number,
        label: '총 들어 올린 무게',
        enLabel: 'Total Volume',
        unit: 'kg',
        isCalculated: true,
        section: '들어 올린 무게',
        sectionEn: 'Volume & 1RM',
      ),
      ExerciseField(
        key: 'estimated1rm',
        type: ExerciseFieldType.number,
        label: '최대 들기 무게(추정)',
        enLabel: 'Estimated 1RM',
        unit: 'kg',
        isCalculated: true,
        section: '들어 올린 무게',
        sectionEn: 'Volume & 1RM',
      ),
    ],
  ),

  // 6. 필라테스
  ExerciseType(
    id: 'pilates',
    name: '필라테스',
    icon: '🧘',
    isDefault: true,
    sortOrder: 6,
    fields: [
      ExerciseField(
        key: 'programName',
        type: ExerciseFieldType.text,
        label: '수업 이름',
        enLabel: 'Program',
        section: '수업',
        sectionEn: 'Program',
      ),
      ExerciseField(
        key: 'equipment',
        type: ExerciseFieldType.select,
        label: '사용 기구',
        enLabel: 'Equipment',
        options: ['매트', '리포머', '캐딜락', '기타'],
        optionEnLabels: ['Mat', 'Reformer', 'Cadillac', 'Other'],
        isRequired: false,
        section: '수업',
        sectionEn: 'Program',
      ),
      ExerciseField(
        key: 'focusArea',
        type: ExerciseFieldType.select,
        label: '집중 부위',
        enLabel: 'Focus Area',
        options: ['코어', '전신', '유연성', '자세교정', '재활'],
        optionEnLabels: ['Core', 'Full Body', 'Flexibility', 'Posture Correction', 'Rehab'],
        isRequired: false,
        section: '수업',
        sectionEn: 'Program',
      ),
      ExerciseField(
        key: 'difficulty',
        type: ExerciseFieldType.select,
        label: '난이도',
        enLabel: 'Difficulty',
        options: ['초급', '중급', '고급'],
        optionEnLabels: ['Beginner', 'Intermediate', 'Advanced'],
        section: '수업',
        sectionEn: 'Program',
      ),
      ExerciseField(
        key: 'instructor',
        type: ExerciseFieldType.text,
        label: '강사',
        enLabel: 'Instructor',
        isRequired: false,
        section: '수업',
        sectionEn: 'Program',
      ),
      ExerciseField(
        key: 'totalMoves',
        type: ExerciseFieldType.number,
        label: '한 동작 수',
        enLabel: 'Total Moves',
        isRequired: false,
        section: '동작 · 스스로 평가',
        sectionEn: 'Moves & Self-Rating',
      ),
      ExerciseField(
        key: 'coreHoldTimeSec',
        type: ExerciseFieldType.number,
        label: '배·허리 힘 버틴 시간',
        enLabel: 'Core Hold Time',
        unit: '초',
        isRequired: false,
        section: '동작 · 스스로 평가',
        sectionEn: 'Moves & Self-Rating',
      ),
      ExerciseField(
        key: 'toolsUsed',
        type: ExerciseFieldType.multiSelect,
        label: '사용 도구',
        enLabel: 'Tools Used',
        options: ['링', '볼', '밴드', '볼스터', '롤러'],
        optionEnLabels: ['Ring', 'Ball', 'Band', 'Bolster', 'Roller'],
        isRequired: false,
        section: '동작 · 스스로 평가',
        sectionEn: 'Moves & Self-Rating',
      ),
      ExerciseField(
        key: 'breathScore',
        type: ExerciseFieldType.counter,
        label: '호흡 스스로 점수 (1~10)',
        enLabel: 'Breath Accuracy Score (1-10)',
        isRequired: false,
        section: '동작 · 스스로 평가',
        sectionEn: 'Moves & Self-Rating',
      ),
      ExerciseField(
        key: 'balanceScore',
        type: ExerciseFieldType.counter,
        label: '균형 스스로 점수 (1~10)',
        enLabel: 'Balance Score (1-10)',
        isRequired: false,
        section: '동작 · 스스로 평가',
        sectionEn: 'Moves & Self-Rating',
      ),
      ExerciseField(
        key: 'flexibilityScore',
        type: ExerciseFieldType.counter,
        label: '유연성 스스로 점수 (1~10)',
        enLabel: 'Flexibility Score (1-10)',
        isRequired: false,
        section: '동작 · 스스로 평가',
        sectionEn: 'Moves & Self-Rating',
      ),
      _caloriesField(section: '기타', sectionEn: 'Other'),
    ],
  ),

  // 7. 요가
  ExerciseType(
    id: 'yoga',
    name: '요가',
    icon: '🧘',
    isDefault: true,
    sortOrder: 7,
    fields: [
      ExerciseField(
        key: 'style',
        type: ExerciseFieldType.multiSelect,
        label: '요가 종류',
        enLabel: 'Style',
        options: ['하타', '빈야사', '아쉬탕가', '인요가', '기타'],
        optionEnLabels: ['Hatha', 'Vinyasa', 'Ashtanga', 'Yin Yoga', 'Other'],
        isRequired: false,
        section: '종류 · 수업',
        sectionEn: 'Style & Program',
      ),
      ExerciseField(
        key: 'programName',
        type: ExerciseFieldType.text,
        label: '수업 이름',
        enLabel: 'Program',
        section: '종류 · 수업',
        sectionEn: 'Style & Program',
      ),
      ExerciseField(
        key: 'focusArea',
        type: ExerciseFieldType.select,
        label: '집중 부위',
        enLabel: 'Focus Area',
        options: ['코어', '전신', '유연성', '균형', '이완/명상'],
        optionEnLabels: ['Core', 'Full Body', 'Flexibility', 'Balance', 'Relaxation/Meditation'],
        isRequired: false,
        section: '종류 · 수업',
        sectionEn: 'Style & Program',
      ),
      ExerciseField(
        key: 'difficulty',
        type: ExerciseFieldType.select,
        label: '난이도',
        enLabel: 'Difficulty',
        options: ['초급', '중급', '고급'],
        optionEnLabels: ['Beginner', 'Intermediate', 'Advanced'],
        section: '종류 · 수업',
        sectionEn: 'Style & Program',
      ),
      ExerciseField(
        key: 'asanaCount',
        type: ExerciseFieldType.number,
        label: '요가 동작 수',
        enLabel: 'Asana Count',
        isRequired: false,
        section: '수련 내용',
        sectionEn: 'Practice Breakdown',
      ),
      ExerciseField(
        key: 'meditationTimeMin',
        type: ExerciseFieldType.number,
        label: '명상 시간',
        enLabel: 'Meditation Time',
        unit: '분',
        isRequired: false,
        section: '수련 내용',
        sectionEn: 'Practice Breakdown',
      ),
      ExerciseField(
        key: 'breathingTimeMin',
        type: ExerciseFieldType.number,
        label: '호흡 수련 시간',
        enLabel: 'Breathing Practice Time',
        unit: '분',
        isRequired: false,
        section: '수련 내용',
        sectionEn: 'Practice Breakdown',
      ),
      ExerciseField(
        key: 'balanceHoldTimeSec',
        type: ExerciseFieldType.number,
        label: '균형 버틴 시간',
        enLabel: 'Balance Hold Time',
        unit: '초',
        isRequired: false,
        section: '수련 내용',
        sectionEn: 'Practice Breakdown',
      ),
      ExerciseField(
        key: 'challengePoseCount',
        type: ExerciseFieldType.counter,
        label: '어려운 동작 수',
        enLabel: 'Challenge Pose Count',
        isRequired: false,
        section: '수련 내용',
        sectionEn: 'Practice Breakdown',
      ),
      ExerciseField(
        key: 'inversionCount',
        type: ExerciseFieldType.counter,
        label: '거꾸로 서는 동작 수',
        enLabel: 'Inversion Count',
        isRequired: false,
        section: '수련 내용',
        sectionEn: 'Practice Breakdown',
      ),
      ExerciseField(
        key: 'flexibilityScore',
        type: ExerciseFieldType.counter,
        label: '유연성 스스로 점수 (1~10)',
        enLabel: 'Flexibility Score (1-10)',
        isRequired: false,
        section: '스스로 평가',
        sectionEn: 'Self-Rating',
      ),
      ExerciseField(
        key: 'meditationDepthScore',
        type: ExerciseFieldType.counter,
        label: '명상 집중 스스로 점수 (1~10)',
        enLabel: 'Meditation Depth Score (1-10)',
        isRequired: false,
        section: '스스로 평가',
        sectionEn: 'Self-Rating',
      ),
      _caloriesField(section: '기타', sectionEn: 'Other'),
    ],
  ),

  // 8. 등산
  ExerciseType(
    id: 'hiking',
    name: '등산',
    icon: '🥾',
    isDefault: true,
    sortOrder: 8,
    fields: [
      _courseField(label: '산·코스 이름', enLabel: 'Mountain/Course Name', section: '코스 정보', sectionEn: 'Course Info'),
      _distanceKmField(section: '코스 정보', sectionEn: 'Course Info'),
      const ExerciseField(
        key: 'difficulty',
        type: ExerciseFieldType.select,
        label: '난이도',
        enLabel: 'Difficulty',
        options: ['쉬움', '보통', '어려움'],
        optionEnLabels: ['Easy', 'Normal', 'Hard'],
        isRequired: false,
        section: '코스 정보',
        sectionEn: 'Course Info',
      ),
      _elevationGainField(section: '높이', sectionEn: 'Elevation'),
      const ExerciseField(
        key: 'elevationLossM',
        type: ExerciseFieldType.number,
        label: '내리막 높이 합계',
        enLabel: 'Elevation Loss',
        unit: 'm',
        isRequired: false,
        section: '높이',
        sectionEn: 'Elevation',
      ),
      const ExerciseField(
        key: 'peakAltitudeM',
        type: ExerciseFieldType.number,
        label: '가장 높은 곳 높이',
        enLabel: 'Peak Altitude',
        unit: 'm',
        isRequired: false,
        section: '높이',
        sectionEn: 'Elevation',
      ),
      const ExerciseField(
        key: 'movementAid',
        type: ExerciseFieldType.select,
        label: '보조 도구',
        enLabel: 'Movement Aid',
        options: ['도보', '트레킹폴', '등산스틱', '없음'],
        optionEnLabels: ['On Foot', 'Trekking Poles', 'Hiking Sticks', 'None'],
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      const ExerciseField(
        key: 'ascentPaceMinPerKm',
        type: ExerciseFieldType.number,
        label: '오르막 1km 걸린 시간',
        enLabel: 'Avg Pace (Ascent)',
        unit: '분',
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      const ExerciseField(
        key: 'restCount',
        type: ExerciseFieldType.counter,
        label: '쉰 횟수',
        enLabel: 'Rest Count',
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      const ExerciseField(
        key: 'restTimeTotalMin',
        type: ExerciseFieldType.number,
        label: '쉰 시간 합계',
        enLabel: 'Total Rest Time',
        unit: '분',
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      _caloriesField(section: '기타', sectionEn: 'Other'),
    ],
  ),

  // 9. 자전거
  ExerciseType(
    id: 'cycling',
    name: '자전거',
    icon: '🚴',
    isDefault: true,
    sortOrder: 9,
    fields: [
      _distanceKmField(section: '거리 · 속도', sectionEn: 'Distance & Speed'),
      const ExerciseField(
        key: 'avgSpeedKmh',
        type: ExerciseFieldType.number,
        label: '평균 속도',
        enLabel: 'Avg Speed',
        unit: 'km/h',
        isCalculated: true,
        section: '거리 · 속도',
        sectionEn: 'Distance & Speed',
      ),
      const ExerciseField(
        key: 'maxSpeedKmh',
        type: ExerciseFieldType.number,
        label: '최고 속도',
        enLabel: 'Max Speed',
        unit: 'km/h',
        isRequired: false,
        section: '거리 · 속도',
        sectionEn: 'Distance & Speed',
      ),
      const ExerciseField(
        key: 'avgCadenceRpm',
        type: ExerciseFieldType.number,
        label: '1분당 페달 회전',
        enLabel: 'Avg Cadence',
        unit: '회전',
        isRequired: false,
        section: '페달 · 힘',
        sectionEn: 'Cadence & Power',
      ),
      const ExerciseField(
        key: 'maxCadenceRpm',
        type: ExerciseFieldType.number,
        label: '1분당 최고 페달 회전',
        enLabel: 'Max Cadence',
        unit: '회전',
        isRequired: false,
        section: '페달 · 힘',
        sectionEn: 'Cadence & Power',
      ),
      const ExerciseField(
        key: 'avgPowerWatts',
        type: ExerciseFieldType.number,
        label: '페달 평균 힘',
        enLabel: 'Avg Power',
        unit: 'W',
        isRequired: false,
        section: '페달 · 힘',
        sectionEn: 'Cadence & Power',
      ),
      const ExerciseField(
        key: 'maxPowerWatts',
        type: ExerciseFieldType.number,
        label: '페달 최고 힘',
        enLabel: 'Max Power',
        unit: 'W',
        isRequired: false,
        section: '페달 · 힘',
        sectionEn: 'Cadence & Power',
      ),
      _elevationGainField(section: '기타', sectionEn: 'Other'),
      const ExerciseField(
        key: 'bikeType',
        type: ExerciseFieldType.select,
        label: '자전거 종류',
        enLabel: 'Bike Type',
        options: ['로드', 'MTB', '픽시', '하이브리드', 'eBike'],
        optionEnLabels: ['Road', 'MTB', 'Fixie', 'Hybrid', 'eBike'],
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      const ExerciseField(
        key: 'rideType',
        type: ExerciseFieldType.select,
        label: '타는 방식',
        enLabel: 'Ride Type',
        options: ['일반', '인터벌', '내리막', '힐클라임'],
        optionEnLabels: ['General', 'Interval', 'Downhill', 'Hill Climb'],
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      const ExerciseField(
        key: 'routeType',
        type: ExerciseFieldType.select,
        label: '길 종류',
        enLabel: 'Route Type',
        options: ['도로', '오프로드', '혼합'],
        optionEnLabels: ['Road', 'Off-Road', 'Mixed'],
        isRequired: false,
        section: '기타',
        sectionEn: 'Other',
      ),
      _caloriesField(section: '기타', sectionEn: 'Other'),
    ],
  ),

  // 10. 테니스
  ExerciseType(
    id: 'tennis',
    name: '테니스',
    icon: '🎾',
    isDefault: true,
    sortOrder: 10,
    fields: const [
      ExerciseField(
        key: 'setCount',
        type: ExerciseFieldType.number,
        label: '세트 수',
        enLabel: 'Sets',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'gamesWon',
        type: ExerciseFieldType.number,
        label: '내가 이긴 게임 수',
        enLabel: 'Games Won',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'opponentType',
        type: ExerciseFieldType.select,
        label: '경기 방식',
        enLabel: 'Opponent Type',
        options: ['단식', '복식', '훈련', '친선'],
        optionEnLabels: ['Singles', 'Doubles', 'Practice', 'Friendly'],
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'aces',
        type: ExerciseFieldType.counter,
        label: '서브로 바로 딴 점수',
        enLabel: 'Aces',
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'doubleFaults',
        type: ExerciseFieldType.counter,
        label: '서브 두 번 다 실패',
        enLabel: 'Double Faults',
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'serveAttempts',
        type: ExerciseFieldType.number,
        label: '서브 넣은 횟수',
        enLabel: 'Serve Attempts',
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'firstServePct',
        type: ExerciseFieldType.number,
        label: '첫 서브 성공률',
        enLabel: '1st Serve %',
        unit: '%',
        isCalculated: true,
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'firstServePointsPct',
        type: ExerciseFieldType.number,
        label: '첫 서브 뒤 이긴 비율',
        enLabel: '1st Serve Points %',
        unit: '%',
        isRequired: false,
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'maxServeSpeedKmh',
        type: ExerciseFieldType.number,
        label: '가장 빠른 서브',
        enLabel: 'Max Serve Speed',
        unit: 'km/h',
        isRequired: false,
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'winners',
        type: ExerciseFieldType.number,
        label: '바로 점수 낸 공격',
        enLabel: 'Winners',
        section: '주고받기',
        sectionEn: 'Rally',
      ),
      ExerciseField(
        key: 'unforcedErrors',
        type: ExerciseFieldType.number,
        label: '내 실수로 잃은 점수',
        enLabel: 'Unforced Errors',
        section: '주고받기',
        sectionEn: 'Rally',
      ),
      ExerciseField(
        key: 'avgRallyLength',
        type: ExerciseFieldType.number,
        label: '평균 주고받은 횟수',
        enLabel: 'Avg Rally Length',
        unit: '회',
        isRequired: false,
        section: '주고받기',
        sectionEn: 'Rally',
      ),
    ],
  ),

  // 11. 배드민턴
  ExerciseType(
    id: 'badminton',
    name: '배드민턴',
    icon: '🏸',
    isDefault: true,
    sortOrder: 11,
    fields: const [
      ExerciseField(
        key: 'matchCount',
        type: ExerciseFieldType.number,
        label: '경기 수',
        enLabel: 'Matches',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'shuttleType',
        type: ExerciseFieldType.select,
        label: '공(셔틀콕) 종류',
        enLabel: 'Shuttle Type',
        options: ['깃털', '플라스틱', '연습용'],
        optionEnLabels: ['Feather', 'Plastic', 'Practice'],
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'shuttleUsed',
        type: ExerciseFieldType.number,
        label: '쓴 공(셔틀콕) 수',
        enLabel: 'Shuttles Used',
        unit: '개',
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'totalScore',
        type: ExerciseFieldType.number,
        label: '내가 딴 점수 합계',
        enLabel: 'Total Score',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'smashAttempts',
        type: ExerciseFieldType.number,
        label: '내리꽂기(스매시) 횟수',
        enLabel: 'Smash Attempts',
        section: '공격 기술',
        sectionEn: 'Smash & Drop Shot',
      ),
      ExerciseField(
        key: 'smashSuccessRate',
        type: ExerciseFieldType.number,
        label: '내리꽂기 성공률',
        enLabel: 'Smash Success Rate',
        unit: '%',
        section: '공격 기술',
        sectionEn: 'Smash & Drop Shot',
      ),
      ExerciseField(
        key: 'dropShotSuccessRate',
        type: ExerciseFieldType.number,
        label: '살짝 떨구기 성공률',
        enLabel: 'Drop Shot Success Rate',
        unit: '%',
        isRequired: false,
        section: '공격 기술',
        sectionEn: 'Smash & Drop Shot',
      ),
      ExerciseField(
        key: 'avgRallyLength',
        type: ExerciseFieldType.number,
        label: '평균 주고받은 횟수',
        enLabel: 'Avg Rally Length',
        unit: '회',
        isRequired: false,
        section: '움직임 · 장비',
        sectionEn: 'Movement & Gear',
      ),
      ExerciseField(
        key: 'distanceKm',
        type: ExerciseFieldType.number,
        label: '움직인 거리',
        enLabel: 'Distance',
        unit: 'km',
        isRequired: false,
        section: '움직임 · 장비',
        sectionEn: 'Movement & Gear',
      ),
      ExerciseField(
        key: 'racketWeightG',
        type: ExerciseFieldType.number,
        label: '라켓 무게',
        enLabel: 'Racket Weight',
        unit: 'g',
        isRequired: false,
        section: '움직임 · 장비',
        sectionEn: 'Movement & Gear',
      ),
    ],
  ),

  // 12. 탁구
  ExerciseType(
    id: 'tabletennis',
    name: '탁구',
    icon: '🏓',
    isDefault: true,
    sortOrder: 12,
    fields: const [
      ExerciseField(
        key: 'setCount',
        type: ExerciseFieldType.number,
        label: '세트 수',
        enLabel: 'Sets',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'totalScore',
        type: ExerciseFieldType.number,
        label: '내가 딴 점수 합계',
        enLabel: 'Total Score',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'opponentType',
        type: ExerciseFieldType.select,
        label: '경기 방식',
        enLabel: 'Opponent Type',
        options: ['단식', '복식', '훈련', '친선'],
        optionEnLabels: ['Singles', 'Doubles', 'Practice', 'Friendly'],
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'serveSpinType',
        type: ExerciseFieldType.select,
        label: '서브 회전 종류',
        enLabel: 'Serve Spin Type',
        options: ['톱스핀', '백스핀', '노스핀', '횡회전', '리프트'],
        optionEnLabels: ['Topspin', 'Backspin', 'No Spin', 'Sidespin', 'Lift'],
        isRequired: false,
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'serveAttempts',
        type: ExerciseFieldType.number,
        label: '서브 넣은 횟수',
        enLabel: 'Serve Attempts',
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'serveSuccessRate',
        type: ExerciseFieldType.number,
        label: '서브 성공률',
        enLabel: 'Serve Success Rate',
        unit: '%',
        isCalculated: true,
        section: '서브',
        sectionEn: 'Serve',
      ),
      ExerciseField(
        key: 'attackAttempts',
        type: ExerciseFieldType.number,
        label: '공격 횟수',
        enLabel: 'Attack Attempts',
        section: '공격',
        sectionEn: 'Attack',
      ),
      ExerciseField(
        key: 'attackSuccessRate',
        type: ExerciseFieldType.number,
        label: '공격 성공률',
        enLabel: 'Attack Success Rate',
        unit: '%',
        section: '공격',
        sectionEn: 'Attack',
      ),
      ExerciseField(
        key: 'forehandWinners',
        type: ExerciseFieldType.number,
        label: '라켓 든 쪽 공격 득점',
        enLabel: 'Forehand Winners',
        isRequired: false,
        section: '공격',
        sectionEn: 'Attack',
      ),
      ExerciseField(
        key: 'backhandWinners',
        type: ExerciseFieldType.number,
        label: '반대쪽 공격 득점',
        enLabel: 'Backhand Winners',
        isRequired: false,
        section: '공격',
        sectionEn: 'Attack',
      ),
      ExerciseField(
        key: 'avgRallyLength',
        type: ExerciseFieldType.number,
        label: '평균 주고받은 횟수',
        enLabel: 'Avg Rally Length',
        unit: '회',
        isRequired: false,
        section: '공격',
        sectionEn: 'Attack',
      ),
    ],
  ),

  // 13. 농구
  ExerciseType(
    id: 'basketball',
    name: '농구',
    icon: '🏀',
    isDefault: true,
    sortOrder: 13,
    fields: const [
      ExerciseField(
        key: 'position',
        type: ExerciseFieldType.text,
        label: '맡은 자리',
        enLabel: 'Position',
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'gameDurationMin',
        type: ExerciseFieldType.number,
        label: '경기 시간',
        enLabel: 'Game Duration',
        unit: '분',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'distanceKm',
        type: ExerciseFieldType.number,
        label: '뛴 거리',
        enLabel: 'Distance',
        unit: 'km',
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'points',
        type: ExerciseFieldType.number,
        label: '득점',
        enLabel: 'Points',
        section: '슛',
        sectionEn: 'Shooting',
      ),
      ExerciseField(
        key: 'fg2Made',
        type: ExerciseFieldType.number,
        label: '2점슛 성공',
        enLabel: '2-Pt Made',
        isRequired: false,
        section: '슛',
        sectionEn: 'Shooting',
      ),
      ExerciseField(
        key: 'fg2Attempted',
        type: ExerciseFieldType.number,
        label: '2점슛 던진 수',
        enLabel: '2-Pt Attempted',
        isRequired: false,
        section: '슛',
        sectionEn: 'Shooting',
      ),
      ExerciseField(
        key: 'fg3Made',
        type: ExerciseFieldType.number,
        label: '3점슛 성공',
        enLabel: '3-Pt Made',
        isRequired: false,
        section: '슛',
        sectionEn: 'Shooting',
      ),
      ExerciseField(
        key: 'fg3Attempted',
        type: ExerciseFieldType.number,
        label: '3점슛 던진 수',
        enLabel: '3-Pt Attempted',
        isRequired: false,
        section: '슛',
        sectionEn: 'Shooting',
      ),
      ExerciseField(
        key: 'ftMade',
        type: ExerciseFieldType.number,
        label: '자유투 성공',
        enLabel: 'FT Made',
        isRequired: false,
        section: '슛',
        sectionEn: 'Shooting',
      ),
      ExerciseField(
        key: 'ftAttempted',
        type: ExerciseFieldType.number,
        label: '자유투 던진 수',
        enLabel: 'FT Attempted',
        isRequired: false,
        section: '슛',
        sectionEn: 'Shooting',
      ),
      ExerciseField(
        key: 'assists',
        type: ExerciseFieldType.number,
        label: '득점 도움',
        enLabel: 'Assists',
        section: '수비 · 기타',
        sectionEn: 'Defense & Other',
      ),
      ExerciseField(
        key: 'reboundsOff',
        type: ExerciseFieldType.counter,
        label: '공격 때 튄 공 잡기',
        enLabel: 'Off. Rebounds',
        isRequired: false,
        section: '수비 · 기타',
        sectionEn: 'Defense & Other',
      ),
      ExerciseField(
        key: 'reboundsDef',
        type: ExerciseFieldType.counter,
        label: '수비 때 튄 공 잡기',
        enLabel: 'Def. Rebounds',
        isRequired: false,
        section: '수비 · 기타',
        sectionEn: 'Defense & Other',
      ),
      ExerciseField(
        key: 'fouls',
        type: ExerciseFieldType.counter,
        label: '반칙 수',
        enLabel: 'Fouls',
        isRequired: false,
        section: '수비 · 기타',
        sectionEn: 'Defense & Other',
      ),
    ],
  ),

  // 14. 축구
  ExerciseType(
    id: 'soccer',
    name: '축구',
    icon: '⚽',
    isDefault: true,
    sortOrder: 14,
    fields: const [
      ExerciseField(
        key: 'position',
        type: ExerciseFieldType.select,
        label: '맡은 자리',
        enLabel: 'Position',
        options: ['GK', 'DF', 'MF', 'FW'],
        optionEnLabels: ['GK', 'DF', 'MF', 'FW'],
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'gameDurationMin',
        type: ExerciseFieldType.number,
        label: '경기 시간',
        enLabel: 'Game Duration',
        unit: '분',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'distanceKm',
        type: ExerciseFieldType.number,
        label: '뛴 거리',
        enLabel: 'Distance',
        unit: 'km',
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'maxSpeedKmh',
        type: ExerciseFieldType.number,
        label: '최고 속도',
        enLabel: 'Max Speed',
        unit: 'km/h',
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'sprintCount',
        type: ExerciseFieldType.number,
        label: '전력 질주 횟수',
        enLabel: 'Sprint Count',
        isRequired: false,
        section: '경기 정보',
        sectionEn: 'Match Info',
      ),
      ExerciseField(
        key: 'passAttempts',
        type: ExerciseFieldType.number,
        label: '패스 한 횟수',
        enLabel: 'Pass Attempts',
        section: '패스',
        sectionEn: 'Passing',
      ),
      ExerciseField(
        key: 'passSuccess',
        type: ExerciseFieldType.number,
        label: '패스 성공 횟수',
        enLabel: 'Passes Completed',
        section: '패스',
        sectionEn: 'Passing',
      ),
      ExerciseField(
        key: 'passSuccessRate',
        type: ExerciseFieldType.number,
        label: '패스 성공률',
        enLabel: 'Pass Success Rate',
        unit: '%',
        isCalculated: true,
        section: '패스',
        sectionEn: 'Passing',
      ),
      ExerciseField(
        key: 'shots',
        type: ExerciseFieldType.number,
        label: '슛 한 횟수',
        enLabel: 'Shots',
        section: '득점 · 수비',
        sectionEn: 'Scoring & Defense',
      ),
      ExerciseField(
        key: 'shotsOnTarget',
        type: ExerciseFieldType.number,
        label: '골대 안으로 간 슛',
        enLabel: 'Shots on Target',
        section: '득점 · 수비',
        sectionEn: 'Scoring & Defense',
      ),
      ExerciseField(
        key: 'goals',
        type: ExerciseFieldType.counter,
        label: '골',
        enLabel: 'Goals',
        section: '득점 · 수비',
        sectionEn: 'Scoring & Defense',
      ),
      ExerciseField(
        key: 'assists',
        type: ExerciseFieldType.counter,
        label: '득점 도움',
        enLabel: 'Assists',
        section: '득점 · 수비',
        sectionEn: 'Scoring & Defense',
      ),
      ExerciseField(
        key: 'tackleSuccessRate',
        type: ExerciseFieldType.number,
        label: '공 뺏기 성공률',
        enLabel: 'Tackle Success Rate',
        unit: '%',
        isRequired: false,
        section: '득점 · 수비',
        sectionEn: 'Scoring & Defense',
      ),
    ],
  ),

  // 15. 스키
  ExerciseType(
    id: 'skiing',
    name: '스키',
    icon: '⛷️',
    isDefault: true,
    sortOrder: 15,
    fields: [
      ExerciseField(
        key: 'resort',
        type: ExerciseFieldType.text,
        label: '스키장 이름',
        enLabel: 'Resort Name',
        isRequired: false,
        section: '장비 · 코스',
        sectionEn: 'Equipment & Course',
      ),
      ExerciseField(
        key: 'equipmentType',
        type: ExerciseFieldType.select,
        label: '사용 장비',
        enLabel: 'Equipment',
        options: ['스키', '스노보드'],
        optionEnLabels: ['Ski', 'Snowboard'],
        section: '장비 · 코스',
        sectionEn: 'Equipment & Course',
      ),
      ExerciseField(
        key: 'slopeType',
        type: ExerciseFieldType.select,
        label: '타는 방식',
        enLabel: 'Slope Type',
        options: ['알파인', '크로스컨트리', '프리스타일', '백컨트리'],
        optionEnLabels: ['Alpine', 'Cross-Country', 'Freestyle', 'Backcountry'],
        isRequired: false,
        section: '장비 · 코스',
        sectionEn: 'Equipment & Course',
      ),
      ExerciseField(
        key: 'slopeDifficulty',
        type: ExerciseFieldType.select,
        label: '코스 난이도',
        enLabel: 'Slope Difficulty',
        options: ['초급', '중급', '상급'],
        optionEnLabels: ['Beginner', 'Intermediate', 'Advanced'],
        section: '장비 · 코스',
        sectionEn: 'Equipment & Course',
      ),
      ExerciseField(
        key: 'weatherSnow',
        type: ExerciseFieldType.select,
        label: '눈 상태',
        enLabel: 'Snow Condition',
        options: ['파우더', '습설', '인공', '아이스'],
        optionEnLabels: ['Powder', 'Wet Snow', 'Artificial', 'Ice'],
        isRequired: false,
        section: '장비 · 코스',
        sectionEn: 'Equipment & Course',
      ),
      ExerciseField(
        key: 'runCount',
        type: ExerciseFieldType.counter,
        label: '내려온 횟수',
        enLabel: 'Run Count',
        section: '내려온 기록',
        sectionEn: 'Run Log',
      ),
      ExerciseField(
        key: 'totalDistanceKm',
        type: ExerciseFieldType.number,
        label: '내려온 거리 합계',
        enLabel: 'Total Distance',
        unit: 'km',
        isRequired: false,
        section: '내려온 기록',
        sectionEn: 'Run Log',
      ),
      ExerciseField(
        key: 'totalDescentM',
        type: ExerciseFieldType.number,
        label: '내려온 높이 합계',
        enLabel: 'Total Descent',
        unit: 'm',
        isRequired: false,
        section: '내려온 기록',
        sectionEn: 'Run Log',
      ),
      ExerciseField(
        key: 'liftAscentM',
        type: ExerciseFieldType.number,
        label: '리프트로 오른 높이',
        enLabel: 'Lift Ascent',
        unit: 'm',
        isRequired: false,
        section: '내려온 기록',
        sectionEn: 'Run Log',
      ),
      ExerciseField(
        key: 'avgSpeedKmh',
        type: ExerciseFieldType.number,
        label: '평균 속도',
        enLabel: 'Avg Speed',
        unit: 'km/h',
        isRequired: false,
        section: '내려온 기록',
        sectionEn: 'Run Log',
      ),
      ExerciseField(
        key: 'maxSpeedKmh',
        type: ExerciseFieldType.number,
        label: '최고 속도',
        enLabel: 'Max Speed',
        unit: 'km/h',
        isRequired: false,
        section: '내려온 기록',
        sectionEn: 'Run Log',
      ),
      ExerciseField(
        key: 'liftCount',
        type: ExerciseFieldType.counter,
        label: '리프트 탄 횟수',
        enLabel: 'Lift Rides',
        isRequired: false,
        section: '내려온 기록',
        sectionEn: 'Run Log',
      ),
      _caloriesField(section: '기타', sectionEn: 'Other'),
    ],
  ),

  // 16. 기타
  ExerciseType(
    id: 'etc',
    name: '자유 운동', // 🆕 [2026-10-07] 기타 → 자유 운동
    icon: '💪',
    isDefault: true,
    sortOrder: 16,
    fields: const [
      ExerciseField(
        key: 'activityName',
        type: ExerciseFieldType.text,
        label: '운동 이름',
        enLabel: 'Activity Name',
        section: '기본 정보',
        sectionEn: 'Basic Info',
      ),
      ExerciseField(
        key: 'categoryTags',
        type: ExerciseFieldType.multiSelect,
        label: '운동 성격',
        enLabel: 'Category Tags',
        options: ['가벼움', '중강도', '고강도', '유산소', '근력'],
        optionEnLabels: ['Light', 'Moderate', 'High Intensity', 'Cardio', 'Strength'],
        section: '기본 정보',
        sectionEn: 'Basic Info',
      ),
      ExerciseField(
        key: 'bodyPartsUsed',
        type: ExerciseFieldType.multiSelect,
        label: '쓴 몸 부위',
        enLabel: 'Body Parts Used',
        options: ['전신', '상체', '하체', '코어'],
        optionEnLabels: ['Full Body', 'Upper Body', 'Lower Body', 'Core'],
        isRequired: false,
        section: '기본 정보',
        sectionEn: 'Basic Info',
      ),
      ExerciseField(
        key: 'equipmentUsed',
        type: ExerciseFieldType.text,
        label: '사용 장비·도구',
        enLabel: 'Equipment Used',
        isRequired: false,
        section: '기본 정보',
        sectionEn: 'Basic Info',
      ),
      ExerciseField(
        key: 'note',
        type: ExerciseFieldType.text,
        label: '자세한 내용',
        enLabel: 'Details',
        isRequired: false,
        section: '기본 정보',
        sectionEn: 'Basic Info',
      ),
    ],
  ),
];
