// exercise_field_help.dart
//
// 🆕 [2026-09-29] 운동 세부 기록 입력칸 아래에 회색 작은 글씨로 보여주는 "한 줄 설명".
// 뜻을 모르면 기록을 못 한다는 요청에 따라, 어려운 항목만 골라 쉬운 말로 풀어 두었다.
// - 🆕 [2026-10-08] 12개 언어 모두 보인다 (아래 kExerciseFieldHelpI18n)
// - 찾는 순서: '종목id.칸이름' → '칸이름'  (같은 칸 이름이라도 종목마다 뜻이 다를 때 앞의 것을 씀)
// - 여기 없는 칸은 설명 없이 이름만 보인다

import 'app_language_service.dart';

const Map<String, String> kExerciseFieldHelpKo = {
  // ---------------- 여러 종목 공통 ----------------
  'calories': '몸무게와 운동 시간으로 자동 계산됩니다',
  'elevationGainM': '오르막을 올라간 높이를 모두 더한 값',
  'elevationLossM': '내리막을 내려간 높이를 모두 더한 값',
  'winners': '상대가 받지 못해 바로 점수가 난 내 공격 수',
  'unforcedErrors': '상대의 압박 없이 내 실수로 잃은 점수',
  'avgRallyLength': '한 점이 날 때까지 공을 주고받은 평균 횟수',
  'assists': '내 패스로 동료가 득점한 횟수',
  'paceMinPerKm': '1km를 가는 데 걸린 평균 시간 (자동 계산) · 짧을수록 빠름',
  'maxPaceMinPerKm': '가장 빨랐던 1km 구간의 시간',
  'cadenceSpm': '1분 동안 발을 디딘 횟수 · 달리기는 보통 160~180',
  'maxCadenceSpm': '가장 빨리 걸음을 옮긴 순간의 1분당 걸음 수',
  'avgStrideCm': '한 걸음의 평균 길이',
  'avgStrideM': '한 걸음의 평균 길이',

  // ---------------- 골프 ----------------
  'golf.roundCount': '오늘 친 경기 횟수 · 18홀 한 번이 1라운드',
  'golf.teePosition': '첫 샷을 치는 자리 · 블랙이 가장 멀고 레드가 가장 가까움',
  'golf.parTotal': '모든 홀의 기준 타수(파)를 더한 값 · 18홀은 보통 72',
  'golf.totalScore': '18홀(또는 9홀) 동안 친 타수 전부',
  'golf.scoreToPar': '내가 친 타수 − 기준 타수 (자동 계산)',
  'golf.putts': '그린에 올라간 뒤 굴려서 친 타수(퍼팅) 합계',
  'golf.threePutts': '그린 위에서 3번 이상 굴려 친 홀의 수',
  'golf.eagle': '이글 · 기준 타수보다 2타 적게 끝낸 홀',
  'golf.birdie': '버디 · 기준 타수보다 1타 적게 끝낸 홀',
  'golf.bogeyOrWorse': '보기 이상 · 기준 타수보다 1타 이상 더 친 홀',
  'golf.fairwaysHit': '첫 샷이 잘 깎인 잔디 길(페어웨이)에 떨어진 홀 수 · 짧은 홀(파3) 빼고 14개 중',
  'golf.greensInRegulation': '기준 타수보다 2타 적게 그린에 올린 홀 수 · 18개 중',
  'golf.ob': '공이 경기 구역 밖으로 나가거나 물에 빠져 받은 벌점 타수',

  // ---------------- 수영 ----------------
  'swimming.laps': '25m 수영장을 한 번 끝까지 가면 1회',
  'swimming.pacePer100m': '100m를 가는 데 걸린 평균 시간 (자동 계산)',
  'swimming.maxPacePer100m': '가장 빨랐던 100m 구간의 시간',
  'swimming.strokeCountPerLap': '25m를 가는 동안 팔을 저은 평균 횟수',
  'swimming.swolf': '25m 걸린 초 + 팔 젓기 횟수 (자동 계산) · 낮을수록 효율이 좋음',

  // ---------------- 헬스 ----------------
  'gym.exerciseName': '예: 벤치프레스, 스쿼트, 랫풀다운',
  'gym.rir': '세트를 마쳤을 때 힘이 남아 더 할 수 있었던 횟수',
  'gym.tempo': '예: 3-1-1 → 내리기 3초, 멈춤 1초, 올리기 1초',
  'gym.toFailure': '마지막 세트를 더 이상 못 할 때까지 했는지',
  'gym.volumeLoad': '무게 × 횟수를 모든 세트에서 더한 값 (자동 계산)',
  'gym.estimated1rm': '한 번에 들 수 있는 가장 무거운 무게를 계산한 값 (자동 계산)',

  // ---------------- 필라테스 · 요가 ----------------
  'pilates.coreHoldTimeSec': '배와 허리(코어)에 힘을 주고 버틴 시간 합계',
  'pilates.breathScore': '동작에 맞춰 숨을 잘 쉬었는지 스스로 매긴 점수',
  'yoga.asanaCount': '오늘 한 요가 자세(아사나)의 수',
  'yoga.breathingTimeMin': '호흡만 따로 수련한 시간',
  'yoga.inversionCount': '물구나무처럼 머리가 아래로 가는 동작의 수',

  // ---------------- 등산 ----------------
  'hiking.peakAltitudeM': '오른 곳 중 가장 높은 지점의 높이 (바다 높이 기준)',
  'hiking.ascentPaceMinPerKm': '오르막에서 1km를 가는 데 걸린 평균 시간',

  // ---------------- 자전거 ----------------
  'cycling.avgSpeedKmh': '거리 ÷ 시간으로 자동 계산',
  'cycling.avgCadenceRpm': '1분 동안 페달을 돌린 횟수 · 보통 80~100',
  'cycling.maxCadenceRpm': '가장 빨리 페달을 돌린 순간의 1분당 회전 수',
  'cycling.avgPowerWatts': '페달을 밟은 힘의 평균 · 파워미터가 있을 때만 적으세요',
  'cycling.maxPowerWatts': '가장 세게 밟은 순간의 힘 · 파워미터가 있을 때만',

  // ---------------- 테니스 · 배드민턴 · 탁구 ----------------
  'tennis.gamesWon': '모든 세트에서 내가 이긴 게임 수를 더한 값',
  'tennis.aces': '상대가 라켓에 대지도 못한 서브 (에이스)',
  'tennis.doubleFaults': '두 번의 서브가 모두 들어가지 않아 잃은 점수 (더블폴트)',
  'tennis.firstServePct': '첫 서브가 들어간 비율 (자동 계산)',
  'tennis.firstServePointsPct': '첫 서브가 들어간 점수 중 내가 이긴 비율',
  'badminton.smashAttempts': '높이 뜬 공을 강하게 내리꽂은 공격 횟수',
  'badminton.dropShotSuccessRate': '네트 앞에 살짝 떨어뜨린 공(드롭샷)이 성공한 비율',
  'tabletennis.serveSpinType': '톱스핀=앞으로 도는 공 · 백스핀=뒤로 도는 공',
  'tabletennis.forehandWinners': '라켓 든 손 쪽(포핸드)으로 쳐서 바로 딴 점수',
  'tabletennis.backhandWinners': '라켓 반대쪽(백핸드)으로 쳐서 바로 딴 점수',

  // ---------------- 농구 · 축구 ----------------
  'basketball.reboundsOff': '우리 편 슛이 빗나가 튕긴 공을 잡은 횟수 (공격 리바운드)',
  'basketball.reboundsDef': '상대 슛이 빗나가 튕긴 공을 잡은 횟수 (수비 리바운드)',
  'soccer.position': 'GK 골키퍼 · DF 수비 · MF 가운데 · FW 공격',
  'soccer.sprintCount': '온 힘을 다해 짧게 달린 횟수',
  'soccer.shotsOnTarget': '빗나가지 않고 골대 안쪽으로 날아간 슛 수',
  'soccer.tackleSuccessRate': '발을 뻗어 상대 공을 빼앗는 데 성공한 비율',

  // ---------------- 스키 ----------------
  'skiing.slopeType': '알파인=일반 슬로프 · 크로스컨트리=평지 이동 · 백컨트리=정비 안 된 산',
  'skiing.totalDescentM': '내려온 높이를 모두 더한 값',
};

// 🆕 [2026-10-08] 한 줄 설명 English + 10개 외국어
const Map<String, Map<String, String>> kExerciseFieldHelpI18n = {
  'calories': {'EN': 'Calculated automatically from body weight and workout time', 'JA': '体重と運動時間から自動計算されます', 'ZH': '根据体重和运动时间自动计算', 'FR': 'Calculé automatiquement à partir du poids et de la durée', 'DE': 'Wird aus Körpergewicht und Trainingszeit berechnet', 'RU': 'Считается автоматически по весу и времени', 'AR': 'تُحسب تلقائيًا من الوزن ومدة التمرين', 'HI': 'वज़न और व्यायाम समय से अपने आप गिनी जाती है', 'VI': 'Tự tính từ cân nặng và thời gian tập', 'ES': 'Se calcula automáticamente con tu peso y el tiempo', 'TH': 'คำนวณอัตโนมัติจากน้ำหนักและเวลาออกกำลัง'},
  'elevationGainM': {'EN': 'Total height climbed on all uphills', 'JA': '上り坂で登った高さの合計', 'ZH': '所有上坡爬升高度之和', 'FR': 'Somme de toutes les montées', 'DE': 'Summe aller Anstiege', 'RU': 'Сумма всех подъёмов', 'AR': 'مجموع ارتفاع كل الصعود', 'HI': 'सभी चढ़ाई की कुल ऊँचाई', 'VI': 'Tổng độ cao đã leo', 'ES': 'Suma de todas las subidas', 'TH': 'ความสูงที่ขึ้นทั้งหมดรวมกัน'},
  'elevationLossM': {'EN': 'Total height descended on all downhills', 'JA': '下り坂で下った高さの合計', 'ZH': '所有下坡下降高度之和', 'FR': 'Somme de toutes les descentes', 'DE': 'Summe aller Abstiege', 'RU': 'Сумма всех спусков', 'AR': 'مجموع ارتفاع كل النزول', 'HI': 'सभी ढलान की कुल ऊँचाई', 'VI': 'Tổng độ cao đã xuống', 'ES': 'Suma de todas las bajadas', 'TH': 'ความสูงที่ลงทั้งหมดรวมกัน'},
  'winners': {'EN': 'Shots the opponent could not return — a direct point', 'JA': '相手が返せず、すぐに点になった自分の攻撃数', 'ZH': '对手接不到、直接得分的进攻次数', 'FR': 'Coups que l\'adversaire n\'a pas pu renvoyer', 'DE': 'Schläge, die der Gegner nicht zurückbekam', 'RU': 'Удары, которые соперник не смог отбить', 'AR': 'ضربات لم يستطع الخصم ردها فأحرزت نقطة', 'HI': 'ऐसे शॉट जिन्हें विरोधी लौटा न सका', 'VI': 'Cú đánh đối thủ không đỡ được, ghi điểm ngay', 'ES': 'Golpes que el rival no pudo devolver', 'TH': 'ลูกที่คู่แข่งรับไม่ได้ ได้แต้มทันที'},
  'unforcedErrors': {'EN': 'Points lost by my own mistakes, without pressure', 'JA': '相手の圧力なしに自分のミスで失った点', 'ZH': '没有对手压力、因自己失误丢的分', 'FR': 'Points perdus par mes propres fautes, sans pression', 'DE': 'Punkte durch eigene Fehler ohne Druck verloren', 'RU': 'Очки, потерянные из-за своих ошибок без давления', 'AR': 'نقاط خسرتها بأخطائي دون ضغط', 'HI': 'बिना दबाव अपनी गलती से गँवाए अंक', 'VI': 'Điểm mất do lỗi của mình, không bị ép', 'ES': 'Puntos perdidos por errores propios sin presión', 'TH': 'แต้มที่เสียเพราะพลาดเองโดยไม่ถูกกดดัน'},
  'avgRallyLength': {'EN': 'Average number of hits until a point ends', 'JA': '1点が決まるまでの平均ラリー回数', 'ZH': '每分平均来回次数', 'FR': 'Nombre moyen d\'échanges par point', 'DE': 'Durchschnittliche Ballwechsel pro Punkt', 'RU': 'Среднее число ударов за розыгрыш', 'AR': 'متوسط عدد الضربات حتى تنتهي النقطة', 'HI': 'एक अंक तक औसत आदान-प्रदान', 'VI': 'Số lần qua lại trung bình mỗi điểm', 'ES': 'Promedio de golpes por punto', 'TH': 'จำนวนครั้งตีโต้เฉลี่ยต่อแต้ม'},
  'assists': {'EN': 'Times a teammate scored from my pass', 'JA': '自分のパスで味方が得点した回数', 'ZH': '队友借我的传球得分的次数', 'FR': 'Buts marqués par un coéquipier sur ma passe', 'DE': 'Tore von Mitspielern nach meinem Pass', 'RU': 'Голы партнёров после моей передачи', 'AR': 'مرات سجّل فيها زميل من تمريرتي', 'HI': 'मेरे पास से साथी ने गोल किया', 'VI': 'Số lần đồng đội ghi bàn từ đường chuyền của tôi', 'ES': 'Veces que un compañero anotó con mi pase', 'TH': 'จำนวนครั้งที่เพื่อนทำแต้มจากการส่งของฉัน'},
  'paceMinPerKm': {'EN': 'Average time per 1 km (auto) · shorter is faster', 'JA': '1kmにかかった平均時間（自動）· 短いほど速い', 'ZH': '每公里平均用时（自动）· 越短越快', 'FR': 'Temps moyen par km (auto) · plus court = plus rapide', 'DE': 'Ø Zeit pro km (auto) · kürzer = schneller', 'RU': 'Среднее время на 1 км (авто) · меньше — быстрее', 'AR': 'متوسط الوقت لكل كم (تلقائي) · الأقل أسرع', 'HI': '1 किमी का औसत समय (ऑटो) · कम = तेज़', 'VI': 'Thời gian TB mỗi km (tự tính) · càng ngắn càng nhanh', 'ES': 'Tiempo medio por km (auto) · menos = más rápido', 'TH': 'เวลาเฉลี่ยต่อ 1 กม. (อัตโนมัติ) · ยิ่งน้อยยิ่งเร็ว'},
  'maxPaceMinPerKm': {'EN': 'Time of your fastest 1 km', 'JA': '一番速かった1km区間の時間', 'ZH': '最快 1 公里的用时', 'FR': 'Temps de votre km le plus rapide', 'DE': 'Zeit deines schnellsten Kilometers', 'RU': 'Время самого быстрого км', 'AR': 'وقت أسرع كيلومتر', 'HI': 'सबसे तेज़ 1 किमी का समय', 'VI': 'Thời gian km nhanh nhất', 'ES': 'Tiempo de tu km más rápido', 'TH': 'เวลาของกิโลเมตรที่เร็วที่สุด'},
  'cadenceSpm': {'EN': 'Steps per minute · running is usually 160–180', 'JA': '1分間の歩数 · ランニングは通常160〜180', 'ZH': '每分钟步数 · 跑步通常 160~180', 'FR': 'Pas par minute · en course 160–180', 'DE': 'Schritte pro Minute · beim Laufen meist 160–180', 'RU': 'Шагов в минуту · при беге обычно 160–180', 'AR': 'خطوات في الدقيقة · للجري عادة 160–180', 'HI': 'प्रति मिनट कदम · दौड़ में आमतौर पर 160–180', 'VI': 'Số bước mỗi phút · chạy thường 160–180', 'ES': 'Pasos por minuto · corriendo suele ser 160–180', 'TH': 'ก้าวต่อนาที · วิ่งปกติ 160–180'},
  'maxCadenceSpm': {'EN': 'Highest steps per minute at any moment', 'JA': '一番速く足を運んだ瞬間の1分あたり歩数', 'ZH': '最快时每分钟步数', 'FR': 'Cadence la plus élevée atteinte', 'DE': 'Höchste Schritte pro Minute', 'RU': 'Максимум шагов в минуту', 'AR': 'أعلى عدد خطوات في الدقيقة', 'HI': 'सबसे ज़्यादा प्रति मिनट कदम', 'VI': 'Số bước/phút cao nhất', 'ES': 'Cadencia máxima alcanzada', 'TH': 'ก้าวต่อนาทีสูงสุด'},
  'avgStrideCm': {'EN': 'Average length of one step', 'JA': '1歩の平均の長さ', 'ZH': '每步平均长度', 'FR': 'Longueur moyenne d\'un pas', 'DE': 'Durchschnittliche Schrittlänge', 'RU': 'Средняя длина шага', 'AR': 'متوسط طول الخطوة', 'HI': 'एक कदम की औसत लंबाई', 'VI': 'Độ dài trung bình một bước', 'ES': 'Longitud media de un paso', 'TH': 'ความยาวเฉลี่ยต่อก้าว'},
  'avgStrideM': {'EN': 'Average length of one step', 'JA': '1歩の平均の長さ', 'ZH': '每步平均长度', 'FR': 'Longueur moyenne d\'un pas', 'DE': 'Durchschnittliche Schrittlänge', 'RU': 'Средняя длина шага', 'AR': 'متوسط طول الخطوة', 'HI': 'एक कदम की औसत लंबाई', 'VI': 'Độ dài trung bình một bước', 'ES': 'Longitud media de un paso', 'TH': 'ความยาวเฉลี่ยต่อก้าว'},
  'golf.roundCount': {'EN': 'Games played today · 18 holes once = 1 round', 'JA': '今日プレーした回数 · 18ホール1回で1ラウンド', 'ZH': '今天打的场数 · 18 洞一次为 1 轮', 'FR': 'Parties jouées aujourd\'hui · 18 trous = 1 tour', 'DE': 'Heute gespielte Runden · 18 Löcher = 1 Runde', 'RU': 'Сыграно сегодня · 18 лунок = 1 раунд', 'AR': 'الجولات اليوم · 18 حفرة = جولة واحدة', 'HI': 'आज खेले राउंड · 18 होल = 1 राउंड', 'VI': 'Số vòng hôm nay · 18 lỗ = 1 vòng', 'ES': 'Rondas de hoy · 18 hoyos = 1 ronda', 'TH': 'จำนวนรอบวันนี้ · 18 หลุม = 1 รอบ'},
  'golf.teePosition': {'EN': 'Where you hit the first shot · Black is farthest, Red closest', 'JA': '最初のショットを打つ位置 · ブラックが最も遠くレッドが最も近い', 'ZH': '开球位置 · 黑色最远，红色最近', 'FR': 'Départ du premier coup · noir le plus loin, rouge le plus près', 'DE': 'Abschlagposition · Schwarz am weitesten, Rot am nächsten', 'RU': 'Место первого удара · чёрная дальше всех, красная ближе', 'AR': 'مكان الضربة الأولى · الأسود الأبعد والأحمر الأقرب', 'HI': 'पहला शॉट कहाँ से · काला सबसे दूर, लाल सबसे पास', 'VI': 'Vị trí phát bóng · Đen xa nhất, Đỏ gần nhất', 'ES': 'Salida del primer golpe · negras más lejos, rojas más cerca', 'TH': 'จุดตีแรก · ดำไกลสุด แดงใกล้สุด'},
  'golf.parTotal': {'EN': 'Sum of par for all holes · 18 holes is usually 72', 'JA': '全ホールの基準打数の合計 · 18ホールは通常72', 'ZH': '所有洞标准杆之和 · 18 洞通常 72', 'FR': 'Somme des par · 18 trous = souvent 72', 'DE': 'Summe aller Pars · 18 Löcher meist 72', 'RU': 'Сумма пар всех лунок · обычно 72', 'AR': 'مجموع البار لكل الحفر · عادة 72', 'HI': 'सभी होल का पार जोड़ · 18 होल में आमतौर पर 72', 'VI': 'Tổng par các lỗ · 18 lỗ thường là 72', 'ES': 'Suma de pares · 18 hoyos suele ser 72', 'TH': 'ผลรวมพาร์ทุกหลุม · 18 หลุมปกติ 72'},
  'golf.totalScore': {'EN': 'All strokes for 18 (or 9) holes', 'JA': '18（または9）ホールで打った総打数', 'ZH': '18（或 9）洞的总杆数', 'FR': 'Total des coups sur 18 (ou 9) trous', 'DE': 'Alle Schläge auf 18 (oder 9) Löchern', 'RU': 'Все удары за 18 (или 9) лунок', 'AR': 'كل الضربات في 18 (أو 9) حفرة', 'HI': '18 (या 9) होल के कुल स्ट्रोक', 'VI': 'Tổng số gậy 18 (hoặc 9) lỗ', 'ES': 'Todos los golpes en 18 (o 9) hoyos', 'TH': 'จำนวนสโตรกทั้งหมด 18 (หรือ 9) หลุม'},
  'golf.scoreToPar': {'EN': 'My strokes − par (auto)', 'JA': '自分の打数 − 基準打数（自動）', 'ZH': '我的杆数 − 标准杆（自动）', 'FR': 'Mes coups − par (auto)', 'DE': 'Meine Schläge − Par (auto)', 'RU': 'Мои удары − пар (авто)', 'AR': 'ضرباتي − البار (تلقائي)', 'HI': 'मेरे स्ट्रोक − पार (ऑटो)', 'VI': 'Số gậy − par (tự tính)', 'ES': 'Mis golpes − par (auto)', 'TH': 'สโตรกของฉัน − พาร์ (อัตโนมัติ)'},
  'golf.putts': {'EN': 'Total strokes rolled on the green (putts)', 'JA': 'グリーン上で転がして打った打数の合計', 'ZH': '果岭上推杆总数', 'FR': 'Total des putts sur le green', 'DE': 'Summe der Putts auf dem Grün', 'RU': 'Сумма паттов на грине', 'AR': 'مجموع الضربات على الخضراء', 'HI': 'ग्रीन पर कुल पट', 'VI': 'Tổng số gậy gạt trên green', 'ES': 'Total de putts en el green', 'TH': 'จำนวนพัตต์บนกรีนรวม'},
  'golf.threePutts': {'EN': 'Holes where you putted 3 or more times', 'JA': 'グリーンで3回以上打ったホール数', 'ZH': '果岭上推了 3 次以上的洞数', 'FR': 'Trous avec 3 putts ou plus', 'DE': 'Löcher mit 3 oder mehr Putts', 'RU': 'Лунки с 3 и более паттами', 'AR': 'حفر بثلاث ضربات أو أكثر على الخضراء', 'HI': 'जिन होल पर 3+ पट', 'VI': 'Số lỗ gạt từ 3 lần', 'ES': 'Hoyos con 3 o más putts', 'TH': 'หลุมที่พัตต์ 3 ครั้งขึ้นไป'},
  'golf.eagle': {'EN': 'Eagle · finished a hole 2 under par', 'JA': 'イーグル · 基準より2打少なく終えたホール', 'ZH': '老鹰球 · 比标准杆少 2 杆', 'FR': 'Eagle · 2 coups sous le par', 'DE': 'Eagle · 2 unter Par', 'RU': 'Игл · на 2 удара меньше пара', 'AR': 'إيغل · أقل من البار بضربتين', 'HI': 'ईगल · पार से 2 कम', 'VI': 'Eagle · ít hơn par 2 gậy', 'ES': 'Eagle · 2 bajo par', 'TH': 'อีเกิล · ต่ำกว่าพาร์ 2'},
  'golf.birdie': {'EN': 'Birdie · finished a hole 1 under par', 'JA': 'バーディ · 基準より1打少なく終えたホール', 'ZH': '小鸟球 · 比标准杆少 1 杆', 'FR': 'Birdie · 1 coup sous le par', 'DE': 'Birdie · 1 unter Par', 'RU': 'Бёрди · на 1 удар меньше пара', 'AR': 'بيردي · أقل من البار بضربة', 'HI': 'बर्डी · पार से 1 कम', 'VI': 'Birdie · ít hơn par 1 gậy', 'ES': 'Birdie · 1 bajo par', 'TH': 'เบอร์ดี้ · ต่ำกว่าพาร์ 1'},
  'golf.bogeyOrWorse': {'EN': 'Bogey or worse · 1 or more over par', 'JA': 'ボギー以上 · 基準より1打以上多いホール', 'ZH': '柏忌以上 · 比标准杆多 1 杆以上', 'FR': 'Bogey ou pire · 1 coup ou plus au-dessus du par', 'DE': 'Bogey oder schlechter · 1+ über Par', 'RU': 'Богги и хуже · на 1+ больше пара', 'AR': 'بوجي أو أسوأ · أكثر من البار بضربة أو أكثر', 'HI': 'बोगी या बदतर · पार से 1+ ज़्यादा', 'VI': 'Bogey trở lên · hơn par từ 1 gậy', 'ES': 'Bogey o peor · 1 o más sobre par', 'TH': 'โบกี้ขึ้นไป · เกินพาร์ 1 ขึ้นไป'},
  'golf.fairwaysHit': {'EN': 'Holes where the tee shot landed on the fairway · out of 14 (no par 3s)', 'JA': 'ティーショットがフェアウェイに落ちたホール数 · パー3を除く14ホール中', 'ZH': '开球落在球道上的洞数 · 不含 3 杆洞，共 14 个', 'FR': 'Trous où le départ atterrit sur le fairway · sur 14 (sans par 3)', 'DE': 'Löcher mit Abschlag auf dem Fairway · von 14 (ohne Par 3)', 'RU': 'Лунки, где первый удар попал на фервей · из 14', 'AR': 'حفر هبطت فيها الضربة الأولى على الممر · من 14', 'HI': 'जिन होल पर पहला शॉट फ़ेयरवे पर · 14 में से', 'VI': 'Số lỗ phát bóng vào fairway · trên 14 lỗ (trừ par 3)', 'ES': 'Hoyos con salida en calle · de 14 (sin par 3)', 'TH': 'หลุมที่ตีแรกลงแฟร์เวย์ · จาก 14 หลุม (ไม่รวมพาร์ 3)'},
  'golf.greensInRegulation': {'EN': 'Holes where you reached the green 2 strokes under par · out of 18', 'JA': '基準より2打少なくグリーンに乗せたホール数 · 18ホール中', 'ZH': '以标准杆减 2 杆上果岭的洞数 · 共 18 个', 'FR': 'Trous où le green est atteint en par − 2 · sur 18', 'DE': 'Grüns in Regulation · von 18', 'RU': 'Грины в регуляции · из 18', 'AR': 'حفر وصلت فيها الخضراء قبل البار بضربتين · من 18', 'HI': 'पार − 2 में ग्रीन पर पहुँचे होल · 18 में से', 'VI': 'Số lỗ lên green đúng chuẩn · trên 18', 'ES': 'Greens en regulación · de 18', 'TH': 'หลุมที่ขึ้นกรีนตามเกณฑ์ · จาก 18'},
  'golf.ob': {'EN': 'Penalty strokes for out of bounds or water', 'JA': 'ボールがOBや池に入って受けた罰打', 'ZH': '出界或落水的罚杆数', 'FR': 'Coups de pénalité (hors limites ou eau)', 'DE': 'Strafschläge für Aus oder Wasser', 'RU': 'Штрафные удары за аут или воду', 'AR': 'ضربات جزاء للخروج أو الماء', 'HI': 'आउट ऑफ़ बाउंड्स या पानी की पेनल्टी', 'VI': 'Gậy phạt do OB hoặc rơi nước', 'ES': 'Golpes de penalidad por fuera de límites o agua', 'TH': 'สโตรกโทษจากออกนอกเขตหรือตกน้ำ'},
  'swimming.laps': {'EN': 'One length of a 25 m pool = 1 lap', 'JA': '25mプールの端まで1回で1本', 'ZH': '25 米泳池游一趟算 1 次', 'FR': 'Une longueur de bassin de 25 m = 1', 'DE': 'Eine 25-m-Bahn = 1', 'RU': 'Один бассейн 25 м = 1', 'AR': 'طول مسبح 25 م = لفة واحدة', 'HI': '25 मी पूल की एक लंबाई = 1', 'VI': 'Một chiều bể 25 m = 1', 'ES': 'Un largo de piscina de 25 m = 1', 'TH': 'สระ 25 ม. หนึ่งเที่ยว = 1'},
  'swimming.pacePer100m': {'EN': 'Average time per 100 m (auto)', 'JA': '100mにかかった平均時間（自動）', 'ZH': '每 100 米平均用时（自动）', 'FR': 'Temps moyen par 100 m (auto)', 'DE': 'Ø Zeit pro 100 m (auto)', 'RU': 'Среднее время на 100 м (авто)', 'AR': 'متوسط الوقت لكل 100 م (تلقائي)', 'HI': 'प्रति 100 मी औसत समय (ऑटो)', 'VI': 'Thời gian TB mỗi 100 m (tự tính)', 'ES': 'Tiempo medio por 100 m (auto)', 'TH': 'เวลาเฉลี่ยต่อ 100 ม. (อัตโนมัติ)'},
  'swimming.maxPacePer100m': {'EN': 'Time of your fastest 100 m', 'JA': '一番速かった100m区間の時間', 'ZH': '最快 100 米的用时', 'FR': 'Temps de vos 100 m les plus rapides', 'DE': 'Zeit deiner schnellsten 100 m', 'RU': 'Время самых быстрых 100 м', 'AR': 'وقت أسرع 100 م', 'HI': 'सबसे तेज़ 100 मी का समय', 'VI': 'Thời gian 100 m nhanh nhất', 'ES': 'Tiempo de tus 100 m más rápidos', 'TH': 'เวลาของ 100 ม. ที่เร็วที่สุด'},
  'swimming.strokeCountPerLap': {'EN': 'Average arm strokes per 25 m', 'JA': '25mを泳ぐ間の平均ストローク数', 'ZH': '每 25 米平均划水次数', 'FR': 'Mouvements de bras moyens par 25 m', 'DE': 'Ø Armzüge pro 25 m', 'RU': 'Среднее число гребков на 25 м', 'AR': 'متوسط ضربات الذراع لكل 25 م', 'HI': 'प्रति 25 मी औसत हाथ स्ट्रोक', 'VI': 'Số sải tay TB mỗi 25 m', 'ES': 'Brazadas medias por 25 m', 'TH': 'จังหวะแขนเฉลี่ยต่อ 25 ม.'},
  'swimming.swolf': {'EN': 'Seconds per 25 m + strokes (auto) · lower is more efficient', 'JA': '25mの秒数 + ストローク数（自動）· 低いほど効率的', 'ZH': '25 米秒数 + 划水次数（自动）· 越低越高效', 'FR': 'Secondes par 25 m + mouvements (auto) · plus bas = plus efficace', 'DE': 'Sekunden pro 25 m + Züge (auto) · niedriger = effizienter', 'RU': 'Секунды на 25 м + гребки (авто) · меньше — эффективнее', 'AR': 'ثواني 25 م + الضربات (تلقائي) · الأقل أكفأ', 'HI': '25 मी के सेकंड + स्ट्रोक (ऑटो) · कम = बेहतर', 'VI': 'Giây mỗi 25 m + số sải (tự tính) · càng thấp càng tốt', 'ES': 'Segundos por 25 m + brazadas (auto) · menos = más eficiente', 'TH': 'วินาทีต่อ 25 ม. + จังหวะแขน (อัตโนมัติ) · ยิ่งต่ำยิ่งดี'},
  'gym.exerciseName': {'EN': 'e.g. Bench Press, Squat, Lat Pulldown', 'JA': '例：ベンチプレス、スクワット、ラットプルダウン', 'ZH': '例如：卧推、深蹲、高位下拉', 'FR': 'ex. Développé couché, Squat, Tirage vertical', 'DE': 'z. B. Bankdrücken, Kniebeuge, Latzug', 'RU': 'напр. Жим лёжа, Присед, Тяга блока', 'AR': 'مثال: ضغط البنش، القرفصاء، السحب العلوي', 'HI': 'जैसे बेंच प्रेस, स्क्वाट, लैट पुलडाउन', 'VI': 'vd. Đẩy ngực, Squat, Kéo xô', 'ES': 'p. ej. Press de banca, Sentadilla, Jalón', 'TH': 'เช่น เบนช์เพรส สควอท แลตพูลดาวน์'},
  'gym.rir': {'EN': 'Reps you could still have done when the set ended', 'JA': 'セット終了時に余力でまだできた回数', 'ZH': '完成一组时还能再做的次数', 'FR': 'Répétitions encore possibles en fin de série', 'DE': 'Wiederholungen, die noch möglich gewesen wären', 'RU': 'Сколько повторов ещё мог сделать', 'AR': 'التكرارات التي كان يمكنك إضافتها', 'HI': 'सेट के अंत में और कितने हो सकते थे', 'VI': 'Số lần còn làm thêm được khi hết hiệp', 'ES': 'Repeticiones que aún podías hacer', 'TH': 'จำนวนครั้งที่ยังทำต่อได้เมื่อจบเซ็ต'},
  'gym.tempo': {'EN': 'e.g. 3-1-1 → lower 3 s, pause 1 s, lift 1 s', 'JA': '例：3-1-1 → 下ろす3秒、止める1秒、上げる1秒', 'ZH': '例：3-1-1 → 下放 3 秒、停 1 秒、上推 1 秒', 'FR': 'ex. 3-1-1 → descente 3 s, pause 1 s, montée 1 s', 'DE': 'z. B. 3-1-1 → 3 s ab, 1 s Pause, 1 s hoch', 'RU': 'напр. 3-1-1 → вниз 3 с, пауза 1 с, вверх 1 с', 'AR': 'مثال 3-1-1 ← إنزال 3 ث، توقف 1 ث، رفع 1 ث', 'HI': 'जैसे 3-1-1 → नीचे 3 से., रुकें 1 से., ऊपर 1 से.', 'VI': 'vd. 3-1-1 → hạ 3 giây, dừng 1 giây, nâng 1 giây', 'ES': 'p. ej. 3-1-1 → bajar 3 s, pausa 1 s, subir 1 s', 'TH': 'เช่น 3-1-1 → ลง 3 วิ หยุด 1 วิ ขึ้น 1 วิ'},
  'gym.toFailure': {'EN': 'Did you go until you could not do one more in the last set?', 'JA': '最後のセットをこれ以上できないところまでやったか', 'ZH': '最后一组是否做到力竭', 'FR': 'Dernière série jusqu\'à l\'échec ?', 'DE': 'Letzten Satz bis zum Muskelversagen?', 'RU': 'Последний подход до отказа?', 'AR': 'هل وصلت للإنهاك في المجموعة الأخيرة؟', 'HI': 'क्या आख़िरी सेट थकने तक किया?', 'VI': 'Hiệp cuối có tập đến kiệt sức không?', 'ES': '¿Llegaste al fallo en la última serie?', 'TH': 'เซ็ตสุดท้ายทำจนหมดแรงหรือไม่'},
  'gym.volumeLoad': {'EN': 'Weight × reps added over all sets (auto)', 'JA': '重さ × 回数を全セットで足した値（自動）', 'ZH': '所有组的重量 × 次数之和（自动）', 'FR': 'Poids × répétitions sur toutes les séries (auto)', 'DE': 'Gewicht × Wdh. über alle Sätze (auto)', 'RU': 'Вес × повторы по всем подходам (авто)', 'AR': 'الوزن × التكرار لكل المجموعات (تلقائي)', 'HI': 'सभी सेट का वज़न × दोहराव (ऑटो)', 'VI': 'Mức tạ × số lần cộng mọi hiệp (tự tính)', 'ES': 'Peso × reps de todas las series (auto)', 'TH': 'น้ำหนัก × ครั้ง รวมทุกเซ็ต (อัตโนมัติ)'},
  'gym.estimated1rm': {'EN': 'Estimated heaviest weight you could lift once (auto)', 'JA': '1回で持ち上げられる最大重量の推定値（自動）', 'ZH': '估算一次能举起的最大重量（自动）', 'FR': 'Charge max estimée sur 1 répétition (auto)', 'DE': 'Geschätztes Maximalgewicht für 1 Wdh. (auto)', 'RU': 'Оценка максимального веса на 1 раз (авто)', 'AR': 'أقصى وزن مُقدَّر لتكرار واحد (تلقائي)', 'HI': 'एक बार में उठ सकने वाला अनुमानित अधिकतम वज़न (ऑटो)', 'VI': 'Mức tạ tối đa ước tính cho 1 lần (tự tính)', 'ES': 'Peso máximo estimado a 1 repetición (auto)', 'TH': 'น้ำหนักสูงสุดที่ยกได้ 1 ครั้งโดยประมาณ (อัตโนมัติ)'},
  'pilates.coreHoldTimeSec': {'EN': 'Total time you held with your core (belly and back) tight', 'JA': '腹と腰（体幹）に力を入れて耐えた時間の合計', 'ZH': '收紧核心（腹部和腰部）坚持的总时间', 'FR': 'Temps total de gainage', 'DE': 'Gesamtzeit mit angespannter Körpermitte', 'RU': 'Общее время удержания с напряжённым корпусом', 'AR': 'إجمالي وقت شد عضلات الجذع', 'HI': 'कोर (पेट और कमर) कसकर टिके रहने का कुल समय', 'VI': 'Tổng thời gian giữ siết cơ lõi', 'ES': 'Tiempo total con el core activado', 'TH': 'เวลารวมที่เกร็งแกนกลางลำตัว'},
  'pilates.breathScore': {'EN': 'Your own score for breathing well with the moves', 'JA': '動作に合わせてうまく呼吸できたかの自己採点', 'ZH': '自评动作配合呼吸的分数', 'FR': 'Note perso de la respiration pendant les mouvements', 'DE': 'Selbstbewertung der Atmung zu den Übungen', 'RU': 'Самооценка дыхания во время движений', 'AR': 'تقييمك لتنفسك مع الحركات', 'HI': 'हरकतों के साथ साँस की अपनी रेटिंग', 'VI': 'Tự chấm điểm hơi thở theo động tác', 'ES': 'Tu nota de la respiración con los movimientos', 'TH': 'คะแนนที่ให้ตัวเองเรื่องการหายใจตามท่า'},
  'yoga.asanaCount': {'EN': 'Number of yoga poses (asanas) today', 'JA': '今日行ったヨガのポーズ（アーサナ）の数', 'ZH': '今天做的瑜伽体式数', 'FR': 'Nombre de postures (asanas) aujourd\'hui', 'DE': 'Anzahl der heutigen Yoga-Haltungen (Asanas)', 'RU': 'Сколько асан сегодня', 'AR': 'عدد وضعيات اليوغا اليوم', 'HI': 'आज के योग आसनों की संख्या', 'VI': 'Số tư thế yoga (asana) hôm nay', 'ES': 'Número de posturas (asanas) de hoy', 'TH': 'จำนวนท่าโยคะ (อาสนะ) วันนี้'},
  'yoga.breathingTimeMin': {'EN': 'Time spent practicing breathing only', 'JA': '呼吸だけを練習した時間', 'ZH': '单独练习呼吸的时间', 'FR': 'Temps consacré uniquement à la respiration', 'DE': 'Zeit nur für Atemübungen', 'RU': 'Время только на дыхательные практики', 'AR': 'وقت تمارين التنفس فقط', 'HI': 'केवल साँस के अभ्यास का समय', 'VI': 'Thời gian chỉ tập thở', 'ES': 'Tiempo solo de respiración', 'TH': 'เวลาที่ฝึกหายใจอย่างเดียว'},
  'yoga.inversionCount': {'EN': 'Number of upside-down poses (like a headstand)', 'JA': '逆立ちのように頭が下になるポーズの数', 'ZH': '倒立类（头朝下）体式数', 'FR': 'Nombre de postures inversées (comme sur la tête)', 'DE': 'Anzahl Umkehrhaltungen (z. B. Kopfstand)', 'RU': 'Число перевёрнутых поз (как стойка на голове)', 'AR': 'عدد الوضعيات المقلوبة (مثل الوقوف على الرأس)', 'HI': 'उल्टे आसनों की संख्या (जैसे शीर्षासन)', 'VI': 'Số tư thế đảo ngược (như trồng chuối)', 'ES': 'Número de inversiones (como el pino)', 'TH': 'จำนวนท่ากลับหัว (เช่น ยืนด้วยศีรษะ)'},
  'hiking.peakAltitudeM': {'EN': 'Height of the highest point you reached (above sea level)', 'JA': '登った中で最も高い地点の高さ（海抜）', 'ZH': '到达的最高点海拔', 'FR': 'Altitude du point le plus haut atteint', 'DE': 'Höhe des höchsten erreichten Punkts (ü. M.)', 'RU': 'Высота самой высокой точки (над уровнем моря)', 'AR': 'ارتفاع أعلى نقطة وصلتها (فوق سطح البحر)', 'HI': 'पहुँचे सबसे ऊँचे बिंदु की ऊँचाई (समुद्र तल से)', 'VI': 'Độ cao điểm cao nhất (so với mực nước biển)', 'ES': 'Altitud del punto más alto alcanzado', 'TH': 'ความสูงของจุดสูงสุดที่ไปถึง (จากระดับน้ำทะเล)'},
  'hiking.ascentPaceMinPerKm': {'EN': 'Average time per 1 km on uphills', 'JA': '上り坂で1kmにかかった平均時間', 'ZH': '上坡每公里平均用时', 'FR': 'Temps moyen par km en montée', 'DE': 'Ø Zeit pro km bergauf', 'RU': 'Среднее время на 1 км в подъём', 'AR': 'متوسط الوقت لكل كم في الصعود', 'HI': 'चढ़ाई पर प्रति किमी औसत समय', 'VI': 'Thời gian TB mỗi km khi lên dốc', 'ES': 'Tiempo medio por km en subida', 'TH': 'เวลาเฉลี่ยต่อ 1 กม. ขาขึ้น'},
  'cycling.avgSpeedKmh': {'EN': 'Calculated automatically as distance ÷ time', 'JA': '距離 ÷ 時間で自動計算', 'ZH': '按距离 ÷ 时间自动计算', 'FR': 'Calculé auto : distance ÷ temps', 'DE': 'Automatisch: Strecke ÷ Zeit', 'RU': 'Автоматически: расстояние ÷ время', 'AR': 'تُحسب تلقائيًا: المسافة ÷ الوقت', 'HI': 'अपने आप: दूरी ÷ समय', 'VI': 'Tự tính: quãng đường ÷ thời gian', 'ES': 'Automático: distancia ÷ tiempo', 'TH': 'คำนวณอัตโนมัติ: ระยะทาง ÷ เวลา'},
  'cycling.avgCadenceRpm': {'EN': 'Pedal turns per minute · usually 80–100', 'JA': '1分間にペダルを回した回数 · 通常80〜100', 'ZH': '每分钟踏板转数 · 通常 80~100', 'FR': 'Tours de pédale par minute · souvent 80–100', 'DE': 'Kurbelumdrehungen pro Minute · meist 80–100', 'RU': 'Оборотов педалей в минуту · обычно 80–100', 'AR': 'دورات الدواسة في الدقيقة · عادة 80–100', 'HI': 'प्रति मिनट पैडल चक्कर · आमतौर पर 80–100', 'VI': 'Số vòng đạp mỗi phút · thường 80–100', 'ES': 'Pedaladas por minuto · normalmente 80–100', 'TH': 'รอบบันไดต่อนาที · ปกติ 80–100'},
  'cycling.maxCadenceRpm': {'EN': 'Highest pedal turns per minute', 'JA': '一番速くペダルを回した瞬間の1分あたり回転数', 'ZH': '最快时每分钟踏板转数', 'FR': 'Cadence de pédalage maximale', 'DE': 'Höchste Trittfrequenz', 'RU': 'Максимум оборотов педалей', 'AR': 'أعلى دورات للدواسة في الدقيقة', 'HI': 'सबसे ज़्यादा पैडल चक्कर प्रति मिनट', 'VI': 'Số vòng đạp/phút cao nhất', 'ES': 'Cadencia máxima de pedaleo', 'TH': 'รอบบันไดต่อนาทีสูงสุด'},
  'cycling.avgPowerWatts': {'EN': 'Average pedaling power · only with a power meter', 'JA': 'ペダルを踏む力の平均 · パワーメーターがある時だけ', 'ZH': '平均踩踏功率 · 有功率计时才填', 'FR': 'Puissance moyenne · seulement avec capteur de puissance', 'DE': 'Ø Tretleistung · nur mit Powermeter', 'RU': 'Средняя мощность · только с датчиком мощности', 'AR': 'متوسط قدرة الدوس · فقط مع مقياس القدرة', 'HI': 'औसत पैडल पावर · केवल पावर मीटर हो तो', 'VI': 'Công suất đạp TB · chỉ khi có máy đo', 'ES': 'Potencia media · solo con potenciómetro', 'TH': 'กำลังปั่นเฉลี่ย · เฉพาะเมื่อมีพาวเวอร์มิเตอร์'},
  'cycling.maxPowerWatts': {'EN': 'Highest pedaling power · only with a power meter', 'JA': '一番強く踏んだ瞬間の力 · パワーメーターがある時だけ', 'ZH': '最大踩踏功率 · 有功率计时才填', 'FR': 'Puissance max · seulement avec capteur', 'DE': 'Höchste Tretleistung · nur mit Powermeter', 'RU': 'Максимальная мощность · только с датчиком', 'AR': 'أعلى قدرة دوس · فقط مع مقياس القدرة', 'HI': 'सबसे ज़्यादा पैडल पावर · केवल पावर मीटर हो तो', 'VI': 'Công suất đạp cao nhất · chỉ khi có máy đo', 'ES': 'Potencia máxima · solo con potenciómetro', 'TH': 'กำลังปั่นสูงสุด · เฉพาะเมื่อมีพาวเวอร์มิเตอร์'},
  'tennis.gamesWon': {'EN': 'Games you won, added over all sets', 'JA': '全セットで自分が取ったゲーム数の合計', 'ZH': '所有盘中我赢的局数之和', 'FR': 'Jeux gagnés sur toutes les manches', 'DE': 'Gewonnene Spiele aller Sätze', 'RU': 'Выигранные геймы во всех сетах', 'AR': 'مجموع الأشواط التي فزت بها', 'HI': 'सभी सेट में जीते गेम', 'VI': 'Tổng số game thắng các set', 'ES': 'Juegos ganados en todos los sets', 'TH': 'จำนวนเกมที่ชนะรวมทุกเซ็ต'},
  'tennis.aces': {'EN': 'Serves the opponent could not even touch (aces)', 'JA': '相手がラケットに当てられなかったサーブ（エース）', 'ZH': '对手碰不到的发球（ACE）', 'FR': 'Services que l\'adversaire n\'a pas touchés (aces)', 'DE': 'Aufschläge, die der Gegner nicht berührte (Asse)', 'RU': 'Подачи, которые соперник не задел (эйсы)', 'AR': 'إرسالات لم يلمسها الخصم (إيس)', 'HI': 'सर्व जिन्हें विरोधी छू न सका (एस)', 'VI': 'Giao bóng đối thủ không chạm được (ace)', 'ES': 'Saques que el rival no tocó (aces)', 'TH': 'เสิร์ฟที่คู่แข่งแตะไม่ได้ (เอซ)'},
  'tennis.doubleFaults': {'EN': 'Points lost when both serves missed (double faults)', 'JA': '2回のサーブが両方入らず失った点（ダブルフォルト）', 'ZH': '两次发球都失误丢的分（双误）', 'FR': 'Points perdus sur deux services ratés (doubles fautes)', 'DE': 'Punkte durch zwei Fehlaufschläge (Doppelfehler)', 'RU': 'Очки, потерянные на двух ошибках подачи', 'AR': 'نقاط ضاعت بفشل الإرسالين (خطأ مزدوج)', 'HI': 'दोनों सर्व चूकने पर गँवाए अंक (डबल फ़ॉल्ट)', 'VI': 'Điểm mất do hỏng cả hai lần giao (lỗi kép)', 'ES': 'Puntos perdidos por doble falta', 'TH': 'แต้มที่เสียเพราะเสิร์ฟพลาดสองครั้ง (ดับเบิลฟอลต์)'},
  'tennis.firstServePct': {'EN': 'Share of first serves that went in (auto)', 'JA': 'ファーストサーブが入った割合（自動）', 'ZH': '一发成功率（自动）', 'FR': 'Pourcentage de premières balles (auto)', 'DE': 'Quote erster Aufschläge (auto)', 'RU': 'Процент попадания первой подачи (авто)', 'AR': 'نسبة نجاح الإرسال الأول (تلقائي)', 'HI': 'पहली सर्व सफल प्रतिशत (ऑटो)', 'VI': 'Tỉ lệ giao bóng 1 vào (tự tính)', 'ES': 'Porcentaje de primeros saques (auto)', 'TH': 'สัดส่วนเสิร์ฟแรกที่ลง (อัตโนมัติ)'},
  'tennis.firstServePointsPct': {'EN': 'Share of points won when the first serve went in', 'JA': 'ファーストサーブが入ったポイントのうち取った割合', 'ZH': '一发成功后得分比例', 'FR': 'Points gagnés sur première balle', 'DE': 'Gewonnene Punkte nach erstem Aufschlag', 'RU': 'Выигранные очки после первой подачи', 'AR': 'نسبة النقاط المكسوبة بعد الإرسال الأول', 'HI': 'पहली सर्व के बाद जीते अंक का प्रतिशत', 'VI': 'Tỉ lệ thắng điểm khi giao bóng 1 vào', 'ES': 'Puntos ganados con primer saque', 'TH': 'สัดส่วนแต้มที่ชนะเมื่อเสิร์ฟแรกลง'},
  'badminton.smashAttempts': {'EN': 'Times you hit a high shuttle down hard', 'JA': '高く上がった球を強く打ち下ろした回数', 'ZH': '把高球大力扣杀的次数', 'FR': 'Smashs tentés', 'DE': 'Smash-Versuche', 'RU': 'Попытки смэша', 'AR': 'محاولات الضربة الساحقة', 'HI': 'स्मैश प्रयास', 'VI': 'Số lần đập cầu', 'ES': 'Intentos de remate', 'TH': 'จำนวนครั้งที่ตบ'},
  'badminton.dropShotSuccessRate': {'EN': 'Success rate of soft shots dropped near the net', 'JA': 'ネット際に軽く落とすショット（ドロップ）の成功率', 'ZH': '网前吊球成功率', 'FR': 'Taux de réussite des amortis', 'DE': 'Erfolgsquote der Stoppbälle', 'RU': 'Процент удачных укороченных', 'AR': 'نسبة نجاح ضربات الإسقاط قرب الشبكة', 'HI': 'नेट के पास ड्रॉप शॉट सफलता दर', 'VI': 'Tỉ lệ bỏ nhỏ thành công', 'ES': 'Porcentaje de dejadas exitosas', 'TH': 'อัตราสำเร็จของลูกหยอดหน้าเน็ต'},
  'tabletennis.serveSpinType': {'EN': 'Topspin = ball spins forward · Backspin = spins backward', 'JA': 'トップスピン=前回転 · バックスピン=後ろ回転', 'ZH': '上旋 = 向前转 · 下旋 = 向后转', 'FR': 'Lift = rotation avant · Coupé = rotation arrière', 'DE': 'Topspin = Vorwärtsdrall · Backspin = Rückwärtsdrall', 'RU': 'Топспин — вращение вперёд · Бэкспин — назад', 'AR': 'الدوران الأمامي والدوران الخلفي', 'HI': 'टॉपस्पिन = आगे घूमे · बैकस्पिन = पीछे घूमे', 'VI': 'Xoáy lên = xoáy về trước · Xoáy xuống = xoáy về sau', 'ES': 'Liftado = gira hacia delante · Cortado = hacia atrás', 'TH': 'ท็อปสปิน = หมุนไปหน้า · แบ็กสปิน = หมุนกลับ'},
  'tabletennis.forehandWinners': {'EN': 'Points won directly with forehand (racket-hand side)', 'JA': 'ラケットを持つ手側（フォアハンド）で打ってすぐ取った点', 'ZH': '正手直接得分', 'FR': 'Points gagnants en coup droit', 'DE': 'Direkte Punkte mit Vorhand', 'RU': 'Очки сразу с удара справа', 'AR': 'نقاط مباشرة بالضربة الأمامية', 'HI': 'फ़ोरहैंड से सीधे जीते अंक', 'VI': 'Điểm ăn ngay bằng thuận tay', 'ES': 'Puntos directos de derecha', 'TH': 'แต้มที่ได้ทันทีจากโฟร์แฮนด์'},
  'tabletennis.backhandWinners': {'EN': 'Points won directly with backhand (other side)', 'JA': 'ラケットの反対側（バックハンド）で打ってすぐ取った点', 'ZH': '反手直接得分', 'FR': 'Points gagnants en revers', 'DE': 'Direkte Punkte mit Rückhand', 'RU': 'Очки сразу с удара слева', 'AR': 'نقاط مباشرة بالضربة الخلفية', 'HI': 'बैकहैंड से सीधे जीते अंक', 'VI': 'Điểm ăn ngay bằng trái tay', 'ES': 'Puntos directos de revés', 'TH': 'แต้มที่ได้ทันทีจากแบ็กแฮนด์'},
  'basketball.reboundsOff': {'EN': 'Missed shots by my team that you caught (offensive rebounds)', 'JA': '味方のシュートが外れて跳ねた球を取った回数（オフェンスリバウンド）', 'ZH': '我方投篮不中后抢到的篮板（前场篮板）', 'FR': 'Rebonds offensifs', 'DE': 'Offensive Rebounds', 'RU': 'Подборы в нападении', 'AR': 'المتابعات الهجومية', 'HI': 'आक्रामक रिबाउंड', 'VI': 'Bắt bóng bật bảng tấn công', 'ES': 'Rebotes ofensivos', 'TH': 'รีบาวด์เกมรุก'},
  'basketball.reboundsDef': {'EN': 'Missed shots by the opponent that you caught (defensive rebounds)', 'JA': '相手のシュートが外れて跳ねた球を取った回数（ディフェンスリバウンド）', 'ZH': '对方投篮不中后抢到的篮板（后场篮板）', 'FR': 'Rebonds défensifs', 'DE': 'Defensive Rebounds', 'RU': 'Подборы в защите', 'AR': 'المتابعات الدفاعية', 'HI': 'रक्षात्मक रिबाउंड', 'VI': 'Bắt bóng bật bảng phòng thủ', 'ES': 'Rebotes defensivos', 'TH': 'รีบาวด์เกมรับ'},
  'soccer.position': {'EN': 'GK goalkeeper · DF defense · MF midfield · FW forward', 'JA': 'GK ゴールキーパー · DF 守備 · MF 中盤 · FW 攻撃', 'ZH': 'GK 守门员 · DF 后卫 · MF 中场 · FW 前锋', 'FR': 'GK gardien · DF défense · MF milieu · FW attaque', 'DE': 'GK Torwart · DF Abwehr · MF Mittelfeld · FW Sturm', 'RU': 'GK вратарь · DF защита · MF полузащита · FW нападение', 'AR': 'GK حارس · DF دفاع · MF وسط · FW هجوم', 'HI': 'GK गोलकीपर · DF डिफ़ेंस · MF मिडफ़ील्ड · FW फ़ॉरवर्ड', 'VI': 'GK thủ môn · DF hậu vệ · MF tiền vệ · FW tiền đạo', 'ES': 'GK portero · DF defensa · MF medio · FW delantero', 'TH': 'GK ผู้รักษาประตู · DF กองหลัง · MF กองกลาง · FW กองหน้า'},
  'soccer.sprintCount': {'EN': 'Times you ran short bursts at full speed', 'JA': '全力で短く走った回数', 'ZH': '全力短冲次数', 'FR': 'Nombre de sprints', 'DE': 'Anzahl Sprints', 'RU': 'Количество рывков', 'AR': 'عدد مرات العدو السريع', 'HI': 'पूरी ताक़त से छोटी दौड़ की संख्या', 'VI': 'Số lần chạy nước rút', 'ES': 'Número de sprints', 'TH': 'จำนวนครั้งที่วิ่งเต็มกำลังระยะสั้น'},
  'soccer.shotsOnTarget': {'EN': 'Shots that went toward the goal, not wide', 'JA': '外れずにゴール枠へ飛んだシュート数', 'ZH': '射正次数', 'FR': 'Tirs cadrés', 'DE': 'Schüsse aufs Tor', 'RU': 'Удары в створ', 'AR': 'التسديدات على المرمى', 'HI': 'निशाने पर शॉट', 'VI': 'Sút trúng đích', 'ES': 'Tiros a puerta', 'TH': 'ยิงตรงกรอบ'},
  'soccer.tackleSuccessRate': {'EN': 'Success rate of winning the ball with a tackle', 'JA': '足を出して相手のボールを奪うのに成功した割合', 'ZH': '抢断成功率', 'FR': 'Taux de tacles réussis', 'DE': 'Erfolgsquote der Tacklings', 'RU': 'Процент удачных отборов', 'AR': 'نسبة نجاح الافتكاك', 'HI': 'टैकल सफलता दर', 'VI': 'Tỉ lệ tắc bóng thành công', 'ES': 'Porcentaje de entradas exitosas', 'TH': 'อัตราสำเร็จของการแย่งบอล'},
  'skiing.slopeType': {'EN': 'Alpine = normal slope · Cross-country = flat travel · Backcountry = ungroomed mountain', 'JA': 'アルパイン=通常ゲレンデ · クロスカントリー=平地移動 · バックカントリー=未整備の山', 'ZH': '高山=普通雪道 · 越野=平地滑行 · 野雪=未压雪山地', 'FR': 'Alpin = piste classique · Fond = plat · Hors-piste = montagne non damée', 'DE': 'Alpin = Piste · Langlauf = flach · Backcountry = ungespurt', 'RU': 'Горные — обычный склон · Беговые — равнина · Бэккантри — без подготовки', 'AR': 'ألبي = منحدر عادي · ريفي = أرض مستوية · خلفي = جبل غير مجهز', 'HI': 'अल्पाइन = सामान्य ढलान · क्रॉस-कंट्री = समतल · बैककंट्री = बिना तैयार पहाड़', 'VI': 'Alpine = dốc thường · Băng đồng = đường bằng · Backcountry = núi tự nhiên', 'ES': 'Alpino = pista normal · Fondo = llano · Fuera pista = montaña sin pisar', 'TH': 'อัลไพน์ = ลานปกติ · ครอสคันทรี = พื้นราบ · แบ็กคันทรี = ภูเขาไม่ปรับแต่ง'},
  'skiing.totalDescentM': {'EN': 'Total height of all your descents', 'JA': '滑り降りた高さの合計', 'ZH': '下滑高度总和', 'FR': 'Somme de toutes les descentes', 'DE': 'Summe aller Abfahrten', 'RU': 'Сумма высоты всех спусков', 'AR': 'مجموع ارتفاع كل النزلات', 'HI': 'सभी उतराई की कुल ऊँचाई', 'VI': 'Tổng độ cao đã trượt xuống', 'ES': 'Suma de todos los descensos', 'TH': 'ความสูงที่ลงทั้งหมดรวมกัน'},
};

/// 입력칸 한 줄 설명 찾기 ('종목id.칸이름' 먼저, 없으면 '칸이름') — 지금 고른 언어로
String? exerciseFieldHelp(String typeId, String fieldKey) {
  final String lang = appLanguage.current;
  if (appLanguage.isDefault) {
    return kExerciseFieldHelpKo['$typeId.$fieldKey'] ?? kExerciseFieldHelpKo[fieldKey];
  }
  final Map<String, String>? row = kExerciseFieldHelpI18n['$typeId.$fieldKey'] ?? kExerciseFieldHelpI18n[fieldKey];
  return row?[lang] ?? row?['EN'];
}
